Seq-annot ::= {
  data ftable {
    {
      id local str "gene_1",
      data gene {
      },
      location int {
        from 149,
        to 1199,
        strand plus,
        id local id 381
      },
      qual {
        {
          qual "gene_id",
          val "381.000"
        },
        {
          qual "real",
          val "X"
        }
      }
    },
    {
      id local str "mrna_2",
      data rna {
        type mRNA
      },
      location mix {
        int {
          from 149,
          to 199,
          strand plus,
          id local id 381
        },
        int {
          from 299,
          to 400,
          strand plus,
          id local id 381
        },
        int {
          from 799,
          to 850,
          strand plus,
          id local id 381
        },
        int {
          from 500,
          to 649,
          strand plus,
          id local id 381
        },
        int {
          from 699,
          to 799,
          strand plus,
          id local id 381
        },
        int {
          from 899,
          to 999,
          strand plus,
          id local id 381
        },
        int {
          from 1099,
          to 1199,
          strand plus,
          id local id 381
        }
      },
      qual {
        {
          qual "gene_id",
          val "381.000"
        },
        {
          qual "real",
          val "X"
        },
        {
          qual "transcript_id",
          val "381.000.1"
        }
      },
      xref {
        {
          id local str "gene_1"
        }
      }
    },
    {
      id local str "cds_3",
      data cdregion {
      },
      location mix {
        int {
          from 379,
          to 400,
          strand plus,
          id local id 381
        },
        int {
          from 500,
          to 649,
          strand plus,
          id local id 381
        },
        int {
          from 699,
          to 709,
          strand plus,
          id local id 381
        }
      },
      qual {
        {
          qual "gene_id",
          val "381.000"
        },
        {
          qual "transcript_id",
          val "381.000.1"
        }
      },
      xref {
        {
          id local str "mrna_2"
        },
        {
          id local str "gene_1"
        }
      }
    }
  }
}
