Seq-entry ::= set {
  class nuc-prot,
  descr {
    source {
      org {
        taxname "Citrobacter rodentium",
        db {
          {
            db "taxon",
            tag id 67825
          }
        },
        syn {
          "Citrobacter sp. biovar 4280",
          "Citrobacter genomospecies 9"
        },
        orgname {
          name binomial {
            genus "Citrobacter",
            species "rodentium"
          },
          mod {
            {
              subtype strain,
              subname "ATCC 51459"
            },
            {
              subtype culture-collection,
              subname "ATCC:51459"
            }
          },
          lineage "Bacteria; Proteobacteria; Gammaproteobacteria;
 Enterobacteriales; Enterobacteriaceae; Citrobacter",
          gcode 11,
          div "BCT"
        }
      }
    },
    pub {
      pub {
        gen {
          cit "Unpublished",
          authors {
            names std {
              {
                name name {
                  last "Lenz",
                  first "Abigail",
                  initials "A."
                }
              },
              {
                name name {
                  last "Tomkins",
                  first "Jeffrey",
                  initials "J."
                }
              },
              {
                name name {
                  last "Fabich",
                  first "Andrew",
                  initials "A."
                }
              }
            }
          },
          title "Draft Genome Sequence of Citrobacter rodentium strain ATCC
 51459, A Primary Model of Enterohemorrhagic Escherichia coli Virulance"
        }
      }
    },
    user {
      type str "DBLink",
      data {
        {
          label str "BioProject",
          num 1,
          data strs {
            "PRJNA261533"
          }
        },
        {
          label str "BioSample",
          num 1,
          data strs {
            "SAMN03115005"
          }
        }
      }
    }
  },
  seq-set {
    seq {
      id {
        local str "Contig361"
      },
      descr {
        molinfo {
          biomol genomic
        },
        user {
          type str "StructuredComment",
          data {
            {
              label str "StructuredCommentPrefix",
              data str "##Genome-Assembly-Data-START##"
            },
            {
              label str "Assembly Date",
              data str "23-JAN-2015"
            },
            {
              label str "Assembly Method",
              data str "Bio Star Illumina v. JAN-2015"
            },
            {
              label str "Genome Representation",
              data str "Full"
            },
            {
              label str "Expected Final Version",
              data str "Yes"
            },
            {
              label str "Genome Coverage",
              data str "50.0x"
            },
            {
              label str "Sequencing Technology",
              data str "Illumina MiSeq"
            },
            {
              label str "StructuredCommentSuffix",
              data str "##Genome-Assembly-Data-END##"
            }
          }
        },
        user {
          class "Interim Storage",
          type str "Input Seq-ids",
          data {
            {
              label str "Input Seq-ids",
              data strs {
                "lcl|Contig361"
              }
            }
          }
        },
        create-date std {
          year 2015,
          month 1,
          day 30
        }
      },
      inst {
        repr raw,
        mol dna,
        length 472,
        seq-data ncbi2na 'FF4534F8C9DDEC4B5B1201D531B3A711FD4F869E69777E407714
B818D2BC2DBFFC0A51E0BC9FDDDBFECC0010C6B291E5B525088405949FD4FCF7C1A2C2D3E3FD70
9D4033F02CCCF33ACCF4CE0CAB847A653CFB905000871DE00628023FFD79783C8C68BC98CE0058
106D38DFBC08CF8AFFE9B35FB77B'H
      }
    }
  }
}
