Seq-entry ::= set {
  class nuc-prot,
  descr {
    source {
      org {
        taxname "Listeria monocytogenes",
        db {
          {
            db "taxon",
            tag id 1639
          }
        },
        syn {
          "Listerella hepatolytica",
          "Erysipelothrix monocytogenes",
          "Corynebacterium parvulum",
          "Corynebacterium infantisepticum",
          "Bacterium monocytogenes hominis",
          "Bacterium monocytogenes"
        },
        orgname {
          name binomial {
            genus "Listeria",
            species "monocytogenes"
          },
          mod {
            {
              subtype strain,
              subname "MOD1_LS1005"
            },
            {
              subtype serovar,
              subname "4"
            }
          },
          lineage "Bacteria; Firmicutes; Bacilli; Bacillales; Listeriaceae;
 Listeria",
          gcode 11,
          div "BCT"
        }
      },
      subtype {
        {
          subtype country,
          name "USA: CA"
        },
        {
          subtype isolation-source,
          name "white peach"
        },
        {
          subtype collection-date,
          name "2014-07-31"
        },
        {
          subtype collected-by,
          name "FDA"
        }
      }
    },
    pub {
      pub {
        gen {
          cit "Unpublished",
          authors {
            names std {
              {
                name name {
                  last "Timme",
                  first "Ruth",
                  initials "R."
                }
              },
              {
                name name {
                  last "Allard",
                  first "Marc",
                  initials "M.W."
                }
              },
              {
                name name {
                  last "Strain",
                  first "Errol",
                  initials "E."
                }
              },
              {
                name name {
                  last "Evans",
                  first "Peter",
                  initials "P.S."
                }
              },
              {
                name name {
                  last "Brown",
                  first "Eric",
                  initials "E."
                }
              }
            },
            affil std {
              affil "United States Food and Drug Administration",
              div "Center for Food Safety and Applied Nutrition",
              city "College Park",
              sub "MD",
              country "USA",
              street "HFS-712 5100 Paint Branch Parkway",
              email "ruth.timme@fda.hhs.gov",
              phone "240-402-2196",
              postal-code "20003"
            }
          },
          title "Whole genome shotgun sequencing of cultured foodborne
 pathogen."
        }
      }
    },
    user {
      type str "DBLink",
      data {
        {
          label str "BioSample",
          num 1,
          data strs {
            "SAMN02991390"
          }
        },
        {
          label str "BioProject",
          num 1,
          data strs {
            "PRJNA215355"
          }
        }
      }
    }
  },
  seq-set {
    seq {
      id {
        local str "CFSAN023504_contig0062"
      },
      descr {
        molinfo {
          biomol genomic,
          tech wgs,
          completeness partial
        },
        comment "Bacterial culture available from Dwayne Roberson, FDA College
 Park Campus, 5100 Paint Branch Parkway, College Park, MD 20740.",
        user {
          type str "StructuredComment",
          data {
            {
              label str "StructuredCommentPrefix",
              data str "##Genome-Assembly-Data-START##"
            },
            {
              label str "Assembly Method",
              data str "SPAdes v. 3.0.0"
            },
            {
              label str "Assembly Name",
              data str "CFSAN023504_01.0"
            },
            {
              label str "Genome Coverage",
              data str "60X"
            },
            {
              label str "Sequencing Technology",
              data str "Illumina MiSeq"
            },
            {
              label str "StructuredCommentSuffix",
              data str "##Genome-Assembly-Data-END##"
            }
          }
        },
        user {
          class "Interim Storage",
          type str "Input Seq-ids",
          data {
            {
              label str "Input Seq-ids",
              data strs {
                "gnl|PRJNA215355|CFSAN023504_contig0062",
                "lcl|CFSAN023504_contig0062"
              }
            }
          }
        },
        create-date std {
          year 2015,
          month 7,
          day 17
        }
      },
      inst {
        repr raw,
        mol dna,
        length 78,
        strand ds,
        seq-data iupacna "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA"
      }
    }
  }
}
