--$Revision: 1.4 $
--**********************************************************************
--
--  Biological Macromolecule 3-D Structure Data Types for MMDB,
--                A Molecular Modeling Database
--
--  Definitions for structural features
--
--  By Hitomi Ohkawa, Jim Ostell, and Steve Bryant 
--
--  National Center for Biotechnology Information
--  National Institutes of Health
--  Bethesda, MD 20894 USA
--
--  February, 1995
--
--**********************************************************************

MMDB-Structural-features DEFINITIONS ::=

BEGIN

EXPORTS Model-feature, Density-coordinate-set, Surface-coordinate-set, 
	Residue-pntrs, RealValue;

IMPORTS Molecule-id, Residue-id FROM MMDB-Chemical-graph
	Model-descr, Atom-pntrs, Component-pntr FROM MMDB-Structural-model;

-- Named model features refer to sets of residues or atoms, or a region in 
-- the model space.  A few specific feature types are allowed for compatibility
-- with PDB usage, but the purpose of a named model feature is simply to
-- associate a text and/or citation-based description with a set of atoms or 
-- residues, or a spatially-defined region of the model structure.  They also
-- support association of numeric or character-defined properties with each
-- residue or atom of a set.

-- PDB-derived secondary structure defines a single feature, represented as a
-- sequence of residue motifs.  The contents of PDB SITE and FTNOTE records
-- define features represented as sequences of atom motifs.  NCBI-assigned core
-- and secondary structure descriptions are represented as a sequence of 
-- residue motifs, and cited as a data deposition in the feature description.

Model-feature ::= SEQUENCE{
	descr			Model-descr,
	motif			SEQUENCE OF Structural-motif }
	
Structural-motif ::=	CHOICE {
	residue-motif	Residue-motif,
	atom-motif	Atom-motif,
	region-motif	Region-motif } 

-- Residue motifs describe secondary structure or other features defined on a 
-- set of residues.  PDB secondary structure classifications from HELIX, SHEET,
-- and TURN records appear as residue motifs.  The residue motif name is in this
-- case derived from the PDB "identifier" field.

Residue-motif ::= SEQUENCE {
	descr			Model-descr,
	type			ENUMERATED {
					helix(1),
					strand(2),
					sheet(3),
					turn(4),
					other(255) },
	residue-ids		Residue-pntrs,
	residue-props		SEQUENCE OF Properties OPTIONAL }


Residue-pntrs ::= SEQUENCE {
	number-of-ptrs		INTEGER,
	molecule-ids		SEQUENCE OF Molecule-id,
	residue-ids		SEQUENCE OF Residue-id }

-- Properties are intended to represent anything describable by numbers or
-- text, for example the surface accessibility of a residue, the chemical
-- shift of an atom, or a code for a local environment category.  The intended
-- meaning must be specified by the name and description.  The number of
-- properties with a given description is assumed to be the same as the number
-- of residues, atoms, or surface points they describe, but this is not a
-- requirement of the specification.  No properties are defined for PDB-derived
-- structural features.

Properties ::= SEQUENCE {
	name			VisibleString,
	descr			SEQUENCE OF VisibleString OPTIONAL,
	number-of-props		INTEGER,
	props			CHOICE {
					numeric		Num-props,
					text		Text-props } }
Num-props ::= SEQUENCE {
	scale-factor		INTEGER,
	property		SEQUENCE OF INTEGER }

Text-props ::= SEQUENCE OF VisibleString

-- Atom motifs describe binding sites, catalytic sites, or other features
-- defined on a set of atoms.  For PDB SITE and FTNOTE records atom motifs
-- are named according to "site identifier" or "footnote number" fields, and 
-- their description contains comments extracted from FTNOTE records, and from
-- REMARK records if these could be linked to a particular SITE record.

Atom-motif ::= SEQUENCE {
	descr			Model-descr,
	atom-ids		Atom-pntrs,
	atom-props		SEQUENCE OF Properties OPTIONAL }

-- Region motifs describe features of substructures defined by spatial location,
-- such as the portion of a density grid believed to contain a binding site.

Region-motif ::= SEQUENCE {
	descr			Model-descr,
	region-boundary		CHOICE {
					sphere		Sphere,
					cylinder	Cylinder,
					brick		Brick,
					surface		Surface-grid },
	region-props		SEQUENCE OF Properties OPTIONAL	}

-- Geometrical primitives are used in the definition of region motifs, and 
-- also non-atomic coordinates.  Spheres, cylinders and bricks are defined by 
-- a few points in the model space.

Sphere ::= SEQUENCE { 
	center			Model-space-point,
	radius			RealValue }

Cylinder ::= SEQUENCE { 
	axis-top		Model-space-point,
	axis-bottom		Model-space-point,
	radius			RealValue }

-- A brick is defined by the coordinates of eight corners.  These are assumed
-- to appear in the order 000, 001, 010, 011, 100, 101, 110, 111, where the 
-- digits 0 and 1 refer to respectively to the x, y and z axes of a unit cube.
-- Opposite edges are assumed to be parallel. 

Brick ::= SEQUENCE {
	corner-000		Model-space-point,
	corner-001		Model-space-point,
	corner-010		Model-space-point,
	corner-011		Model-space-point,
	corner-100		Model-space-point,
	corner-101		Model-space-point,
	corner-110		Model-space-point,
	corner-111		Model-space-point}

-- A grid boundary is a set of points which are assumed to define a triangle
-- mesh surface when each is connected to it's 3 nearest neighbors.

Surface-grid ::= SEQUENCE {
	number-of-points	INTEGER,
	scale-factor		INTEGER,
	x			SEQUENCE OF INTEGER,
	y			SEQUENCE OF INTEGER,
	z			SEQUENCE OF INTEGER }

Model-space-point ::= SEQUENCE {
	x			RealValue,
	y			RealValue,
	z			RealValue } 

RealValue ::= SEQUENCE {
	scale-factor		INTEGER,
	scaled-integer-value	INTEGER }

-- Literal density coordinates define the chemical components whose structure
-- is described by a density grid, parameters of this grid, and density values.

Density-coordinate-set ::= SEQUENCE {
	descr			Model-descr,
	contents		Component-pntr,
	grid-corners		Brick,
	grid-steps-x		INTEGER,
	grid-steps-y		INTEGER,
	grid-steps-z		INTEGER,
	fastest-varying		ENUMERATED {
					x(1),
					y(2),
					z(3)},
	slowest-varying		ENUMERATED {
					x(1),
					y(2),
					z(3)},
	scale-factor		INTEGER,
	density			SEQUENCE OF INTEGER }

-- Literal surface coordinates define the chemical components whose structure
-- is described by a surface, and the surface itself.  The surface may be
-- either a regular geometric solid or a triangle-mesh of arbitrary shape.

Surface-coordinate-set ::= SEQUENCE {
	descr			Model-descr,
	contents		Component-pntr,
	surface			CHOICE {
		sphere		Sphere,
		cylinder	Cylinder,
		brick		Brick,
		surface		Surface-grid } ,
	surface-props		SEQUENCE OF Properties OPTIONAL	}


END
