# $Id$

APP = merge_tree
SRC = merge_tree_app  


LIB = xmergetree  \
      $(DATA_LOADERS_UTIL_LIB) $(SRAREAD_LIBS) $(OBJMGR_LIBS) $(LMDB_LIB) \
      $(GENBANK_LIBS) $(SEQ_LIBS) 
LIBS = $(BLAST_THIRD_PARTY_LIBS) $(GENBANK_THIRD_PARTY_LIBS) $(CMPRS_LIBS) \
       $(DATA_LOADERS_UTIL_LIBS) $(LMDB_LIBS) $(NETWORK_LIBS) $(DL_LIBS) \
       $(ORIG_LIBS)
