Seq-entry ::= set {
  class pop-set,
  seq-set {
    seq {
      id {
        local str "seq1"
      },
      inst {
        repr raw,
        mol na,
        length 62,
        seq-data ncbi2na '90939390033A393900FF9A54E4E39390'H
      }
    },
    seq {
      id {
        local str "seq3"
      },
      inst {
        repr raw,
        mol na,
        length 62,
        seq-data ncbi2na '3990939003933A3900FFA954E4E59390'H
      }
    }
  },
  annot {
    {
      data align {
        {
          type not-set,
          dim 2,
          segs denseg {
            dim 2,
            numseg 11,
            ids {
              local str "seq1",
              local str "seq3"
            },
            starts {
              -1,
              0,
              0,
              2,
              2,
              -1,
              4,
              4,
              -1,
              20,
              20,
              22,
              22,
              -1,
              24,
              24,
              -1,
              54,
              54,
              -1,
              56,
              56
            },
            lens {
              2,
              2,
              2,
              16,
              2,
              2,
              2,
              30,
              2,
              2,
              6
            }
          }
        }
      }
    }
  }
}
