Seq-align ::= {
  type not-set,
  dim 3,
  segs denseg {
    dim 3,
    numseg 3,
    ids {
      local str "03_TAJ",
      local str "04_TAJ",
      local str "08_TAJ"
    },
    starts {
      0,
      0,
      0,
      -1,
      12,
      12,
      -1,
      -1,
      15
    },
    lens {
      12,
      3,
      3
    }
  }
}
