Seq-entry ::= set {
  class pop-set,
  seq-set {
    seq {
      id {
        local str "id1"
      },
      inst {
        repr raw,
        mol aa,
        length 567,
        seq-data iupacaa "MEAKLFVLFCTFTALKADTICIGYHANNSTDTVDTVLEKNVTVTHSVNLLEN
SHNGKLCSLNGIAPLQLGKCNVAGWLLGNPECDLLLTASSWSYIIETSNSENGTCYPGEFIDYEELREQLSSVSSFEK
FEIFPKASSWPNHETTKGVTAACSYSGASSFYRNLLWITEKGTSYPKLSKSYTNNKGKEVLVLWGVHHPPTTNEQQSL
YQNADAYVSVGSSKYNRRFTPEIAARPKVRGQAGRMNYYWTLLDQGDTITFEATGNLIAPWYAFALNKGSDSGIITSD
APVHNCDTKCQTPHGALNSSLPFQNVHPITIGECPKYVKSTKLRMATGLRNVPSIQSRGLFGAIAGFIEGGWTGMIDG
WYGYHHQNEQGSGYAADQKSTQSAIDGITNKVNSVIEKMNTQFTAVGKEFNNLERRIENLNKKVDDGFLNVWTYNAEL
LVLLENERTLDFHDSNVRNLYEKVKSQLRNNAKEIGNGCFEFYHKCDDECMESVKNGTYDYPKYSEESKLNREEIDGV
KLESMGVYQILAIYSTVASSLVLLVSLGAISFWMCSNGSLQCRICI*"
      }
    },
    seq {
      id {
        local str "id2"
      },
      inst {
        repr raw,
        mol aa,
        length 567,
        seq-data iupacaa "MEAKLFVLFCTFTVLKADTICVGYHANNSTDTVDTVLEKNVTVTHSVNLLED
SHNGKLCSLNGIAPLQLGKCNVAGWLLGNPECDLLLTANSWSYIIETSNSENGTCYPGEFIDYEELREQLSSVSSFEK
FEIFPKASSWPNHETTKGVTAACSYSGASSFYRNLLWITKKGTSYPKLSKSYTNNKGKEVLVLWGVHHPPSVSEQQSL
YQNADAYVSVGSSKYNRRFAPEIAARPKVRGQAGRMNYYWTLLDQGDTITFEATGNLIAPWYAFALNKGSDSGIITSD
APVHNCDTRCQTPHGALNSSLPFQNVHPITIGECPKYVKSTKLRMATGLRNVPSIQSRGLFGAIAGFIEGGWTGMIDG
WYGYHHQNEQGSGYAADQKSTQNAIDGITSKVNSVIEKMNTQFTAVGKEFNNLERRIENLNKKVDDGFLDVWTYNAEL
LVLLENERTLDFHDSNVRNLYEKVKSQLRNNAKEIGNGCFEFYHKCDDECMESVKNGTYDYPKYSEESKLNREEIDGV
KLESMGVYQILAIYSTVASSLVLLVSLGAISFWMCSNGSLQCRICI*"
      }
    }
  },
  annot {
    {
      data align {
        {
          type not-set,
          dim 2,
          segs denseg {
            dim 2,
            numseg 1,
            ids {
              local str "id1",
              local str "id2"
            },
            starts {
              0,
              0
            },
            lens {
              567
            }
          }
        }
      }
    }
  }
}
