Seq-entry ::= set {
  class nuc-prot,
  descr {
    source {
      genome genomic,
      org {
        taxname "Prunus dulcis",
        common "almond",
        db {
          {
            db "taxon",
            tag id 3755
          }
        },
        orgname {
          name binomial {
            genus "Prunus",
            species "dulcis"
          },
          attrib "specified",
          mod {
            {
              subtype cultivar,
              subname "Nonpareil"
            }
          },
          lineage "Eukaryota; Viridiplantae; Streptophyta; Embryophyta;
 Tracheophyta; Spermatophyta; Magnoliophyta; eudicotyledons; Gunneridae;
 Pentapetalae; rosids; fabids; Rosales; Rosaceae; Amygdaloideae; Amygdaleae;
 Prunus",
          gcode 1,
          mgcode 1,
          div "PLN",
          pgcode 11
        }
      },
      subtype {
        {
          subtype country,
          name "Australia"
        }
      }
    },
    pub {
      pub {
        gen {
          cit "Unpublished",
          authors {
            names std {
              {
                name name {
                  last "Goonetilleke",
                  first "Shashi",
                  initials "S.N."
                }
              },
              {
                name name {
                  last "Croxford",
                  first "Adam",
                  initials "A.E."
                }
              },
              {
                name name {
                  last "March",
                  first "Timothy",
                  initials "T.J."
                }
              },
              {
                name name {
                  last "Wirthensohn",
                  first "Michelle",
                  initials "M.G."
                }
              },
              {
                name name {
                  last "Mather",
                  first "Diane",
                  initials "D.E."
                }
              }
            }
          },
          title "Novel variation in the almond S-locus and in the proteins
 that underlie self-incompatibility"
        }
      }
    },
    pub {
      pub {
        sub {
          authors {
            names std {
              {
                name name {
                  last "Croxford",
                  first "Adam",
                  initials "A.E."
                }
              },
              {
                name name {
                  last "March",
                  first "Timothy",
                  initials "T.J."
                }
              },
              {
                name name {
                  last "Wirthensohn",
                  first "Michelle",
                  initials "M.G."
                }
              },
              {
                name name {
                  last "Mather",
                  first "Diane",
                  initials "D.E."
                }
              }
            },
            affil std {
              affil "University of Adelaide",
              div "School of Agriculture, Food and Wine",
              city "Adelaide",
              sub "SA",
              country "Australia",
              street "Hartley Grove, Urrbrae",
              postal-code "5064"
            }
          },
          medium email,
          date std {
            year 2018,
            month 3,
            day 6
          }
        }
      }
    },
    user {
      type str "Submission",
      data {
        {
          label str "SmartComment",
          data str "ALT EMAIL:shashi.goone@acpfg.com.au"
        },
        {
          label str "AdditionalComment",
          data str "BankIt2092437"
        }
      }
    },
    user {
      type str "Submission",
      data {
        {
          label str "SmartComment",
          data str "TOTAL # OF SEQS:1"
        }
      }
    },
    user {
      type str "NcbiCleanup",
      data {
        {
          label str "method",
          data str "ExtendedSeqEntryCleanup"
        },
        {
          label str "version",
          data int 1
        },
        {
          label str "month",
          data int 4
        },
        {
          label str "day",
          data int 9
        },
        {
          label str "year",
          data int 2019
        }
      }
    },
    update-date std {
      year 2019,
      month 4,
      day 9
    }
  },
  seq-set {
    seq {
      id {
        local str "S7_haplotype",
        general {
          db "BankIt",
          tag str "2092437/S7_haplotype"
        },
        general {
          db "TMSMART",
          tag id 90976019
        },
        genbank {
          accession "MH029536"
        }
      },
      descr {
        title "Prunus dulcis cultivar Nonpareil F-box protein (SLF7) gene,
 partial cds; and ribonuclease (S7-RNase) and S haplotype-specific F-box7
 (SFB7) genes, complete cds.",
        molinfo {
          biomol genomic
        },
        user {
          type str "StructuredComment",
          data {
            {
              label str "StructuredCommentPrefix",
              data str "##Assembly-Data-START##"
            },
            {
              label str "Assembly Method",
              data str "Burrows-Wheeler v. 0.6"
            },
            {
              label str "Assembly Name",
              data str "BWA-mem algorithm"
            },
            {
              label str "Sequencing Technology",
              data str "Illumina"
            },
            {
              label str "StructuredCommentSuffix",
              data str "##Assembly-Data-END##"
            }
          }
        },
        user {
          type str "Submission",
          data {
            {
              label str "AdditionalComment",
              data str "LocalID:S7_haplotype"
            }
          }
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "LocalId",
              data str "S7_haplotype"
            },
            {
              label str "General",
              data str "gnl|BankIt|2092437/S7_haplotype"
            },
            {
              label str "General",
              data str "gnl|TMSMART|90976019"
            },
            {
              label str "GenBank",
              data str "gb|MH029536|"
            }
          }
        },
        user {
          class "1.0",
          type str "AutodefOptions",
          data {
            {
              label str "UseLabels",
              data bool TRUE
            },
            {
              label str "LeaveParenthetical",
              data bool TRUE
            },
            {
              label str "SpecifyNuclearProduct",
              data bool TRUE
            },
            {
              label str "MaxMods",
              data int 0
            },
            {
              label str "FeatureListType",
              data str "List All Features"
            },
            {
              label str "MiscFeatRule",
              data str "Delete"
            },
            {
              label str "HIVRule",
              data str "WantBoth"
            },
            {
              label str "ModifierList",
              data fields {
                {
                  label str "SubSources",
                  num 1,
                  data strs {
                    "clone"
                  }
                },
                {
                  label str "OrgMods",
                  num 1,
                  data strs {
                    "cultivar"
                  }
                }
              }
            }
          }
        }
      },
      inst {
        repr raw,
        mol dna,
        length 71953,
        strand ds,
        seq-data iupacna "ATGATGATGAGCATAACCTCAATTTTGTTGTTGAGGACATCAAGTTTCCACT
TTCTTCGGGACAATTTATTGGCCTCGAGGATGTAGAATCTCCAAGTATTTTAGGCCATTGTAATGGGATAGTTTGTCT
GAGTCCTTGTAGTGACAACCTTGTTTTATGCAATCCAGCAATCAAGGAAATCAAACTTCTACCCAAATCAGGCCTTCC
AGATTGGTGGGGATGTGCTGTAGGGTTTGGATATGATCCCAAATCTAAAGATTACAAAGTTAGTAGAATTGCATCTTA
TCAGGTGGAAATTGATGGTCTTATTCCTCCTCCTAGAGTTGAAATATACAGCCTCAGTACCGATTCTTGGAGAGAGAT
CAAGAATAATTCTTTAGAAACAGATACTACTTGCTTTTTTCCTGATTATTTCCAGATGTACTTCCAAGGAATTTGTTA
TTGGGTGGGGTATGAGCAACCAAAACAATCTGTGGAATACGAGGATGAGGAACAGAAGCCAATGGTCATTTTCTTCGA
CACGGGTGATGAAATATTTAATCATATATTATTTCCTGATAGTTTTTATATGTATGAGGAGGGATCATCTTATGCTTA
TGAAATGTCTTATCTTATGTATTGTGATCTGCGCATTATACTGTGGAATGGATCTATTGCTCTTTTTGGCTTTAATCG
TTTTAGTGTATTTCCTGACTCCTATGGAGTTTGGGTATTGGATGACTTTGACGGTGCTAAGGGTTCTTGGACAAAACA
CTTAACTTTTGAGCCATTGATGGGCATTAAGAGGGTATTGGAATTTTGGAGGAGTGACGAGATTCTTATGGTTACCGA
AGATGGAGATATAGTATCTTACAACCTTGCAACTCAGAAGCTTGAGAATCTTCCCATGAATAGCTTATCTGATTTCGA
AACTATTGTGTATGTGAATAGCTTAGTTTCGATCACAAGAGGCAACAAGCTTGAGAGTGTTGATATATAATTCTAGCA
ATATAATTTCTCTATTTTTTTTTTCTCATCCAAAAGCTTGATAAAAGATGTACCAATAAGGATGAAATTCTGTTGAAA
AGTACATTAAGGCTTGTTTGGTATCCTACTTGGATTGAATTTTATAAACTCAAAAACAAATTTTAAGTTCAAAGCTAC
AAAAATCTGTTTGATATGCCCATTTTTAAAAACCCAAACCCAAAATAAACTGAAAAGCACCCCTGAGGTTTTAGAGTC
ATTACTAGAGCTCTAACATTCCATGTGGCCATTGACTTTGGCAGTTTGACGTCTAAACCTGAATAGCATAAAAGAAAT
CACTACTCAAAACTCTTAGACATGTCATATGATTGATACTCATAATAATCTCACATCGATATTGTGTTGCAGAGATTT
AGGGAAAAGTGACATTTACTTGGCATTTGTTAAGCTTTGGTTCGTTAGAAATGGTACCGAAAGCACAATCAGCCCATT
ATTGCCTATGTAAAAAATGGTAGTCATATATGGGCTATAGTTATGAATCATGATGGCATTGGCGGTTGCGTTTCAAAG
TAAGTTGGGTTCAAACAATCATATGATTATGATATTAAAAGGTTTTAGGCTTCTAGCTATTAAATTATCAATTTGTAC
TACTTGGTTATAGAAACCTTCAAATGGAATCCTAATGGAGGGAATCGAAGCAATGACTTATTTTAATCATAACTCTTT
TTCTTCCCCAGCTCCATCCCCTGCTCCCCGACCCCCAATCTCCCTTCCGCCCCCAACGTAATTTTGCTGACTTTGGTG
AGCTTATTTTGGTACGTTGTTACGTGTATGTTGGGTGTGCAAGATCAAAGCAGTGGCTGGGGTGGGAGTTGTGGGTCG
AGGAAGTGGGGGGATATTGGTCGGAGAAGTGAGCGGGTGTTGCTGGAAATGGTTGCGTTTCCTTGAGACATCCCATCC
CACGTGTCCATGGACTTTAAAGTCTTAAGGTCAGTAGCATCAGGAAGTCATTATATTATTGTATTTTTCGGATTCCAA
AACTACCTCTATTTATAAGATAATGTGTTCTTTGGGAGAGGAGTAATGAATTTGGAAAGATCTCCAAATGGTTGTAAT
GGATGTAAGAATTAATTTAGAAACTTATTTGAAATTAAATATTAAATATTAAATTCAACATTAACGAATTAGTAATCT
ATAGGTGATTAACGTTTTGATTTATTTAATAAAAAATGATGTTGTTTTCCTTTTATGAATGAGTAATGCTATTTGGAC
ACACAATATTGACCACCTTAACTGACCACCTTATGTGGCAATTGATGTGTCATGTCATGTCAATTAATGAATGCTGCC
ATGAGGCCACTCACTAGGAATGCTAGGATTTTTTAATTGACATGGCAACATTCATTAATTGACATGGCATGACACATC
AGTTGCCACATAAGGTGGTCAATTAAGGTGGTCAATGTTGTGTGTCTAAATAGCATTACTCATAATGTATACCTAGTA
TAATGAACTTATTTTTTTCTTCTAAATAATGTATCTATTTTTAATTTATAAAAAAATGTGCATAAATTTCAATTATAC
AACGTACCTATTTTCTATAAATTATTGTGTACCTAATTCTAATTTATGAAAAATGTATGAAAATTTCAATTAAAAGTA
ACTGACCTAGTTTTTTTTAAAATTTTTTTTTTAATTTTTATAAATAATATACCTATATTTTTATACATATATATTAAT
ATTTTTCATAGGTACATTATTGGATATGTAATTTACATATTTTTTTTGTTTGCAATTTTAGGGGGCAATATGCTAGAG
AGAATGGTAACCAAAAGAAATGGGGTGATTGATGCTATTAATAGGGAATTTTAATTACAATTATGGCAGTTAATAAAA
TTGTAATAACCCAAAATAAAATATCTAAAAAGTAGGATTAATTTATTCTAGCAAAAAGACGATATTGCCATCGCATTA
TTTAATAGGGAAAAAGTTGACTTTTTGACCGACAAGGAATTTGGTAATTCCGCTTACGCCGTTGCGTAGGGCACGGCG
AAACGAGTTCATAGACACGGAGTAGACTCGAATCGGGGTTGTAACGAAGAAAATACGGTCAAAATACCGCGAAGGGCA
AAACGGTAATTTGGACAAAAGTCAGATTTTTATCTCTTTTCTTCTTTCTCTCTCCTCTCTCTCTCCTCCCGCGCCACC
AGCCGCGCGACCTCCGTCCCTTCTCGTCGTCACACCGGCCACCACAGGCCAAGCCGATCTCCGGCACCGGTACCAAAA
GCTCCGCCACACCCTTGCCGTCACGCCACGACCCGTCGCCGCCCTTGCCTCGGCCGAAGCTCGCCGGAAACTGGAGTT
TTCCATCGGTTTTCAGTCGAAACTTCAAGCTCCTCGATCTCATCCGTTTCTCCACCAAATCGTTCGAGTAAGGTATGG
TTTCTCACCTATTTTTTATGCTCTAACTGATGGATGGATGGGTTTTGATCGATTTTACCTCTAGATCACTCGATTTTC
AACTTGAAAATTGGTCGAATTTCGGCCGCCGTGATCGGCCATTTCCGGCCACTTTTTGGGGTATGTCCAAGAACAAAA
GTGACTCCAAATGGGGTGTTTTACCTAGGATAGGAGTTTGGAGTCTTGATTTCGAGTTTTTCCGGTAGCCTGGTATCG
CTTTAGACACCCAAATTGCCCGCTCGTGTGGTGGCTCGTGGGTGAGGGTAGTGAAGTGACTCTGTGTAGTTTTGCGAT
CCCCGTGTTGTCACGAGCGCGTAGAATTTCGCGGATCTCGATTTGGAGTCCGTTTGAGCCCCGAACGGATTTTCCATA
TTGGGCGATCCTTGGGTGCAGTGTCGTCGAGTCTTTGGATCGCACTCAATTTTGGATATATCTTTCTACATGATTTCA
GGATCGTGTAGGATTCGACGGATTGTGAATCGGAGTCCCGGATACTCCGAAATCGCGAACCCTAGGGCTAGGGTTTGG
ATTTTAAACGATAACGCGATTTTGGCTAATCCAACCTTCCGTTTCGGACCAAATTCGCGGAACATGGTTCTTTCTTTA
TGAGGAACCTTTAGAGAATCCCAGATTGGCCATCGGAGATCGTGGACCCCACGGGGTTCCGGATCGGCCGGTCTGGCA
GTTTATCGCTTAGTAAAGCTTCGGGTCTTTCAAGGCCGTTCTCGTTGTCTGAAAAGCTAAAGTGGGCTTAGGAGTGAC
TTGAAAATGAGTACACGCATTTCTAGGAGCCGGGGCAGGGTGTTTAATTTAATTCTTTTATTAAGTAGTTTAATTAAT
TTAATCTTTATGGGTAATCAGGCACCAAAGGCCAGACTGAGCTCAAGAAAGGACCTTTAAGAGGTCCTGCTAGCTGGG
ACCAGCTGTGAGTGGACTTTTTTCCATAAATGATTTTATATAAATGATTTTATATTGGTTTTATTTAAATAAGTTTAT
ATGCATGAATTTTATTATTTGATCTTGAATAAGTTTTATTGAAAGTTTCCGAGCATGATTAGTACAGTAATATTTCTA
TAATTTTATGCTGCTTAGTTACACATGCTAAAAGTTATAGAAACAGAGTGTGAGGTTTGAATCAAATGAGATAGCAGC
ATAATGTGAGATTACATTTATTAATCAGATTTTCTAAAGTAATTTATTTTAAAACCACCACGTACCCATTTTTATTTG
GTGATTACCCTTAGACGGACCGATGTCTACGGACATCTAGTCTGTTTACAGCTCTGTCAGTGCACTTGACATTGCCTC
ACGAGTTTCGGGGACGCTCGGATCGTGAGTGCCAGGATTTGCGGCTCGGCAGACTTGGTGTCCCGAGACCTGCCAGGA
TTTGCGGCTCGACTGACTCTGTGTCCCCGAGACCTGCCAGGATTGCGGATCAGGCTGACTACGGTCCCCTGTATCTTG
CCAGAGCGGCTTGAGTCGACTTGGTGTCATCGAGACCTGCTGGCGGGTCAGGCTGACCATAGTCCCCTGAATTCTGCC
AGTTTGCGGCTCGGATAGACTTTGTGTCACCGAGACCTGCCAGGGGATTTGACGGATTTTACAGGGGTACAATTAGGT
GGTAGTTTTAAAGAAATTTAAATACTTTTATACAGCTATTGCTTCCAGTCATTTTATATTAATTTTCTCAATATACGT
GCATGTTTTATATTTCCATATAATTGTTCAGTTTTACGAATTTATATACATACGATTATAAATATATTTAGATGAATA
CCTTATATTAAACACAGTTGAACTTTAGCTTTACTTATCAAGTTATTTTTACCATGGGGGTTATTATGATTATAAACT
GTTTTCAAGAACATTAATTTTTGTCCACTCACATTTTCAAACTTGTTTTTCGCCCCCAGGCTGTAGAAGTGCGCAGGC
ATTCACCACCGGGCCACTCTTAGCTTCGCATCACCAAGAAACGTAGGATTTTATTGTAAAAGTTCTTGAAATCTTGTA
AAGAATTAGAAAATGCTCTGATATATAGTTTTAGTGAGAAACTTGAGCTGGTGAATGCTTGGTTGTTTTATTCTGGCA
AGTTGGTGGAAAATTAATTGGTTGTTTAATAGGTGGAAGATTTTGGGTTTAGACAAAATACAGGGGAGACTCTGCCGA
ATTTTCGGCAGGAGTCTAAGAGAAGTTTTAATAGTAATTGTAACAGGAAGGGTAAAAAGGTCATTTGTGCCCGACATT
CGCCAGGTGTCGGACACCCACAGGACTTGGCTCGAATTCCAAAGTGGAATTGGGATCGGATCCTGTCAAAAATACTTG
GAATAAATTATAAATAAAATGTGGTGGGAAGGATTTGTGTTCAGGAGGTGGGTGTGTGTAGGGGAGTTGGGGCCTTTG
GGTCTGGCTGCGGAAAGTAGCTGGGAGAAAGAGAGAAGAAAGAAGGGGGGGCTAGATTGGATGGTAGTATCATCCTTT
GATTTTAATTTATTTTAGTTTTAGATTTTATTATTATTATTATTTTGGTAACAAGGGGACTAAGAGCCCATACCAAAA
TTTTAGATCTTATTTAATTATCCATTTTTAAATTGAATTCAAATATATCTATTTTTTAAATTAATATTTAAATAGTTT
TTAATTTTTTAAACATAAATATAACGGATTTGATCACATTGGCTAACGGTCCTAAACACAGAGATCAAATTGGCCAAA
TTAAAAACACAGAGATTAAATTGGCCAACATAATAAAATACATGGACTATTTTAACATTTAAGCCACCTAATATCCTT
AAAATTTTATTAAAAAATCCCCAGACATTTGTGCAGTGAACTTAAAAACCAATACATCACAAAATGGAAGAGAAATGA
GAGATGAGTGAATCACAATCTCTAAGAAGAAGATATCTGAATCACAAAATGAAACCAACTCATCTTTTACGTGAGTGT
TGAAATCAATTTGGACGATTCTGAGAAAAAAAAATAAAAAAAATAAAGAAATCGATTTGGAGGAGATAAACTCACTCC
TATTCAACGTCTCTGTTCATAAAATCAAATGAAACTGAACCCAAAGAAAAAATCAACCGAAACCCAAAACAAATAACT
AGCCAGAACTAAAGGGACATTCCAATACCAAAATGAAACAAAACCGGGAAGGAATCAACAGTCCAAAAGAACACAAGC
AAACTTCAAAAACCCAAATATGACTCCCAAAACAGTAGAAAACAAATAGAAAATTTGGACATCTTTAACAACAAGAAG
CTCTCCACAACCAAGACTCATGCCCACATACGGCCAAAGGCACCGCACGATCAACTTGCACTTGCTCCATGGGATTGA
AGCGACATTGACTTTGGCCCCTTCAAGGCACTGGCCACTAGGGTTACTGTTGGGATGCGTACGCTCCTTTACTTGGTA
TTTTATGGAAATTTTTTTTTTTTAATGTCAAAAATAAAAAGAAGTTAACTGAGTTAACTCTCTGTTAAGTTATACTAG
CACGCCTGCAAGAGGCTTCTTTTAAAAAATTTAAATTTCTTTTAGAATTAAAAAGATAATGGGTAGTTGTGTTTCATA
AAAATAGGATTCATTATTTGATTTTTTCTTTAATTGTAATTTTTTTTAATATGAAAAAGTGTGAATTTACCATATTAT
CCTCATTTAATTAATAATTTTAATTCTTTATGTTTGGATTAACTAAAGGGCATTTTCTGGTATTTTGAATGTTCACCA
TTCTCTCCTTTTTGCTTTATATATATAGATGACACATGTCAAATAACTAGGGAGGCGACATCAAATTAAAGACAGTGG
ATTCACTCCCTTATCCTATTGGTCATTTAAGTTTGAAATTGAGTTTTACACATAGATTTATAGAAAGATGGATATATG
TCTAGGAAATAAAAATTGTAGGAACCTATATTGGACAAGCTCTACAAAAACTGATTTTTAATTGGTTTTTGAATAGGT
TAGGTTTTAAGTTTTGTCTTTTTCTGTTTTTTTATATTATAAATAAACCCTTTTCTGTTTTATTTTTTATTTTTATAA
TAAACCTTTTTCTGTTTATTTGTTAACTGGATTCCTTGTATAAAAAATAAAAAAACCAAAGTTGGATGTACCTTTGCT
TACAATTTATAAGTCAGAGATTAATTGCGACAGTACACCCCATGCACCCTCCTATATAAGCAGCAAACACATTGAGTC
GTCGTAGCTCAGAAAGCCTCTATCATTCTGTTGTATTTCTTCTTGCTTTAGTATTTCCTAAGTATGGGGATGTTGAAA
TCGTCACTCGCTTTCCTTGTTCTTGGTTTTGCTTTCTTCTTTTGTTACGTTATGAGCAGTGGTGGGTTAAATTACAAT
CTTTTGCTATATGCATATAATCAGCTTTGCATTTTTCTACTTGTATTTGTTGTTCAGAGAAACTATTGTGTGTATTGG
ATGATATATCACATGACATGCGGTGTATTGAATTAACCCACATATTTTTCATTTAATCTAACGCACAACTTTCTTTGG
ATGAGTAAGTATTTGGGGATTGTTTTTGTTTTCATTATCTTTTGTTTATTCTGATAATTGGTTGCAATAAGTGCAGTC
TATTCATCACAATAATTTTGGCAGGATCTTATGACTATTTTCAATTTGTGCAACAATGGCCACCGACCAACTGCAGAG
TTCGCATGAAGCGACCTTGCTCCAATCCCCGGCCATTACAATATTTCACAATCCATGGCCTATGGCCAAGTAATTTTT
CAAACCCAACGAAGCCCAGTAATTGCAATGGGACTAAATTTGATGCAAGGAAAGTGGTACGTATTGATTTTCTTTTCC
CACCTTAGCATTTAGTTTTTAGAAAATTGATTGTCATATGAAGATATCATGCTTTTCAGTAAACAGCAGCCATGACAC
TGGTGAAAATTAGAAAGTTCTTCCCCTCGATATGTTTTCACGTTTGCTTCTCCTAGTGCTTCCCTACTTTCGGCCCTC
TCTCTACCGTCCCCTCTCCCTGGGCTCTCCACAGGCACTCCATGAACACACTCCATTCTCCATATATCTTCCTCCGTT
AAATAAACACCATCGTTCCTATTGTCTAAACTTTAATAGAGAACAAGAAAAGGATGGAAAAACAAATCTGGCGATGAA
GTATAATGTCACGCCAAAAAGAGATGCGAAGAACATGAATGCATTTCAATTAAACAAATAATTTCTTATTAACTTATT
GTTACTAAACCCTTGGCACACACTGTGCCAATTGGTTTTTTTATTGGAAAATACTTTCCCCTTACCAGGTAAGTATGA
GCTCTTACATTCCTGCCAATAGTAGTATGATGTGTGCAAAAGTTTTTCTTTTATGTTTTTGATGAATTATTTTTGCAT
ATGTGTCAAAATGTGATTCGCAAGAAGGAAGAGTATCTCCTTACTAGTAAGGAGGCAAGTAGTATCATTTTTTATTTA
AGAATTAAGAAAGAGAATATAACAACAACAACAACAATATAACATCGTGTTGCATGAAAATAGGACCCATGTTCTTAT
TTTGGTTTTTATTTGAACTTTTTTAAATATGAAAAAATATTAATTTGCTATATTATCCCTATTTAATGAAAAGTTTCA
ATAGTTAATAAATCAATAACTAAGGGAAATTTTTAGTATTTTGAATGTTTTATTCTCTACTTTTTGCTTATGTATGTA
GATAAATTCGTTAATTAAGGGCAATTTTTGGTATTTTGAATGTTTTATTCTCTGCCTTTTGCTTGTACGCTTGAGCAT
ATGTGCCAATTGGTTTTTTAAATTTTATTTTAGAATTAAAAAAGATAATGGGTAAGTGTTCCACAAAAATAGGACCTA
TTATTTGATTTTGTTTTAAATTTTAAATTTTGTAATATGAAAAAGTGTGAATGTACCATATTATCCTCATTTAATTAA
TAATTTCAATTCTTAATGTTTATATTAACCAATGTCATTTTCTGATATTTTGAATGTTTCACCGTTCTCTACTTTTTG
CTTCATATATATAAATATAGATAAATTCAGTAACTAAGGGCAAATTTTGGTATTTTGAATATTTTACCACTCTCTGTA
TTTTGCTTCATATATATAGATATAGATAAATTCATTAATTACGGTCAAATTTTGGTATTTTGAATGTTTTACCAATCT
TTGCCTTTTGAATATATATAGATGAACTAAAATCCAAGAAAGAAAACTTAAGTATATATCTAAATAGTGTACATCAAA
ATTAAATTCTGTATAATACTCAGGTTTAATGAAGAAAAAAAATCTTACCCGAGTCTTTACTTTTTCTCATGATATGTA
TATGTTGATTCGATGTCTCAGTATCCTGAAATGCGATCCGATCTGAAGATATCTTGGCCAGACGTGGAAAGTGGCAAT
GATACAAAATTTTGGGAAGACGAATGGAACAAACACGGTACATGTTCTGAACAGACACTTAATCAATTCCAGTACTTT
GAGCGATCCCACGAAATGTGGATGTCGTACAATATTACAGAGATCCTTAAAAACGCTTCAATCGTACCACATCCGGCA
AAAACATGGACCTATTCGGACATAGTATCACCCATCAAAGCAGCAACTGGAAGAACACCGCTTCTTCGTTGCAAATAC
GATAACAACACTCAGTTGTTACATGAAGTGGTATTTTGTTATGGCTATAAAGCAATAAAGCAGATTGACTGTAATCGG
CCAGGATGCAAAAATAAAATTGACATCAAGTTTCAATAAAATAATAGCTAGCTTTCTAAAATCGTAATAAAGGAGTGT
GGTTTAGTATGGTACTAGTGTAATAAAAAACAAAGTGTATGAATGTTTATTTTTATTTTTTTGATGCGGAATGAATGT
TTATTTACGTTTTGGGAAGTCCAACTTTTATTTATTTTAATTTTTCTGGTAAATTATAACTTTTTTATATTTGTAGAT
TTTTTTAATCTTTCGTAAATATTTTTATTTTGCGAAAAAGAAAAAAAGTTTTGGTTACTTTAAAGAAATTTTGGGATT
GCATTCATAATTCAACCAAAAATTCTTATGGGGCTCCTCAACTAACGATCACGCATGATCAAGCAACTCTAGCATATG
CATTCAAATTAAGAGTGCAATAAACTCATAACAAAATATATATATATATAAAACTTGAAAAAAAATCAAGCCATAACA
ATACAAATAAAACTTTCACAAAGGAGATGTGGAAAACTCTCACAAAAGAAAGGTGAAATTTTTTACAAAATGAGAGGT
GAAAACTATATAGAAAAGCCAAAGAGTCTCTACAACTTATTCCAAATATGAAGAAACCGCAAAAAGAATGATGGTAGA
GATTCGACACTGAAACGAAAGTGAAGATTCGACACTGAAACGCAAGTGAGATCCGACACCGTGAAGCATTTGCATGTG
ATGAGTGGAGGAAAATCTTTACAAAACGAAAACAAATATGAGAAACCTTCTGTCTCTAAAAATGGGGGGAAATGGGAG
AAGGGAGAAATGAAGAAAGGGAGAAGGGAGAAAGAACAGTAGCTTCGAGAAAGGGAGAGGGGAAGAAGAACAATGGCT
TCCTCCCCCTCAAATGAAAACGGATGTAGAATGTTTTTGGGGAATGAGGGGACTAGGTATGGTAGTGGTTTGATGGGG
GCTTGTTTTTGTTTTTTTTGAAGTCTTATGGTGCTGACAATAAAGCCCTTACATTCATGCAACACGTGCATTCAAACT
GACGAAATTGAGACATCGGACTTAATTTGTTAACGACTGAAAATGCGGTGACGAAATCAGAATCACAGTAACCAAAAT
CGTTTTTTATCTTCACTCCAATGACCAAAAGTGTTTTTTCCCCTTTTCTTTCTAAACACAGCGAAAGTGGTCTTTAGT
CGCCAACATTTTCCTCACGCTCACTCAGGATCAAATTTTTCTTCCGTTCTTAGATAAAAAATAAAAAAATTATTCCGT
TTGATTTCTTTTGTGCCAAATAAGAACAAGCTTTGCTCGAAGCTAAATGAGCCCTGTAAGAGAAGTTGTGCGAGAACA
AAAAGTCTCCACAAATATCTACAAGTGCAGTGTTGTGTAAGACATAAGAAAATAATAAATTTTCTCCAAAACTTTGAA
ATAGAAGCAGCACGTACTCAGAGAAAATCCTTTGTAATTTATTTTCAGTTTTACTTCTCCTTCGATTTTGTTTTGTGT
TTGTACATTTGAGTTCTAGGCTTAATCAAATTCTAACACAGAGGAGGTCGAGGAGGACCAAAACAAACAACCAAAGAC
ATGAAATCGAAATTACAAAAGGCGCGAAACAAAAAACATGGAATGTTTTTCTCTTAAATCTCCCTTCAATAATTACCC
TTACAAAAGAAACCGAATAAAAACAGAGTTTAAATCTGTTTAATAATTATTGAGTAAAACCAAACTTTCTATGTAAGT
AAATGAAAACAAGAAATCGATTTCGCCATATGTCATGATGGCCAACTTAATTCCTGTTTCAAGAACTTGCTTGGATTC
GTAATTACACAAACATAGATCTGCTGCGCCCTTATTGAAATCTTTTTTTTGCAATAAGAGCTCATTATCTATACTAGT
CCCAATTGTACGGCAATATTTCCAAGGAATAATAAAAGGACACAATTGTTTCCATCGTTTTTCTTGCAGAACCCACAA
GTCAACTTTTCGCATGCCCTCCTCCTCACAACCATAAAATCTGAAAAGCAAGCAAATTTGGTCCTTGTAAGCGTCGAT
ACACAACCCCCGTGAATTGCAAATGGCATCTGGTGCAATGAATTCTTCGAACTCTTCACTGCCTGAATCGAAGGACAT
AATGCTGAATAAGGGACCTTTCTCAATGATGTGGTATGCCGCTCCATTAAAAAATGTACCCGTATGATGCTGCCAAGT
GCATTTTAACCAAGGAGGAATTGTTTCAATCATCTTCCAAGAGTCTGTTCTAAGACTATAAACCTCAACCGCGAAGGT
ATCTTTGTTGGAACGCATCATTCTTACAGCCTTGTAGTCATTAACCCCCGAGTGGAAGCCGAATTGGAGAGCAACGTA
GACAAATTTAATGTTGTTGGGGCTTATTGGAGGGGTCCTAAATTTCCTAACCGATGGGTTCCATATGTGTATAGGACT
ATCATAATTCAATATCTCGTCCGAAATGCAAACTAGACCATTGCTTGAACCATATATCCCATAATGTTCTGTGCTTCC
TAAGGGATTGCTTAACTTAGAGAACTGCTCAAATGTTTCATTTGAAAAAAGTGACCATAGAAGTTCTTCTTCAACAAA
TGGGTCATCGTTGTCATTTTGACGTTCAAAAGTTGGGTGGTGGAGGCAAAGTAGATAGACGTGGGCATGTTTAGTGAC
ATTCCTATTAATGTGTGTGCTGACAAAACTGGACCTGCCAATCAAATCACTCCATGACTTGCATGTACAAAGAAACCG
AACCAGGGATTTTGCAGTTAGTCTTGCTAGGATGTCGATCAAGATTTCTTTCTTACCTAATTTGAATGTCATCCTGTA
GAAAATCATATAAGTTAATAAGTATGGATCATAACAAAACAAAGTGCTTTCCAATTTTTGCAGAAAGTCCTATGACTC
ACTTTTGCGGTTGGTAATGGCAAAGGGAATGAGCTTTCCAACATAATTTAATGACTATTTGTGTGCGTCAAACAACAA
AATATAGATAACCTCCAAGAAAAAGGGTAAAAAAGGAAGAATTGAATTTCAGGCCAGCTTCTCAGGAGTAAAAAATGA
CTATAATAGATCCTGGCTGAACGTTATTGAATGGATGATATACAGTGACCAAGTAATTTGAAGTCCTAGAATAAAGCA
CCACCACATGATCATGACAAGAAGAAATTCATGGTCAAGTGTGGTGTGCGGTTTAGGGTTTGGCGTCCAATGACTCAT
AACTTCTGCATTGATCCAGTGTGGTGTGGGGTTTGGATATGATCTCAAATATCACTACTAAAAAACTGGGCTAAAAGC
ACAAATTCCATTTGTGCTCTTTTGCATTTGTGCTCTTTTATGTCAAATAGCACGAATAATTGTGCCCTATGATGAAGG
CCACAGTGCAGCCACTTTAAAGTAGTCGGTGTACTATATAGCAGTTTCCATTGACTATAGAGCATGAATGTTTTACTT
TGTCGCAGGCATTTAGAGCACGAATGCCAAGTACTTGTGCTTTGCCCAGTGACTAGACAAATTTGACAGATGTGAACT
AAGCACAGTTTTAAAATTGTGCTCAATAGGTATATATGTCTTATAAAAAAAATATAAACACAATTTGAAAAACGTGCT
CAATGCCAATTGTTTAAATTTAAAAAAAAAAAAAATTACACACTGAAATTTCATTTCCACTTAATATAGTATGGTATT
TCAGACCTTTTCAAAAAATATATATATATTAAATAACAAACTGAAATTTCATTTCCAATTAATATAGTGATTAGATAC
AATAATTGAATAAAAAACTTGTACTTAAAACTGAACGTATCTAACATCAATGACTTAGAAGCTCCAAATAAAACACCC
TTTATGAGCCTGTCTGCCTTTGTGAGCCTCCTTAATCACATTATCTGCCAAATAAGAGCATCGGCATTAGAGAGAGGA
CAGGGAGAGAATCTACCACAATAGATAACCAGCTAGTAATCATAAACTCTTCAAGTTTAGGGTACTTAGGAAACCAAA
AGAGATGCATTAATTTTATGAAGACATTAAAGCTTAACTATGATGTTTAAGTTTCCTGGACATGTGTGTGCATCTATC
AAAATGGACTCGGAGAAAAAAAAAAAATATATATATATATATATATATCAGGAAAAAACAAAATAAATGACATATCCT
CAACCAATGGCATCTCATATCGTGCACATATACATTACCAAATATAATTAGCTGCTCTTTTTGGCTGAAATTAGTGCA
GAGAAAATTTGAACTCAATTGTGCACAATATATGACTCCAAACAATCTCTTTTCCTCAGAGCCAATTTTATTAGCTTC
AAAATTAATATGAAATCATAACTATTACAGTGGAACATATTAATACATCCACTTGGAGGTTAAAATAGAAACATAATA
ATAGCAAGAGAGCCAACAATAGCATGTTATAATCATTCTTGACCAAACAAATGCATGAAGAAAAATTGAAATAAGAGC
ACAAATGCTTTGTCTTTGAGCTTTGAAGCAAAGTACTTTAACCAAAATGACATTTAAATGCTCAATGATAAATATGGA
AAACGTGTTAAAATTAATACTTCAATGTAGAAGAGAGAGAGGAAGAATAATATGTCATCCTCCTCTTCCAAATGAAAC
CAGCCGAGAGCTAAAAGAGAGAGGGATAATCCTCCTTCAATATTTCAGCAATACTATCAAGTTCCAACAAAACCAATG
GCTACATACTTCATGGTCTACATTGGATTCAATGTAAATGACAGTACCATTTCTTGGCCTCTTGAAGTAAATGACAGC
AGCATTTTGGTGATCAAATTATATTAAACGACGGAACTAAACCAAATCTAACTACACAATTTATACTTCTCTATTATC
AAATTCTCAAAACTTTAACTCTTGGCTTTCGAATTCTACATGGATATTTGTAATCTTAAATGTACAATGATTCTTGAC
AGTTGATGTCAATCTTAAACCTTCCGCCAATTGGAGACCCACTCCCTAACATAACAAACTTAAAAAAGGGAGGCCATG
GTAATGAATTTTAAGTACCTATGATGAAAAGAAGAAAGGTAATGCCTTATCACTACAAATCTGGCAGCATCTAATTCC
TCCATGTTCATCAAAATGTTACAAACTAGTAACTGAGGCTGTTAATTATATGTCGCACATCTATCCTGTAGCTACATA
AAATTTACAATTCTATCTACCCTGTACCTACATGATTATTGCTACAAGAACTGCACTTCAGATGTAAAACATCCAAGA
GAATAACAGATGGCAAATATTTCCCTCGTGAGAACATGGGTGACAAAAATGTAATTAATTACATATCATAGGGAAAAA
GAAACATTTAAGATAAAAATCCTATCTTCAAGCACGCAGACATTAAAGCAGAGAAAAGTTATCAGTCATATCATCTTA
TCAGATCCTAACCTAGTAGGACCAAACAAAACCAAAGCTTGAAACAAGAAGAAGCAAGCAACACACAGAGATTGAGAC
AGAGGAACATTTATACCTTCAATTTCGCCTATTAATCGAAACCCACAGAGACTATGCATAACAACTGCAAAATTAAGA
AAATTTTGATTTAATTTCAACAGAATACAAAAATGTCGAAACCCTAATAATCTACTAAATTGGGGAACATGAAAACAA
CTACGAATTCAAACCAAATACATACAAATTTACCTTACAATGAACCAGAGCCCTCCACAATTTGCAAGGATTCTCTCC
AAAAACCAATGAAAGTGGATGATGTTTGGTTAGGTTTGGAGAGGAAGAACAAGTCTCTGGACTCTAAGTGACTTACAG
AAGTGACTAAGAGTGAGAGAAAGCGAGCGCGATAGAGACGAGTCGAAAGAGAGAGACTCTGAGAGGGTTAGGTTACTG
AGGGGTGATCTGGGTTAGGTCGACTAAAGAGTGGGAGAGAGAGGATGAGGTTGACAGACAGAGACATGAGATCGAGAG
AAGAGATGATACCAGATGAGAGAGTGAGATAGATGAAGCGACGCCGACGCTGTCAGCGACTAAGGTCGGGAGAGACGA
ATCGATAGAGAGAGGAGCTGAGGTCGGGAGAGAGAGACAGGCGGCGAGTGAGATGAAGATTAGAAGAGAGAGAGAGAG
AGGTGCGTGACTCGTGTGAGCGACGAGAGCTTTAGGGGGGTGTATCCAATTCTAACTTTTAAAGACTTTTTTTGAGTG
AATGACTTTTCTAAAGTTGACAAATTCTTAATGACTTTTACATACTTTATAAAGTTAAGTGACAAACTTTCATATACT
TTTGTTATAGAGTTTTATAGACTTTTAAATACTTATTTTTATATTTATTTTACAAATAGCATTTATCTTTTATGTTGA
TTGAACTAGTCGGCATACATTGAACAAAAAATTAAGAAAAAAAACAATTGGATACAATTACATAAAAGCAAAGAATAG
TTCTCCTTAACATTAGAAAATGATAAAAATGACAAAGTACATTTGAAAATGTACCATAAGGAAATAATTGGCGCTCAA
CTAGCCATGATTCAGTTTACAAAAAGGCTTAGCCATGATTCATTTCAATGACGGTGGATAAACCATAATACAAATTCC
TTTTGAAAATTCCAATGCTCATTACCGTTGAGTTCCGTTATTATCTTGCATGGCATTTCTCCACATGTCAGAAGCTAT
ACCAACTCTCCATTCATTAGCATTCTCTCGTTGTTGTTCTTGAGTTTCAAAAACTTGTTCCACATTATCTCCTTCATT
CCCTGGTAATGGTGAAGATGATGAAGACTCGTTCTCTAGTTCAATAGGAAATTCATCAGAACGACATTCCCTACGAAG
AAAATTATGTAGCCCTGCACAAGCTAACACAAGCTCTGCTTGAGTCCTATATAGGAATGGAGGTGCTGACTTGAAAAT
TGTGAATCTTGATTTATATATCCCAAATATCCTCTCAATTACATTCCTCAAGGAAGCATGGCGAAGATTGAAAAACTC
AGTTGCGTTTTCGGGGTCACGACCTTGACAGCAAAATCTTGGAGATGATATCGTACACCTCGAAATGGAGCTAAAAAT
TGACGTCGATTTGGAAATCCACAATCCACTAAGAAATATTTACCTAATCATAAAATATATATAAAATTTGTATGCAAA
GCATGATATAATGAATGATAATAATAAAACAAAGAGATAAGAGTGTACCTTGTGGTACCTTGAGTCCATTTCTCCTTG
ATAAAGCATCATTTAACACTTTTGAATCATGAGCTGAACCTTCCCATCCACTGAGCACGTATATGAACTCCAAATCAA
AGTTACATGCTGCTAATACATTTTGTGATATCTTTCCATGACGATTGCGGTAGTGCTTACATCACGTCCTTTTACCAT
GGCTGGAATATGTGTACCATCAATAGCTCCAATGCAATCCTGAAATGAATTGATAAGAAATTATAAGTAAAACATAGT
TTTGTTGGAATAATAACAATAATACTTATAATAATAAATTCCATTACCTTAAAGTAGGGGTAAAATCGTGTACTTTCT
CTTATCTTAGCTGGCACTGCAGATCGAGGTTTAGCCAACTTTTAAATAATACTATATCACACGTACAAATCCTTATTA
ATTGTGTATATTTTCATAATAGCTTATTGGTAAACTGCATCCAATGCACCTTTTAAATTTTTATTTATCAAATATAAT
CACATAGACAAGTAACATATTCTTATCAAAATAAATAAATATTACTCAGTCATCAATAATATTTCATAAACACTCACA
AATCAACAGAAATGGTTAGATTACAAAAGAGTCTATATTCCAGCAATTCTCCTAACCTAATATGTGGGATGTAAATAT
TATATGAAAAAATTATCCACCTAACGAATTATGGGTAAAGAAACAGTACCTAAAGAATAAATTAATGGGTTTAGGGGC
AACAAATTATATAATAAAATATTATAAGAAAACATAGCATATGAGACAATCAATATAATAAAATATTTATATGCAAAC
ACAGCTTTTTTTACTAATAGAAGAAATATTCATCAATAATAAACGTGTGGATGAGAAGAGAAGAAAAATATTCAATAT
TTTTTTACTAACCTGAAGGAAGTGGATGACAATGGAATACCAAAGTGGAGCCCTAACCATGAAGAAAAAAGATCTATT
TGCTTGATGCTTGATATAACAAGGGAAGAAAGAATTGGAGACGTTTGGAGACTTTTTGGTTCTATCTTCTCAGCTTCC
CAATATTTTCATAAAGTCTGGTGTAAATTAGCAAGACTTTTGGTAGTAAGAATTACCTTTAAAAGTATTGAAAAGTCA
TTTATTTAACAAAGTTTTTAAAAGTCATTAATATTTGGATACCTCAAAACTTTTAAATACTCTTTAAAACTCACAATT
GAATACAACTAAACTTTTAAAGACTATTTAAAAGTCACAATTGAATACCTTCAGACTTTTAAACTCATTAAAAGTCAT
TAAAAGTTATAATTGGATACACCCCCCTTAGGCACGGTTATTAGTTTTCCGCGTCTTATTATCCAATTGAATTTTTAT
TTTTAAATATTGAGCACAAATTGCAGTACTCGTGCTCTATATAAGAGCGATTCCACCGGAAGGGCCCAGCCCGAGGCG
AGGGGAAAAAAACAAAAAAATTTCGTTCCACCGCTAGCCCAAGCCTGGGGGGTGTGGGACCCATCAACTCGGGCCAAT
CCGAAGGCGAGACGAGTCCGAGTTCCAGCCCGCGGTCGCTGACGTCAGCTAGCGTGTTTCAAATTTTCGCCTCCCCAG
CCCTCCGATCAGCATCTCTGCATCCATCCTACGGCTGAGGCTTTTTTGGGCCAAAAAAATATGAAAAAAAATCGTAAA
TTTTTTTTTAAAATTCTAAAAAATTCTGATTTTTTTTCTTCTATAAATACTTATCAATACCCTTCACTTTCAACACCA
ATTCTCATACATTTCATTATACTTATACTATTATTAACTATTTACTCAACATTTTCATCTTTTTCATCTAGTATTTTG
ATTTCATATTTTTATGACTTCTTCTATCGAAACCGGAGGGGCTTGGAGCACCATGGAAGATCTTTCCTTGTCCTGTGT
CCGGCAATGAGATGAAATTTTTTCATATGTGGAAAAAAATTCATGCCGAATTTTGTGAAAAAATTCCAGGGTCTACTC
GTACGGAGATGACATTATCCAGTAGGTGGAAAATTCTCAATAAAGAGTTGGGAAAATGGAGAGCTGCCTTAGCAAAAG
CGATGGACAACTATAGAAGCGGGGAAAATCGTACTAACGAGGTAAGTATTTTATAATTTTTGTTTTATTAAGTTTAAT
CTCCTAATATATATATTTTGTTAATATTTCTTGCATTTTAAATATTTTGTTCATATTTCTTGCATTATCAATATTTTG
TTAATATTTCTTGCAATTTAAATATTTTGTTCATATTTCTTGCATTTTCAATATTTTGTTAATATTTCTTGCATTTTC
AATATTGACAGGACCCGATCCCAATTCCACTTTGGAATTCGAACCAAGTCCTGTGCGTGTCCGACACCTGGCAACTGT
CGGGCACAAATGACCATTTTACCCTTCCTGCTACAGTTACTATTAAAACTTTCTTTGGACTCCTGCCGAAAATTCGGC
AGAGTCTCCCCTGTATTTTGACCAAACGCAAAATCTTCCACCTGTTAAACAAGCAAATAAATTCACCCAACTGCCAGA
ATACATCCAAACAACCATTCACCAGTTCAGGTTTCTCACTAAAACTATATATCAGAGCATTTTCTAAAGTTTACAGGG
TTTCAAGGACTTTTCTACAAAACTCTATGTTACTTGGTGGCGCGGAAGCTAGGAATGGCCCGGTGGTGGAATCCAGCA
CACTTCTACAGCCTGGGGGCGAAAAACAAGTTTGAAAATGTGAGTGGACAAAAATAATGTTCTTGAAAACAATTTATA
ATCATAATAAACCCCGTAATCAAATAATATGTATGTAAACCTAAAGTTCATCCGTATTCAAATATAAAGCATTAAAAT
TAACATGTATAGGTATATGTATGTAAACAGATATGAAACGGTACGAATACCAAGAAAACTGATATAAGATTTTTGAAA
GCAATAATTTTATAGAAGCACATAAATTCCTTTAAAACTACCACCTAAGTGTACCCCTGTCAATCCGTCAATTCCCCT
GCAGGTCTCGGGCGACACGCAGTCCATCCAAGCCGCAAACTGGCAGGATACAGGGGACTATGGTCAGCCTGATCCGCC
GGCAGGTCTCGATGACACCAAGTCAACTCGAGCCGCTTTGGCAGAATACAGGGGACCGTAGTCAGCCTGATCCGCAAT
CCTGGCAGGTCTCGGGGACACAGTCAGCCGAGCCGCAAATCCTGGCAGGTCTCGGGACACCAAGTCTGTCGAGCCGCA
AATCTTGGCACTCACGGTCCGAGCGTCCCCGAAACTAGTGAGGCAATGTCAAGTGCACTGACAGAACTGTAAACAGAC
TAGATGTCCGTAGACATCGGTCCATCTGAGGGTAATCACCAAATAAAAAAGTGGGTACATGGTGGTCTTAACTAATTT
ACTCTCGAAAAGTCTGATAAATAACTGTAATCTCAATTCTGCTGCTATTTCTGTTATATAAAGCTCAAGGTCTGCTGT
TCATATAACTTCAATCATATATATAACTCAAAATATTTAACCGTAATAAACATGCTCGAAAAACATGCAAGAATACTT
ATTCAAGATCAAATAATGAAATTCACTCATATAAACTCATTTATAAAAACTTATTTATATAAAATCAAGATAAACTCA
TTTGTATAAATCATTTATATAAAATCATTTGTGAAAGAAAATCCACTCACCGCTGGTCCGAGCTAGCTGGACCTCTTG
AAGGTCCCTCCTGTGGTTCTGTCGGGCCTCTGGTGCCTGATTACCCATAAAGATTAAATTAATAAAACTGCTCAACAA
CAGAATTAAATTAAACACCCTGCCCCCAGCTCCTAGAAATGCGTGTACACATTTAAAAATCACTCCTATGCTCACTTT
AGCCTTTCAGACAAATAGAACGGCCTTAGGAGACCCGAAACTTTACTAAGTGATAAACTGCCAGACCGGCCGATCCGG
AACCCCGTGGGGTCCACGATCTCCGATGGCCAATCTGGGATTCTCTAAAGGTTTCTCACGAAGAAAGAACTGTAATAA
CCCAAAACAAAATATCAAGAAAATAACAAAATATCTATAAAAGTAGGATTAATATCTTCTAGCAAAAAGACAATTTTA
CTCTCGCATTATTTAATAGGGAAAAAGTTGACTTTTTGATCGAGAAAGAATTTGGCAATTCCGCTTGCACCCTTGCGT
AGAACACGGTGAAACGAGCCCGTAGACAAGGAGTAGGCTCGAATCGGAGTTGTAACGAAGAAGATACGATCAAAATAC
CGTGAAGGGCAAAATGGTAATTTGGTCAAAAAGTCAGATTTTTATCCCTTTTCTCCTTCTCTCTCCTCATTTCTCTCT
CCTCACTCTCTCTCCTCCCGATTCGCCCTAGCCCGCGACCTCTCCTCCTTCTCGACATCGCCGCGGCCGACACAGGTG
GAGCCGATCTCCGAGACCGGTGCCAAACGAACCACCACTCGACCGCCATCATTTCCTGACCCGTCGCCGCCGTTACCG
TGGCCGGAGTTCGCCGGAAATCGCCATTTTTGTCGATTTTCCAGTTTGAACTTTGAGCTCCTCATTCTCCCTCAATTC
TCTACCAAATTGATCGAGTAAGGTATGGTTTCTCAGCTATTTTTTCGTGTTCTAGCTGATGGATGTATGGGTTTCGAT
CGATTTTGGCTCTAGAACGTTCGATTTTTGACTTGAAAATTGGCCGAAACTTCGGCCGCCATAATCGGCCATTTCCGG
TCACTTTTTGGGGTATGTCCAAGAACAAAAGTGACTCCAAATGGGGTGTTTTACCTAGGATAGGAGTTTGGAGTCTTG
GTTTTGAGATTTTTCGGCAACCCAAAATCGCTTTGGACACCCAATCTGCCCGCGCATGTGGCAGCGCGTGGGAGAGGG
TGGTGAAGTGACTCTGTGCAGTTTTGTGATCCTCGTATCGTCACGAGCGCGTAGGATTTCGCGGATCTCGATTCAGAG
TCCGTTTGAGCCCCGAACGGATTTGGCATATCGCGCGATCCTTGGGTGCAGTGTCGTCGAATAGTTGGATCGCACTCA
ATTTTGGATATGTCGTACTACATGATTTCAGGATCGTGTAGGATTCGACGGATTGCGAATCGGAGTCCCGGATACTCC
GATATCGTGAACCCTGGGGCTAGGGTTTGGATTTTAAGCGATAACGCGATTTTGGCCAATCCGACCATCCGTTTCGGA
CCAAACTCGCGGAACATGGTTCCTTCTCTATGAGGAACCTTCAGAGAAGCCCAGATTGTCCATCGGAGACCGTGACCC
ACGGGGTCCTGGATCGACCGAACTGGTGGTTTATCGCTTAGCTAAGCGTCGGGTCTTCCACGATCGTTTTAGCTGTTT
GAAAGACTAATGTGGGCATAGGAGTAACATTAAAACGAGTGCACGTATTAATGTGGTTATTACAAATATGTTGTTAAT
ATTTCTTGCATTTCCACGTGTTTCTTAATTTTCTTGCACTTCTAATTTATTTGTAAGGTTAATTGCATTTCCATTATT
TTTTTTTAATTATTTCTTGCATATCCAATATATTTTATGACAGGACCCGACCCAATTTCCACTTTGGAATTCGAGCCA
AGTCCTGTGCGTGTCCGACACCTGACAAATGTCGGGCACAAATGACCTTCTTACCCTTCTGACTTCAATTTCTCTTTA
AATTTCCTTAGATTTCTGCCGAAAATTCGGCAGAACCTCCCCTGTATTTTTGATTTATCCCAAAATTTTCACCTGTCA
AATAATCTCAGAAACCCTACCAACAGCCAGACTAAGTCAACAAACAGATTCCAACCTCAATTCCTTATGTTCAACATG
ATATCAGAGCATTTTCTAGGGTTTTCAAGGTTGCAAGGATCTTCTGCAAAACTTTACCTTGGCGCAGAAACTATGATT
GGCCCGGTGGTGGATCCCGCGTACTTCTACGGCCTGGGGGCGAAAAACAGGTTGAAAATGTGAGTGGACCAAAGCAAC
AATAATGTTCTTCAAAACAATTCTCATAAACATAATATCCCCCATGGTAAAATAAATTTAGCTAAATAAAACTGAATA
CTTACTTATTATATCACGCGTAGTCAATTCAAGGCATTCTATATCAGTCATATTCAAACTTGAAAGTTTCATACAAAC
CACTGAATTCAAAGCTTTCATAAAAGTACTGAAATCCAACGCGTATAAAAACTCTGTACTCAGATCTTTCATAACTGA
ACGAATATAAAGGTATCTATACTTGAAAAATCAGAAAAACTGACTTAAAATAACTGAAAACCATAGTTAAATAAAAGA
AACTCAAAATCCTTTGAAATACCACCAGTTTGTACCCCTGTCATTTCCGTCAATTCCCTGGCAGGTCTCGGGCGTCAC
ACAGGCTACCCGAGCCGCAAACTGGCGAAATCAGGGGGCTATGATCAGCCTGTCCCGCCGGCAGATTCCTCGGTGACA
CCAAGTCAGCTCGAGTCGCTCTGGCAGGATGCAGGGGACCGTAGTCAGCCTGATCCGCAATCCTGGCAGGTCTCGGGG
ACACAGAGTCAGCCGAGCCGCAATCCTGGCAGGTCTCGGGATACCAAATCGGCCGAGCCGCAAATCCTGGCACTCACG
GTCCGAGCGTCCCCGGAACTCGTGAGGCAAGTCAAGTGCACTGACTGAACTATAATCAGACTGGATGTCCGTAGACAT
CGGTCCGACTCTGGGTAATCACCATAAAGAAAAACGGGTACGAGGTGGTTTAAAAATAAAGTCCTTTAGAAAAATCTG
AATCACAACTGAAAAACTCAAGTCGTGCTGCGGTCTCAACTGATTCAAAACTCAAACTCTGTTTCTGTAACTGGTAAA
TAAGCAGCACCGACTTATAGAATTATTACTGTACTGATCATATTCAAAATCGTATTAAAACTTACTCAAAGACTGAAT
GAAGAAACTTACTCAAATAAACTCATTTATAAAACTCATTTATATAAAATCATTTATAAAATCTATTTTATATAAAAG
CACATCAATTCATATAAAAGCACATCAATTCATTTATGAAATCTGAATTATAAAAGAAGGTCCACTCACAGATGGTCC
GAGCTACTTCGATCCCTCGGAGGTCTCCTTTTAAAATTCTGTCGGGCTCCTGATACCTGATTACCCCGAAAAATTAAA
TTAATAAACTGCTGAATAAAACGAAATTCAACTAAACATCCTGCCCCCGGCTCCTAGAAATACAAAACTTATTCCAGT
TATTCCTATGCCCGCCTCAGCTTTTTAATTAGTTAGGCTAGCCTCAAGAGACCCAGAACCTTGATAAGCGATGAGCTG
CCCGATCGGCCGATCCGGGACCCCATGGGTCCACGGTCTCTAATGGCCAATCTGAGCTTCCCAGAGGGTTTCTCATGG
GGCGGGAACCAAGTTCTGCGAAATTGGTCCGAATCGGACGGTCGGATTGGCCAAAATCGCATTATCGCTTAAAACCCT
AACCCTAGCCCCAGGGTTCGCGATTCCGGAGTATCCGGGACTCCGATTCGCAATCCGTCGAATCCTACGCGATCCTGA
AATCACGTAGACCGACATATCCAAAATTCAGCGCGATCCAACAACTACACGATACTGTACCCACGGATCGCGCGATAT
GGAAAATCCGTTCGGGGCTCAAACGGACTCCGAATCGAGATCCGCGAAATCTCACGCGCTCGTGGCGACACGAGGACC
TCAAAACTGGCCAGAGCCGTACCACCACCCTGGCCCACGCGCCGCCTCACGCGCAGGGCAGATCGGGTGTCTAAAGCG
ATTCGGGTGTGCCGAAAAATCGTGGAACCGAGACTCCAAACTCCTACCCTAGGTAAAACACCCCATTTGGAGTCCCTT
TTGTTCTTGGACTACCCCCAAAAAGTGACTGGAAATGCTAGTTTCGAGCGGCCAAAGTTTCGGCCAAACTTCAAGTCG
AAAATCGAGTGATCTAGAGATCGAATTGATCTAAACCCAGCCAACCAGCAGATAGAGCACGAAAAATAGATGAAAATC
CATACCTCACTCGACTGATTTGGTTGAGAAATGGAGGAGATCGAGCGGCTGGAAGTTCGGATGGCATTCGGACGAACC
GTCGACTTCCATGGCAGATTCCGGCCGATTCCGACCACGGCAGCGGCGGAGGTGGGTAAGGAAACGTCGGCCGTCGTG
TGCTGGTTTGTTTGGCACCGGTCTCGGAGATCAACTCCAAGCGAGGCGGCCGGTGCGACGTCGGGAAGGGAGGAAGGT
CGCGGGCGAGGGCAGCTGCGGGAGGAGAGAGAGAGCTGACGGGGGAGAGGAGAGAGAGTGATATAAATATCTGACTTT
TTGACCAAATTACCATTTTGCCCCTCGCGGTTTTTAGACCATAACTTCTTCGTTACGGCTCCGATTCGGGTCTACTCC
GTGTCTACGAACTCCTTTCGCCGCGCTCTACGCAATGGCGTAGGCGAAATTTCCAAATTCTTTCCCGATTAAAAAGCC
AAATTTTCCCCCATTAAAATATGCGAGGGCAATTTGGTCATTTCGCTAAAAGATATTTTCCTTACCTTTTTAGATATT
TTCTTTCTTTTTGATATTTTGTTTTGGGTTCTTACATTTTAAATATTTATTGCATTTCCATTTTTTTGTTAAATAGAT
TATTCAAGCACAAATGTGGTTCGGTGCAACCGGGGGTGGCAAAAAAAATTTCAACCATCATGAATGTTGGGAGGTGGT
GAAATATTGCAAACGCTTCATAATTATTCCAACGGGTCCAGAGGTTGTGTTAAACGAGACGCCACTCCGTGATTTAAT
GACATCGGATTCACCTCTCGATTCTCCTATGAGTCAAGACTCACCCATCGAAAAGGAGCCGAGGCCCATTGGCCGAAA
GGCCGCGAAGGCAAAGAAAGCGGGTAAATCAAGCAATCATAATTCACAATTTTTGAAGGAAATTGCAAGGCAAAACGG
CATAAGAATAGAAATGGAGCAAAAAGGCCAAGATAACGAGTTGGCCCTTCAAGCTGAGTATGCACGAGAAAGGGAGTA
TTTGCGCAAAAAAGATATGGACAAGACGGATCGGGAAACCATGGCGATGGATACAAGTCATATGTCCCCTAAAACAAA
ACAATTTTGGAAGCTAGAACGAAGGGATGTTATGAGAAGAAGACTTTTCCGGGATGATGGGCCTAGCAACACGGATTG
GTTAAATGATGGAAACCATTAAATTAGTTAGCATACCTTTTATGTATTTGTATTTTTCATGTTTTCTATTAAAGTTGT
TGTAATTCATGTATTTTATTTTAGTAGTAGTAATTCGTAATGACTTGTATTACATTTCGTTATTTAATAAACAAAGCA
TTCAATAAATTACCTTTTTATTCAACATATTCCATACTTCAAACAAAACATAAAAAAATAAAAAAAAGTACAAACAAG
GCACAATAATAATAACCAACCATAACCAAACCATAATAAACAAAACATAACCAAAGCATCTATGCTCCATCATTCATC
TTCATTGCCTTTCACCGCCCACAGATGCTCCATCAAGTGAACTTGACGCATTTCATGGATATACGAAGATTGCATCTC
TGTATATCGATCTATCATTCGGGTCATCAAATGATCATCCCTCACCAATGGTTCCGGCTCAAACGGTTCTCCACTTGG
CCCCATGGGCCTTTCATAAATCCGTGTCAAGGCCATGTTCATTGGATCTGGTTCGTAGACCTCTAAAGCATCATAATC
GTACTCATCCTCCACAATCATATTATGGAGGATGATGCAAGTCATCATAATACTTCTGAGGATCTCCTCATCAAACAT
ACGGGCCGCACCTCGAATAATCAACCACCGAGCTTGAAGGATGCAAAACACCTTTCGACATCTTTCCTGTATCCCTCT
TGATAGGTAGCAAATAATTTTTGCTTCTGGGATCGGGGATTTGGAATGGATTTGACAAAAGTGGTCCACCTCGGGTAG
ATGCCGTCAGCTAGATAATATCCCGTCTGGTATACTGTATTGTTGACTTGATAGGTGACATTGGGGCCCTGGCCTCTC
AATACATTGTTGAAGACGGGGGATTGACCCAGCACGTTGAGGTCATTTTGTGATCCTGCAACTCTAAAGAAGGCATGT
CAAACCCATGTGTCGAAGCCAGCAACGGCTTCAAGGATGATACTTTTTTGGTCTTTTCTATTTCCATAATCACGTTGC
CAGGCAGTTGGGCAATTCTTCCATTGCCAGTGCATGCAGTCGATGCTACCAATCATTCCTGGGAATCCTCGAGCTTCG
GCTTTTTCTAGAAGCCGTTGGAGGTCCTTGGGAGTAGGTCTACGCAGGTAGTCCGTAGTGTACAGAGTTTCAACAGCT
TGACAAAATCTTACCAAAGCCTCCAACGTAGTGGACTTCCCCATCCGGGCAATCTCATCCACCTGATCAGCAGATGCT
CCATACGCCAACATTCGTATAACAGCTGTAAGCTTTTGCTCCGGAAGAAGCCCCAAAACCCCAGTAGCATCACACTTT
TGAACAAAGTATGCATCATAATTGCAAATATCATGCATGACTTTATTGAACAAATGAGGTTGCATTCTAAATCGCCTT
CGAAAATCAACATCAGAGTACAAAGAAGTTGGGATAAAATAATCTTCCAAAAGATTCTTACCCCGAGAATGCCTATGT
CTTTCCACATTCCGGAGGCGGCCGACTTGTGAACCACGGCGGCGACCTTGGTTCTCTTCATCTTGCAAAGCCACTGCT
ATGAGAACTTGCTCATCGACTTGTCTCTGCAACTCATTGATTTCATTTGCTCTACGGTTTCTCTCATTTGTTTCTCGC
TCTTGCCTCTCCAAGCATCTCCTAAATTCTTCCATTGAGAATGAATGAAGTATGAATTCTAAACTCTGAGAAATGAAA
ATATAGAAAGATGTGGTGTGAGAGGTATGAGTTGAGCCTCTGGTTTTATAGAAAAATTTGGCAAGATAGACATGCCAC
GTGGCTTGATTTTATTGGATGAAAATCTTATCTGAAATTTGAAATTCATCCGAAATTTGAACCCTAATTTGTATGAAA
TTTGAATTTTGAAATTCATCCGAAATTTGAACCCAAATTTATCTGAAATTTGAATTTTGAAATTCATTCGAAATTTGA
ACCCAATAATTTATCTGAATTTTAAATTTTGAAATTCATCAGAAATTTGAATCCAAAAATCTTATCCGGAAATTTTAT
CTGATTATGAATAGTCTTGGCACATAGGAACCCGAAAATCTTATCTGAAAATATTACCCAAATTAATTATTTTCATTA
AAAAATAGGGGAAAAAACAAAAAAAGAATAGTAATTGCCCTTACCCATGACAATGGGTGGAAACACAAAATACTATTT
GCAAGGGCAACCACTATTCACGTGAATAGTGGCTGCCCTAGCTCCACCCTTGCCATGGCTAAGGGCAAATGGGTGGAG
TTGCTCTAAAGACACAGTTACAGTATTCGTGTTCTATAAGCCATCATACTTCGGAATGTATGCAATACAAGACGCAAA
ATTTCAGTGTCTGTGCTTTATATAAGTCACGGGACTTTGAAAAAGAAAAGAAATATAAATAACCACAAAAAATATCTA
TTTGTGCTTTCTATATGCCAGACAAGTTGTCTTTAAATTACTAAAGCACAATTATTTCTTTCTTATATTTAAATTGGA
CACAAAACTATTATGTTTTCTCTATATATGACACAAATACTACATATATCTGTCTAATGTGATTTAAAAAAGGCATGA
CTCTCTTTTTTGTGGCCTTTGGATCGTGCTTGTTGCCTAGTTTTGTAGTAGTGTATTTAGATATTACAACTCATAAAA
TTTCTTGTGATGGTGTTGGTGAGGAAAATTTTGGGTCAGCGTCTTATTCTTTTTCTTTATATATAGTTGAAATATACA
CTCAGTACTAATTCTTGGCGAGAGATCAAGAATAATTATGAGTGCTACTAAACGGTCTCTAAAATTAAGGGTTAATAT
CAAAAGACCTCCTCAAGGTTTGAGGTCATTCTTAATATGGGCCCTCGATTTTCAATTTCATCAGTTTACACTATATTG
TTTTCAAATATGACCAATTTAAGCTTTCCGTTAAGTTGAGTAGGGGTAGGCACGGTTCGGTTGGGACCGGTTTTTGGG
AAAAAATGGAACCTGATCCGAAAGTGCTGACCGGTTCGGTTTGGACCAGTTTTGCTTAACATCCATACAGAAATCCGA
ACCAAACTGGACCTGTCTGGTTTCGGTTCAGTTCCTGCGGTTCTGGTTTTTTTTTGTTTTTTTAATTTTAATATTTAA
CAAACCTGCCTAAAATGTATTTATATACTAACATACCCTAAATTTGAGGTTCCACCAAGCTTTCAACACATCAAAATG
AATCCATCTTCAACAAAAATACAATCCAAATTCAATCCAACTTCAACATATAAATTACAACCCAAATTCAATCAAACT
TCAACAAAATAAGTTCCAAAATAAATTACTAGCCAAATACAACCCAAATTCAATCCAAATATACATTACAACCCAAAT
TCAATCCAGCTTCATTAAATTCCTCATAACATTGAAAAGTAGCTGGAGCTATGGTGCTAGGTGTGGATGAACTCATAA
TATCTACATAAAAAAACATTAACCCATTAAAATATTAGTCAAACATACATATTATATAATACATTAATAAAGCACATA
AAATTAAAAAGACATACCTAATTCAATCGATTCATAGAACTCCATCTCTTGAATTGTTGGCTCATATTGTAAAGAGGA
TATGTCATCCGACCTTAACCAATTTTGAGAGCAAATTAAGGCCTCCACAATCTGAGGAGTCAAAGAAGCACGAGATGA
ATTAATTACCCGACCACCCGTGCTAAAGCATGATTCCGAAGCCACCGTTGATACCGGGATGGCAAGCACATCTTTTAC
AATAAGTACCATAACTTCTTTTTTCCCCATAAATCTCTACTTTGATTGATGCCATAAGGAAAGCTGCAATCAACCATA
TCTAATTCCCTAAACAAATAATGAGCAGAAATCTTGATTTATACAGTCATAAAAGTTTGATATAATTCCCCATTTCCA
TGAACACTTTTCTTATCTTATTTTTAAGATCTAAAAACAACATAATAACAGGCATACAGTAATATGAATATTTATGAG
TTTTGGGTTGAGTAAATAATCCAGCCAAAAATGCAAACAGAGATTGAAATTTTCAGAGAATAAATCGCTCAATAAAAG
TAAATAAAAATGCAAACAGAAATTGGAAATAACAATATTGAAGATTAAGCATTTACAGAAGAGTGAGAAATTCATCTT
TGGTAGAGAGAGAGTCTTCAAAGGAAAAGTGACGAGAAGGAGTGCGCGGCTGTGTTAAGGGGAGAAAAAAAAGAGTGC
GTATGCTAGAAGTTGCAACCTACTCCAGAAATATGGACGATGATCTGCACGAACTGCTGATGGAGTACATAGAGATGG
TCAGACAGAGAATCGAAGGGGGAAAAGAAACAAAAAGAAAAAAAGAAAAAAGATAGCCATAATCAAACTTGCTTGCGC
GACGACTGAGAGAGCTTCGGCGGCGCAGCGGTTGAAGAAGAACAAGGATGGCTGGAAGAGAGGCTTCACGCAGAGGAA
AAGAGAGGTTTGGCTGCTCTCAGATCAGACAGAGAGAGAGGAAATCAAATTGAAGAAGGAAGAAAGAAACCCAAATCG
TGTTTTAGTTGTGATGATCCTCTGTGTGTGTGCGTACGGTAATATTTTAGGCAGCCAATACAAAACAGCCACATGTTA
ACTATATATATAAAATATAAAATATAAATATATATAATATAAAAATATATATTAATTAATTATATTAGACCGGTTCGG
ATGGGACCGATTCCTTGTAGTAGAAAATCGAAACCAAAACCGATCTGAACCAGTCCGGTTCGAATTTGACTTTGTTTT
TTACTTTTTTAGTAAACACGGTTTTTTTTTTGGATTTTTTTCGTTTAGTTTGGTTCGGTTTTGCGGTTCCAATGCCCA
CCCCTAAAGTTGACTGTCAGAATTCAATTAAGTGACAACAGGTTATTTTTATGGCCCACTTTTTTTTTTTTTTTGTTG
AAAGAAAATCTTAATAAAATAATTATTAGAAATTTTAAAATTGAATATATTAATTTTTTTTAAAGTAAAAATAAAACT
AACCCCGATCCCCGATCCCCGATCCCCGATCCCCTCCCTCCCTTCCAGCGCCACCACTTCCCCACCCTCCCTACACCT
CCACCGTCACCTCATCCCAGCCACCCTACCCACCGGTGGCTTGCGCCCTCTCTCTCCCTTCTCCCTCTCCCCCCTCTT
CCGATTCCCACCAGTGCTGGACTTTAGTGATGAAGCCGTCTTACTTTATGTTCAGATGGTGCTGAAGGGTATTTTGCT
TTATAAGTTCACATTTCTGTTTGTACTGAGTGCTTGCTCCAAGGTTGTGGCTTTCTATGAAGGGGTTCAGCTCCATGG
AGCACTTGTTAAGATGGGTTTGGTGGAAGATGCATTTATTGAGAATTCTTTGATCCATTTCTATGATGAATGTGGGGA
GTTGGATTATGGCCGAAAGGTGTTTGATGAAATGGCTGAGATTAGAGCATTCACAGTTGGGTGGTGTATAATGAGATG
TATGTTAAATATACATTCATCGTGATCGGAATCACCCGCAATGGAGGGTGTAAATGAATGTATAATTACATCACGACC
ATGAGATGTAAATTTAAATGCAATTGTACATCTTTTTTTACATCTCTTGCAGGTGAGACCCAGCTGAGAAAAAGAGAG
GAAAAATAGAGAAAAGTATTTGCATCTTTAGATCGTTTCCCATTGAAGCAAAAATCGTATTTACATTTTCGGAGGTGT
AAATGGAATGTAAAAGTAGCTTTACACCCCCGAAAATACACCCCCCATTGTGGATGCTCTTAATTTCAAATTGATGGG
TTTCTCGTTTATGAAATTTGATGCTAGTTTCTTATGGTTTTTGCATGATTGTTTCATAGAAAATCGCTTCTAACGGTT
TTGAAAATTTTGCAGAATCTGATTAAATGATTGTTCTTGAAGACAATAATTGTGCTTTAGTTTTTCAAATGTTACATT
TGTGTTTGTGATTTCAAAATCTTATCTAAAAGCCTGACAAAAAAAACTTATCTAAAAGCTGTTTTAGGGAGACTTGCT
GATTTGGTTTATGGGTTGTGATTGTTAGGTGACAGTGGAGGGTGTGAGGAAGAGAAGCGACGGGGAAAATTTCAGGTG
AAGAAGGGGGGATCGGAAGAGGAGGGAGAGGGAGAAGAGAGAGAGAGAGAGGCGCGAGCCACCGGTGGGTGTGGCTGG
GGATGGGTAGGGTGGCTGGGTTGAGGTGACAGTGGAGGTGTAGGGAGGGTGGGAAAGTAGTGAGGTCTCGGTTGGGAG
GGAAGGTGCAGATTGGGGAGAGGGGGTTGTTTATTTTTTTATTTTTTTTAATAATAATATATATTCAAATTTTAAATT
TCTAATTAATATTTTATTAGTATCTTCTTTCACTAAGCAAAAAACGTGGCCATACAAAAGACACGTCATTACTTGATG
GATTTTCTGACAATTAGCTTAACGGAAAGTTTAAATTGGTCAGATTTAAAAACAATAGGGTGTAAATTGTTGAAATTA
AAATTCGGGGGTCCATATTGAGAATGACCTCAAACCTTGAGGAGGTCTTTTGATGTTAGTCCTAAAATTAATTAATTA
AGTACACCATACTACCAAACTATTTATTGAATTACTAACTTACCCTGCTATAAAATGATCAAAAAGGAAATATTGAAT
TGTGAAACAAATATAATTTTAATAAGTACATCCCACTCATCATATTCAACCATAATTCGTAAGCGAAAAACCCTTCCA
AACTTGTTCTTGTACTTCAAGTGCAACCTTTCAAAGCTCTTCTAATTTACTGCTACATGTACATCCTAGTTGCAAAAC
AAGAATTTAACAATGTTCACCAAGGTGCGATGAAGAGAGGTAGATTCTTTGTGAGCCTTTTCAGAGACCAAAATATAG
AGGTTAACAAAGAACTAAAGGAATGCTTCTATAATGTATAAGATATTACTAATCTTACTCTTAGGAAATCTGCATAAA
AAGAGTTGAAAAGTCAATAACCTTAATAAAGGGACTGGCTGTAGCAATACGAGGGACTGGCTGTAGCAATACGAGGGA
CTGAAACTTTTTTTTAGAACTATCTTTTGGGCTTTAATTTTTTTTTTTTTTTTCTCCGTGGAGTAATCTTATGATTGA
TTCAAAGGATCCAATTTTGGGTTTATAATTTGAAGAATGCTAATGAATGGAAAAATGAGTTTAGTGTTTTGTGATAGA
GTGTATTAGGGTGTACTATGAGCATTTTTGGTAATTAAATAGGATGTATTTAGTTAATTTTACATTTTGATTTAAATA
TTATAGCGTACTTTTTTTCTTTTTTTTGTTGTTGAGAAATTCTATGATTGCATTCATAATTCAGTCAAAAAAGTCACT
AGCCACAAAAGGGCCATTACAATAACGAAGCGGTCTAATATCAAAATTAAGACAATCTGGTGTGTCTCCACTAACGAT
CAGGCAAGATCGAAGAAATTCTGGCATAGGCATCCCAACTAAGATTGCAAACTTAGAATAATAAAAAATAGATAAAGC
TTGAAAAAACCAAGCCATAATAATACAAATAAAACTCTTACAAATGAGAGATGAAAAGCTCTCACAAAGGAGAGATGA
AAAACTCTCATAAAATGAGAGGTGAAAACTACACAGAGAACCCAAAGAGTCTCTACAACTTATTCCAAACATAAAGAA
ATTGCTAAAAAGATGGTAGTGGAGATTCGATACCGAAATATTATAGTGTACTTAAATAATAGATGTATTCAATTAATT
TTATAGTTCGTTTAGCAGCACTCATAATTATTTAGAAACAGAAACAAATTCCTTTTGGTACTTAAACGCTAACCTCGG
CCTGCCCCAAAAACAAATTGCTGAAGACTCTCAGCCTTCTCTTCCATCACTTCTCCACATTCTTCCACATTGTGCCTT
GCCATCCAATCAGAAACAAACCAGAACCCTTTCCATCGCAATCACCATTAATGCGTGTCCCCGTTGGTAAGTTTTTTC
TTTCTCCATGTCATATATATATATATATATATATATATACACTTCTTTTTAATTGGATTATCTATTGTAGACGTCCTT
GAACTTGGCCCCCAGGTGCAATTGGATCCGTGAACTTTTTTTGAGGCAATTACATCCGTTAACTCGATAAATAGTTCC
AATTGAGTCCTACCGTCCAACTCTGTCAATTTATCTGTCAAAGTGAGAGGGTAAAAGCGTCCTTTCGGGTTCATCCAT
CATTAACCCCAACTCCACCTTATTCATCCATCATCAACCCTAACAACCCTACCTCAATCTTCACAAGTTTACAATACA
AATCCATATCAAACAGTTTGTGATTGGTAGAAACTACATAAAAGAATTTAACCCCAAAAAGAGAAAAAACCATGCTAT
GAATTCAAAAGTTTGTGAAATCTGTAGAACCCATTTGTGCACTAACAATTCGTACAAGCTCACTTCTCTGAAACCAAC
CTGACAACACAAACACACCGCCTGAGCCACCACCACCGTCTGCACTGTCCCAAAAATCTGGTAATTATTATGCCAATT
GAAAGATCCAAGTTGAGTCACTACACTTGTACATATAATGATCTTACAATTTCTGCTGCTGTTGTTGTTGTTGGTCTT
TCTTTGTGGTGGTCCCATTGCTAGCCTCTTCTATGTTGTCCTCGGGGAGATGGGTTGCAGGTTGGGAAATAGGGGGTG
GGTTGGGAACTGAGTTTTAAGGGGGGTAGGATAAGGAGGGGGGAATGGATTGTGGAGAAAGGGAGAGACAGAGCGAAT
GAGAGAGGGATTTTTATTTTTAAGTTTATTTATTATTTTAATTTAAAAAATTCAAAATTTTCAGTTTTTTTCTTCAAG
TTTTAAATTTTAAAATATTTTAACTGAAATGGACGGGTTAAATTGACAGAATGACTCAATTGAAACGGATGAAAGAGT
TGGATGAACTAATTGACTAAAAAAAAGATCGGAACCCAATTACAACTGAGAATAGATAACCTTTTTTAAATCATCAAC
TTGAATCCAATACTCTTCTTCTTGTTGTTGTTCCAGAAAACCAAGATGTGCAGGAAAAAGTGCACACGTACATAGTGT
GGCCCATACCACCCGATGACATGGTCCGCCGAATCAAGAAGGTGATGGAGAGCCTCCCGACCTAGTTTGGTGGGCCCC
AGATCGAGCCACATCACCACTATGGGGTCCATCCTTTTGAGCCATGAAGGAGCAGTCGAAAGCTTCACATAGGCTTGT
GAAGTTTCCAGCGACACAGTTTTAAAGTTGGTCATGTGGGTGTGGCTACTCGGAAATTCTTTTACCAGTGTGTTTCGC
TCTTCATCCATCCAATAAGTTAGTTTGCACTTCTTGTTATTACTTTTCATATGCAGAGATTTCATTAGAGAAATCATA
GAATAGTATCGTACTACCACGTCAACTAGTGATATTCTCACTCCAAATATGACATGTGTTTTAATTATTTTAACAACT
CAAACTTTCTTTTACCGCTGTAATTGACCCTAATTTTTATCTTTAAAATAAAATTAAGAAGAACAATTGAAAGGAAAA
AAGAAGAAGAAAAGGTAGAGCCATCGCCCACCCTAAAACGCATACCCCGTGCTGCTTGCTCTAGTCACCGCTATGGCT
GGCATTTTGCACCGTAACCCCTCAAAACTGATAAAATCGATCGAGATGTTGCTCCAAAGAAGCCGACATGTCACAAAA
GCCAACCGAGATCTGCGATTTCTTACACCAACCGCAATCTGCGATTGCCGATGCATATGCGTTTCTACAAATCCAAAA
ATTGCGGTATACCGCACTGACTGCAATATATAACTAACAGCCTTTACATGAATCCCTCAACCTCCAAACCTCAGCCTC
TCCTCCTCCCTCAGCCTCTTTTCCACCTTAACTCAATATCTCTTACTCTCAGTCAGTCTCTCTCTTTCTCGTCTCTAC
CAAACCCCAGTCTCTCTCTTTCTCGACTCAACCAAATTCTTTTTTAAAGATTATTATACTCATAAATAGTTTTTTCAA
TACCAACCAACCAAATTTTTTTCAAAACCTCATTTTTTAAAATTATTATATCCATAAATATATTTTTAATACTTTCCC
TTAAGTGTTCCTAAGGGATGCGTTTCACTACCCAAGGAAACACAAAAATAGGTGCCTTCGCTTATCTTCTTCTTCTTC
CCCTATCTGTTTCTTCTATCTCTCCTCCCCATTCTTTGTTTGATCTCTGGTTCTACTCTTCACATCTTTGTTCTCAAT
TTTTTTTTGCAGATTTGGTATACCGCAAAATCCGACTGCACGTCATGGTAACTATCACCCCCATAATGGCAATTATGT
GGTTCGACGATAGTTCATATTTTAGCTATACTACAATCATTCGGCCGATTTATGATTGCACGAAAAACTCGCGGTTTT
CAAACCGCAACCACCCCTAATCACCGCCCTTCCCTATCTTTTATCTCATCCTCTCTCTCTCTCTCTCTCTCTCTCTCT
CTCTCTCTCTATGTTGCCCTTCTTCAACTTTCTCAACCTTTCAGTGACTATCCCCAAGATCTATACATATTTTCTCAT
TGACGAAGGTCTCCTCGGCAGATGTGATTCGTGAAGAAGATTGGGATGGGAGGTAGGTGTTATAAGGGAAGCTGTAAT
TTCTCCTACACTACAGCCGTATCAGAATCAAATAGAATAAATGTTTGCTATTAGTTTACTTTCCTTGTATGTATTGTT
GACTTAGAATATTCAATTGTAATTTATTTTCTTTCCTTCTTAGATACAGAAATCTCTGTATATATGTAAAGGGTTTTG
CCCAATCAAAGTATTAATTGAAAACATCTTCTCCTCTAATGTTGTTATCACCCCTAACTCCAACACTACTTTCTCTCT
CTCTCATTGCTATCAACGCTGCTGCACAGCTTCCTCTCAAACTCACCCCTCTCAACTATCCCTCCTGGCGTGCCCAGT
GTAAACTTAATAAGTTATAATAACTTGAACACTAACCTTGTTCTGCCATTGAAGCCTTTTGTCAAAACACCTGGGAGA
CAGCTCTTCTCTAAGATCACCGAATGCCTTATTCTCTGATTCCAGATGGGGTGAATCGCTTGATGAGATTTTGTGTGT
ATCGGCTCTTAGAGGGAGCTGTTCTATTTATATACATCACTCAAGGAGTCTTGCCCATCAACAGACTCCTTGAGGTAT
CCTTATTGCTATAGAACTTTTAATCCTAATTCTCATAGAACTAGAAACCCCTTTAGCCTTGTAATCCATATGGGACAC
TGACACAGAGGCTGCAGGTCGAGAGTTGTGTTGAGCTCTTGATTAGTCTTGAGTCTTGCAATCCGATAATGAATAGAA
GACCAATTCTGAAAGGATTGGGATAATAAATTATCTTACATTCTCCCACTTGGTCAAATATTCATTGTGACTCAAGAG
CAATCTCTTAATGGCCAATTTAGAACTCAACCTTCTCAGTTTCTTATCAAGCCACTGTCATTGATATAAACTCATATG
GAACTGTCAAAGAACATTGAGCAACCAAAGTCAAGTCTTTTACAACCACACATACAAATGTACATCAACACATGCGAC
TGCCAACTGAATTAGTATCAAAACTTGTTGTGATCTACCTTAGTAAACTTAATGATCAAAACAAAACTTAGCTCACCC
TTACAAGACTACCAAGGTCTTAATAAACTTACATGACTACTTCATGGATACGAAAATGCAAAAAACACAAGTGCTAGC
AAATTTTGCAGATTCTTCCTTCATCCATATGTCAAAATATTTATAAATTGGAAAAACACGATTTAAGAAAACTTTGAA
TAGCAATTTCAAAATAAAACTGTAAGGACAACTTCGATTGAAACTAATTAAAAGAAACCATATCTAACTCTGGCTCCC
ACTGACTCCCACTGACTTAAACATCAAAACTGATCTGCAAACCCATGCTTCTGACATGCCTGTGAAAAACATGATTAG
GCAAACCTTTGTTCAAAGGGTCTGCAATCATAGAATCTGTCCCAATGTGATCTAGAGTTGTAAGACCATCTCGGATCT
TCTCTTTTGCTGACAGAAACTTTAACTGCAGATGTCTCAGACCTGACGATCTCTTATTTCCTTTTGCAAAATAAACTG
CAGCACTGTTATCATTCCACAACTGGATTGGTCTCTGTATGGATTCCACAATTCTCAACACTGACATAAAATTCTTAA
GCCATATTGCTATTGAAGTAGCTTCATAAACTGCTAAGAATTCAGCCTGCATAGTTGAGGTTGATACATTTTGTTGTT
TTACACTTTTCCATGCCACTGCTCCCCCTGCAAACAAGAATACAACACCTGATGTACACTTCTGAGTATCCAAGCATC
CAGCAAAATCTGCATCAGCATATCCTTCCAGTTTTAATTCTTCAACTCTTCGATAAACCAGTTTGTACTCTTTAGTTC
TCTGTAAATACCTCAAAACCTTCTTGCCTGCTACCCAATGTTGTTGTCCTGGGTTAGATTGAAACCTTCCAAGAACAC
TTATGCAGAAAGCAAGGTCTGGCCTTGTACAAACTTGTGCATACATCAAGCTTCCTACAAGTGAAGCATAGGGCTTGT
CCTGCATTTCCAGCTTTTCTTGCTCAGTTTTAGGAGATTGATCACAGCTCAGTTTATCACCTTTTGAGAATGGAACAT
CACACCCTGTGCAGTTTTCCATATTGAATCTTTTGAGTATCCTTTCTATATATCCTTTTTGTGATAGACCAAGTAATC
CCCTTTCTCTATCTCTACTAATTTCAATCCCCAATACATAATTTGCTTCACCTAAATCACTCATCTCAAAATAATTTG
ACAGCATTCTCTTAGTGTCATGTAATAATGACAAGTTGCTGCTTGCTAAGAGAATGTCATCAACATAAAGGAGCATGA
AAATATAATGTCTTCCATGAAATTTGAGATAAATGCATTCATCTAAGGGATTATCAATGAAACCTTGAGACTTCACAA
CTTCATCAAACTTCAAATACCACTGCCTTGAAGCTTGTTTTAATCCATATATTGATTTTTGCAACTTGCAAAACAAAT
CTTCTTCCCCTTTTTGAATGAAACCATCCGGTTGTTTCATATAAATTTCTTCAATAAGGTTTCCATTCAAAAATGCAG
TCTTAACGTCCATTTGATGGAGATGTAAATCGAAATGTGCCACTAATGCCATTATCACCCTTAAAGAATCTTTAGTTG
AAACAGGTGAAAATGTTTCATTGTAATCCACTCCCTCTTGTTGTGTGAACCCTTTTGCTACCAAACGTGCCTTATATC
TGTCTATTTGTCCCTTTGAGTTTCTTTTGGTCTTGTAAACCCATTTGCATCCTATTGGTTTACATCCTTGAGGCAATG
CTACAAGCTTCCATACACCATTTTTACTCATTGACTGAAGCTCAGACTCCATTGCTTCCATCCATTTTTCACATTCTT
CACTTTGCACAGCCTGTTTAAAAGACACAGGATCTTCTGTGGTGTTGATGTCATGTTCTGACTCTTGCAGGTAGACAT
AATAGTCGTTTGATAAAGCAGGTCTCTTAGTTCTTTGTGACCTTCTCAGTTCTGAGTTGTAAGGCTGCTGCTCTTGTT
GATCTATCTGCATATTTTCTGCTGCAGTTGGTTGAGCTTCAGTTATTTGATTCTCTTCTAAATTTCTTTCATCATGAA
TTGGTGAGATTTGTTTGTCACTCGAATCAGTGAATGGCAAAACTGTTGTTTCTCTTATCAAAACTTCTTTTCCTGTAA
ATTCCTCACCTTCCAAAGTTTCATCAAAATCAAAATTTTCATCAGTGCCTTGCTCACTTTCATCCTCAATGAAAATTG
CTCTTTGTGTTTCCATAAACCTTGTGGTATTGTTGGGACAGTAAAACCTGTACCCTTTTGTTCTATCTGGATATCCCA
CGAAAAAGCATGTAACTGTCTTGGAATCTAGTTTCTTTTCTGATGGATTATAGAACTTTGCTTCTGCCTTGCTTCCCC
AGACTTTGAGGTGTGAGAGACATGGTTTTCTGTTGCACCATATCTCATAAGGGATTTTGTTCACACTTTTCGTAGGAG
TTCTATTCAGCAAATAGTTTGTTGTTTTCAAAGCCTCCCCCCAGAGAAAATTTGGAAGTTTAGAACAGCACATTAAGC
TTCTAATCATTTCAATCAATGTTCTATTTCGTCTTTCTGCCACGCCATTTTGTTGTGGCGTACCTGGATTAGTATATT
GAGCCACAATTCCTTCTTCTTGTAAAAACTTTGCAAAAGGTCCAGGATTTCTTCCTTTTTCATCAAATCTGCCATAAA
ACTCACCTCCTCTGTCTGACCTTACCACTTTTATTTTCGAATCCAGCTGGTTCTCTACCTCTGTTTTGTAAACTTTAA
ACATGTCTAATGCATTGGATTTTTCAGATATTAAGTATACATAACCATATCTTGAAAAATCATCTGTGAAGGTTATGA
AATACTTAAAACCATCATGTGTTTTAGTGGGAAAAGGACCACATATGTCAGTATGTATAATTTCCAGCAGTTTCTCAC
TTCTTGTAGCACCTTTCTTCCTCAAATTAGTTAACTTTCCTTTAACACATTCAATGCAAATGTTGTCTTTGTCATTGT
GGTTAAGTGGTGGCAACAGATTTTCTTTGTTTAGCAGATTCATTCTTTCATTCGAGACATGTCCTAGTCTCTTGTGCC
AAAGTCTATATGATTCTTCTTTATCTGCTTTCCTTTTAGTGCTTATCAGATTGATGTTTAGATTAGCAGTACTTGGAT
TTGGTTTCTTGCAATTCAAACGAAACATGCCATCATCTAGAAAACCATTACCAATCATGACTTTATTTCTGAAAATGG
AGAATCCAGACTCATCAAACTCAAACTGCAAGTTTGATTTTACAAGCTTACTAACTGAAATAAGATTCCTTTTCATAG
AAGGAATATAAACTACATCTACTAACTCCAAAATAAAACCAGACTCCAAAACGATCTTAGCTAATCCAATGTACTCCA
CCTTGACTCTTTCTCCATTTCCCACGAACACCTTCATCTCAGCCTTGCTTGGCAGCCTCTTTGTTTTGAACCCCTGCA
AACAATTAGCCACATGAACTGTTGCACCACTATCCAACCACCATGAATCTGAAGAAATCTCAATTGCATTAGACTCAA
AACAAACATTTACTTGTCTAGACTTACCTTTAGCCTTCTGTTTATCTAGCCAGCGTTTGTATCTGTCACAATTCCTTT
CATATGACCAAATTTCTTGCAGAAGTAACACTTGAAACCTTCTGGTTCTAGCCCCTTACTCCCCTTTCTTCCTTGTTT
TTCTTCCAAGTAATTTTACCCTTTCCCAAATCCTTTTTGGGTTTGAAGTTGTGAACCATGTTAACTCTTTCTTCAGCC
TTATCTTTCTTCATATTTTGTTCTTCCTGCACACAGATGCCTATGAGGTCAGTTACTGTCCATATTTCCTTCTGTGCT
ACATAGGTGCTTCTAAGGTGCTTGAAAGTGCTTGGTAGAGAATTTATTGCAAAGTGTACCATCATATTTTCATCCACA
TTGACTTTGAGTGCTTGCAGCTTGTTCCCAATTTCCAGCATATTCAATATATGTGTTCTTACACACTTCTCCCCATTG
TATTTTGCATCAGTAAGTTGTGCCATCAGAGTACCAATTTCAGCTTTCTTGGATTCCTGAAATTTTTCCGCAATAGAA
TCAATGAACTTCTTGGCATTATCAGATGGTGTGATGCTTCCTCTGACAGATGGTGAAATTGATCTCCTCATGATTAGA
ATAGCCATCTTGTTGGCTTTAATCCATTTTGCATATTTTGCTTTTGCTTCAGCAGATGCAGTAGCAGTAGGTTCTGCA
GGAGCTTCTTCTTCAATGACCATCTCATAATCCAGCAATCCTAGAGCAATTTCCACATCTTCCCTCCATTTGGTGTAG
TTGGAGCCAATGAGAGTTTCAATCGAGTTGTGATTAACTGAAAAACACATGGTATATATATATGTGTTTAAAAACTGA
AAACCCCAGAATCTTTAAAACATGATCAATTCTCACCTTTAGGTGAAGAAATCAAAAACATGTTCAACACTAAGATAT
GAAAATCACATAAGCTTCCTGTACAAGAAAAGTTCCACATCTTTGGACAGAAGAACAATCTTGATAGCCTACATGTTT
CATCTCTTATGCTGTTCTGCTGAAAATAATTGCACGATAAATCATTCACATCTTTGGACAGTGAATCATTCATTATGC
CTTTATTTTCAACACAAGTTTGATCATAAAACTTTGAATGTACAGATCTTGTTGTGTCTGAGTTGCTTTGGCTTGCTC
AGAGCACGGCAAGAACTATACAAACTTTTGATCAATTTCTGTTTTGTCACGGCAAGGTGTTAACTTCAAACCTTGCTG
TAACAAGTTTCTCTAACCTTGAAAATTTTAATTATCCTTCAATTTTCAAGTTCTAAAAGCTGCAACAAAATTGGTTGG
GTAGAAGATAAAATAACTTATGCTCTGATACCACATGTAAACTTAATAAGTTATAATAACTTGAACACTAACCTTGTT
CTGCCATTGAAGCCTTTTGTCAAAACACCTGGGAGACAGCTCTTCTCTAAGATCACCGAATGCCTTATTCTCTGATTC
CAGATGGGGTGAATCGCTTGATGAGATTTTGTGTGTATCGGCTCTTAGAGGGAGCTGTTCTATTTATATACATCACTC
AAGGAGTCTTGCCCATCAACAGACTCCTTGAGGTATCCCTTATTGCTATAGAACTTTTAATCCTAATTCTCATAGAAC
TAGAACCCCTTTAGCCTTGTAATCCATATGGGACACTGACACAGAGGCTGCAGGTCGAGAGTTGTGTTGAGCTCTTGA
TTAGTCTTGAGTCTTGCAATCCGATAATGAATAGAAGACCAATTCTGAAAGGATTGGGATAATAAATTATCTTACACC
CAGTTCAAAGCCCTTCACCTTGGGTATGACCTCCTGAACCTCTTGTTGTCACTGCCAATAATACCTAGCGAACCTACT
CCAACCATTCCTTCCACAAGGGTTCTACCACATCCTATGGCTACAGGCCACCTTCTCAGCAACGTGGCATTCTTGGCC
CCGACAACTCTTTCCTACACATTTCCCTTCCATTTTTCGGATAGCATTGCTCCTACAATCAACCAAACCATGGTTACA
AAGGTTTCTGTCAATTGTATGATCAGCAGGATCACAGTGCCAAACAGTGGCCACGTGCTCAGGTTCTACCCTCCCCTG
TTCCACTGTGAACGTTGCTACTGCTCCTGATATCGCCACCAGTTGGCCCATTAACTTTGGCGCTTCTCATCATGTGAC
CCCTGATCTTGCCAACCTTTCTCTCCACACCAATTATGAAGGCCCTGACTCAGTTGTGATGGGTAATGGTTCAGGCAT
GGGCATCACCTATGTTGGCTCCACCTCTCTTCTCTTCCTACCTCCTTTCGTGCATTTGCCTTACATGATGTTCTTTGT
GTGCCATCCATTAAAAACAATTTAATTTCTGTCTCTTAATTTTGCAAATCTAACCACACTTCTGTTGAATTTTTTCCT
TCTTATTTTTCTATACAGGATCTGCGCCATGTGCGACTCTACTTCAAGGCCCAAATAAGATTGATGTGTACGTGGCCC
GAGTCAATGATTAACGTCTCCTCACCTTCTACACTTGTTGGTACGGCTTCTACCCTGCATGACTGGCATAGTCGCCTT
GGCCACTCTTCTCAACCTATCCTAGATAAGCTCATCCGCTCTCAATCTCTCCCTGTCACTTCAAAGTCATCTGTTAAG
TCTCCCTGTGTGTCGTTCCAATGTAATAAGAGCCATAAGCTCCATTTTCATTTAAATTCTCTTTCTAGTCAGCTTCCT
CTAGATCTTATCTACACTGGTGTCTGGGGTCTTGCTCCCTTTCTCTCAATTGATGGTTTTCGCTATTATCTTATTTTT
GTCGATCATTACACAAAATATATTTGGTTTTACCCTCTTAAAAACAAGTCTGATGTATGTACAATTTTTTTCCACTTT
TAAAAACCTTGTTGAAAATTACTTTCGCTCCAAAATTGTTTCTCTTTAGTCTGATGGTGGTGGCGAATACAGAAAATT
TAAACCTTTTCTCGCCTCCCATGACATTACTCATCTCGCCACACCTCCCCACACCCCAAAAACATAATGGTTCCGCCA
AGCGACGTCATCGTCACATTGTTGAGACCGACCTTGCTCTCCTCAACCAAGCCTCTATGCCACCACTTTACTGGTCTT
ATGCCTTTCAAGCTGTTGTATATCTCATAAATCGTATTCTCACTCCTCTCCTTAAATCATCCTCCCCTGACACATCTC
TTTTTTGTCAAACACCAAACTACCATAAACTTCCTATTTTTGGTTGCCAATGTTTTCCGTAGTTACGACTTTACAATA
CCGATAAACTCCAACCCCGCTCTCGTCCTTGTGTCTTCCTTGGATTCTCAACCTCTCAAAGTGCCTGTAAGTGTCTTG
ACCTATCCTCCAATCGTCTTTACCTTTCTCGTCAAGTCGTTTTTAATGAGTCTATTTTTCCTTTTACCTCTCATGTCT
CACTTTTCTCCTCTGTCTTTCATCCCGCTGTCCACTCGTGGTCTGTCGCAGCTGATCTGGGATCCATTGCTGACCCTT
TGCCCATGCTACCAGCCATGCACATGCCTCTACCACTATTTCCCCTGCCCCTACAGCACCATTACACGCACCAACAGC
ACCAGTGCCAGCTCTTGTTGCACCGATGCTAGCCCCTTGTACACATCCTTCTTCTTCCGTCTTGGGTGAGTCTTCTCT
CGTGTCCCCCACTTTCTCTCATTTCCCATCCTTCTCTCTTCTTTCTTCCGAGGCTCCCACTCTCTCATGGCCTTCTCC
TCCACCACCCCATCCCCCTTCTCGTATATTTTTAAACCTAAACAGATTCACACCACCACTAACACAGTCCACTACCCA
ACATCATCTTCCCCCCTCCCTTGAACCTACCTGTGTTTTCATGCCAACAAAGACAACAAGTGGCACTCTGTCATGTCC
GATGAGTTACTGCTTTGGTTCGGAATGAACTTGGAGCTTGTTCCATCTTGCCCTCATCAAAATTCAGTTGGATGCAAG
TGAGTGTTTTGCATCAAGCGTCATCCTGATGGAAGTATTGACAAGTACAAGGCCCGTTGGGTGGCAAAATGGTTCCAT
CAGCGCCCTGACATTGAATTCTATGAGACCTTCAGTCCAGTGGTCAAACCCACCACTATTCGGCTTGTCCTACACCTT
GCTCTTGCTCACGGCTAGCCTATTCGGCAACTTGATGTTAATTACGCTTTTCTTCATTGAACTCTTCATGAGGAAGTG
GTTATGTCTCAACCTCCTAGTTTTGTTGATTCCGCTTATCTTTCTCATGTGTGCAAGCTCCGCAAGGCCCTTTATGAC
CTTAAACAAGCACCCTGGGTGTGTTGATTATTGCCTCAAACCAATAGTCAAAAGTGGTAGGCTATTGTTGAAGTTGCA
ATGTGAATGCATTAATTGGCTTTCACAAATGGTGGTAGGCTATTGTTGACTTTGCCTATGTGAATGAATGATGGTAGG
CTATTGTTGACTTTGCCTATGTGAATGCATGGTGGTAGGCTATTGTTGACTTTGCCTAACCTTTGGCTTCTTTGAGAA
GCCACTTCCTTTGGCTATAAATTGGAAGCAAATGGTTTCATTTGTAGCATCCAACCAAGAATCCAACCAAGTGTTGAG
TAGAAGAGAAAAATAGCAAGAAAGGCATTTTGCCAAAGAGTGAAACAAATTCTCTCTAGTTGTTCTTTGCTTTGTATC
ATTGTTTTCTCTTCCTTTGTGAGTGTGTGAGGTTGGGTGTATTTGGGTCTTTGGGAAATTGAGTGGTAAACACTATTG
TATATCTCCATTGATTATAGTGGAATACTCCATCGTCTCCAAACTGGATGTAGGCAATTGCCGAACCACGTATAAATC
TTGGTGTTCTTCTTGTTGTAATTCTCTGTTAAATATATATTTTTTTTTCCTGCCAGTAGTTGTTTATTTTTCACTCAC
AGTTGGTTGACGCTTCCGCACGACAAGTGGTATCAGAGCTCCAGTTTTTCGACTGGGGTTTCGTGGGAGTGAAAAATC
TGTCGGTGCTACAGTGACGGTGAATAGTGCTGTGCTACAATAGCAGTGAATAGTGCCGGGCAGATTTGATGGCTGGAG
AAAAAGTTGAAATTTTAAAGGAGAAGGAATCGACATCGTCTTCGTCGGCACCTACATCCAATAGACATCCAATTGCCA
GTACAAGGTTAGAGGTTGATAAATTTAATGGCTCCAATAATTTTGGTATGTGGCAATGTGAAGTTATGGATGTGTTGT
ATCAACAAGAGTTGGATATGGTTCTGGAGGATAAACCAGAAGATATTGATGACAAGCAGTGGACTCGAATTAATCTCC
ATGCTTGTGCCGCTATTCGATCATTCCTTGATAAAGAGTTGAAATACCCGTATATGAAGGAAACTTCTGCTAAGAAGT
TATGGATGAAATTGGAGGAGAAGTATATGACCAAGAGCGCAGAAAATCGGCTCTTCTTGAAGAAACGACTCTTCCGAT
TTCAATATCGTTTAGGTATTTCTATGCATGAACACCTCAATGATTATAATAAAATACTGGCTGATTTAGCAAATCTTG
ATGTGATAATTCCTGACGAGGATAAGGCACTATGTTTGTTAAATTCATTGCCTGATGATTATGATCATTTGACAACTA
CTTTGTTGTATGAAAATCCGAGGTGAAACTGGATGAGGTGTCTGCGGCATTGGTGAATCATGAGTGTCGTAAAAAGGA
ACAGAAGACTCAAAATTCACAAACCGAGGCACTCGCTTGCAAGGGGTCGAACAGAGGAAAGAAAATCTGGGAAGCGGG
GAAAATCTCGTTCAAAGTCACGAGGGAAGTTTCCTGCTAAAGATGAATGTGCCTTTTGTCGCCAAAAGGTCATTGGAA
GAAAGACTGCCCCAAATTGAAGAACAAGGAGAAGGAGAAAGCGGGTTCTGAAGCAAATGTTGCAAAATCTGGAGATGA
AGATTTCGAGTTGCTTTGGCTAGTTCATCTGCTGATGGTCACTCAACTGAGTGGATTTTGGATTCAGTTGCACCTATC
ATATGTGTCCCATTCGGGAATGGTTTTCTAGCTTCGAGGAGCTGGATGATGGAGTTGTTTTGATGGGCAATAATAATG
CCTGCAAAACACAAGGGATAGGCAAAATCTGTTTGAAGATACATGATGGAACAGTCAGAGAATTGAGTGATGTTCGGT
ATGTACCGGATATGAAGAAGAATCTCATCTCATTGGGCGCTTTGGAATCCAAGGGTCTCAAGATCACCATGGAAGGTG
GAGTTCTTAAAGCTGTGTACGGGGCACTGGTGGTGATGAAAGGTACAAGACGAAATAACTTGTATTTCTTGCAGGGTA
GTACAGTTATTGGTGGAGCAGCTGTCACCGAAGCTGCTGACGCAGATAGCACAAACACCACAAGGTTATGGCATATGC
GTCTTGGGCATGCTGGTGAAAAAGCGTTGCAAGGATTGGTGAAGCAAGGCTTATTGAAAGGTGCAAAGGCATGCAAAT
TGGAATTCTGTGAACACTGTGTGCTGGGTAAGCAAACTAGAGTGAAATTTGGCACTGCTATTCACCACACTAAAGGCA
TTCTAGATTATGTTCACACTGATGTTTGGGGACCTTCCAAGAATGCATCTTGGGGAGGTAGCCATTATTTTGTCTCCT
TTGTTGATGACTTCTCTAGAAGAATATGGGTGTACACCATGAAGCGTAAAGATGAAGTCTTGAAGATATTCCTGAAGT
GGAAAAGATGATTGAAACGCAAAGCGGTCGAAAGATCAAGACTCTCAGATCAGACAATGGTGGTGAATATAAGTCTGA
TCCTTTCTTGAAAGTTTGTCAAGATGAGGGTATTGTGAGGCACTTCACGGTTAGGGAGACACCGCAACAGAATGGGGT
GGCGGAGCGCATGAACCGTACTTTGCTTGAGAAAGTTCGGTGTATGTTGTCTAATGCTGGTTTAGGCAAGGCGTTTTG
GGCTGAGGCGATTACTTATGCAAGCCATCTCATAAATCGGTTGTCTGCTGCTGCGAATGAGGGCAAAACGCCCATGGA
GGTATGGTCTGGTAAACCTTGTACTGATTACAAGTATTTACACATATTTGGTTGTCCTGCTTACTATCATGTCAGGGA
AAGCAAGTTAGATCCAAGAGCAAAGAAGGCTCTATTTATGGGATTTAGCACTGGCGTGAAGTGATACCGACTTTGGTG
TCCAGATGAGAAGAAAATTGTTGTAAGCAGAGATGTGACTTTTGATGAGGCTGCTATGGTAAATCAGAACAAGCATGA
AGGTGAAATTGAAGCAACTAAGACCATGAGTAGTTCAAAGCAGGTGGAGTTACTGAAAACTCTAGTTGTTCCGGTAAG
GTCTGATACTACAGACACTAGTCCTACAGTTGATTCTGATGAAGAGGACGAGGATGATGAAGAGGAGGCACCTACCCA
AGAGCCTCCACAGCAACAAGATTCTATTGCAACCAGAAGATCGAGAAGGGAAATTCGAAAGCCTGCTTGGTTTACTGA
TATTGTGGCATATGCACTTCCCGTTATTGAAGATGATATTCCATCCGCCTTCAAAGAAGCTGTCAGAAGTTCAGAGAG
CTTGGAGTGGAAGAAATCTATGGATGAGGAGATGAAGTCTCTTCATAAAAATGAGACTTGGAAGCTGGTTCAGTTACC
AAAGGGGAAGAAAGCAATTGGTTGCAAATGGGTTTATGCCAAAAAGATGGAATCTTTGGGAAAAGACAATGTAAGATT
CAAAGCCAGATTGGTAGCTAAAGGCTATGCTCAGAAGGAAGGCATTGACTACAATGAGGTATTTTCTCCTGTAGTAAA
ACATTCCTCTATTCGTATTTTGTTGGCTTTGGTTGCACAGTTTGACCTTGAGTTGGCTCAACTTGATGTCAAGACTGC
ATTCTTACATGGTGATTTGGAGGAAGAAATTTATATGTCTCAGCCAGAAGGTTTTGAAGTTGCTGGAAAAGAAAATTG
GGTTTGCAAATTGCAAAAATCATTGTACGGCTTGAAGCAGTCTCCAAGACAATGGTACAAGCGATTTGATCGGTTTAT
GATCGGGCAGAAGTACACAAGAAGTCATTATGACCATTGTGTATACTTTCGCAAGCTACAAGATGGAACCTTCATCTA
TCTGCTTTTATATGTTGATGATATGCTTATAGCATGTAAAAGCAAAGTGGAGATTGAAAGGTTGAAGACTCAACTGAG
TAATGAATTTGAGATGAAGGACTTAGGAGAAGCTCGGAAGATACTGGGTATGGAAATTGAAAGAGATAGAGCGAAGGG
CAAGATTAGTCTGTGTCAAAAGCAGTATTTGAAGAAGGTACTACAATGTTTTGGGATGAATGAAAATTCAAAGCCGGT
TAGTACACCTCTTGCCCCTCATTTCAAACTTAGTGCTTCTATGTCTCCTAAAACTAGTGAAGAGAGTCATTACATGGC
TCAAATTCCATATGCAAGTGCTGTTGGTAGTTTGATGTATGCTATGGTGTGTACAAGGCCTGATATTTCACAAGCTGT
TAGTATTGTCAGTAGATATATGCATAATCCAGGAAAAGGGCATTGGCAAGCTGTGAAATGGATTCTGCGGTATATTCT
GGGTACTGTAGGTGTTGGTTTATTGTTTCAGCAAGATAAAGTTACTGGTCAATGTGTTGTTGGATATGTGGATTCTGA
TTACGCAGGAGATTTGGACAAGCGTAGGTCCACTACAGGTTTTGTATTCACTATTGCTGGAGGTCCAGTGAGTTGGAG
GTCGATTCTGCAATCTACAATTGCTTTGTCGACTACTGAGGCAGAATACATGGCAGTAACAGAAGCTATAAAGAAGCC
ATCTGCTTCAAGGTCGCTTGATAACTTGGGTCCCCACAAGACCATGTGGATGTTCATTGTGACAGTCAGAGTGCTATT
ATTTAGCAAAGAATCAAGTCATCATGCACGTACGAAACACATTGACGTAAGGTTCCATTTTGTTCGTGAGATTATTGA
AGAGGGAGATATTCTTCTTCAGAAGATTGGGACTGCTGACAATCCGGCGGATATGTTGACAAAGCCAGTTTCGTTGCT
CAAGTTTAAGCACTGCTTAGACTTAATTGGCATTTGTAAAATTTGTTGATTGCCCCATAGGGGATTGGGAGACGACTA
TTGGGAGTTCTACTTCGAGCGTTTGAGTCAAGGTGGAGATTGTTGATTATTGCCTCAAACCAATAGTCAAAAGTGGTA
GGCTATTGTTGAAGTTGCAATGTGAATGCATTAATTGGCTTTCACAAATGGTGGTAGGCTATTGTTGACTTTGCCTAT
GTGAATGCATGGTGGTAGGCTATTGTTGACTTTGCCTATGTGAATGAATGGTGGTAGGCTATTGTTGACTTTGCCTAT
GTGAATGCATGGTGGTAGGCTATTGTTGACTTTGCCTATGTGAATGCATGGTGGTAGGCTATTGTTGACTTTGCCTAT
GTGAATTCATGGTGGTAGGCTATTGTTGACTTTGCCTAACCTTTGGCTTCTTTGAGAAGCCACTTCCTTTGGCTATAA
ATTGGAAGCAAATGGTTTCATTTGTAGCATCCAACCAAGAATCCAACCAAGTGTTGAGTAGAAGAGAAAAATAGCAAG
AAAGGCATTTTGCCAAAGAGTGAAACAAATTCTCTCTAGTTGTTCTTTGCTTTGTATCATTGTTTTCTCTTCCTTTGT
GAGTGTGTGAGGTTGGGTGTATTTGGGTCTTTGGGAAATTGAGTGGTAAACACTATTGTATATCTCCATTGATTATAG
TGGAATACTCCATCGTCTCCAAACTGGATGTAGGCAATTGCCGAACCAGTATAAATCTTGGTGTTCTTCTTGTTGTAA
TTCTCTGTTAAATATATATTTTTTTTCCTGCCAGTAGTTGTTTATTTTTCACTCACAGTTGGTTGACGCTTCCGTACA
ACAGGGTGTGGTACAAGGAGTTGAGCTCCTTATTGGTTTCTTATGGTTTTCATCACTCTAAATTATACACTTCTCTTT
TTGTTTATCACGACGGTTCTATTGTGGCTTACTTTCTTGTCTATATCGATGATTTAATTATGACTGGCAGCGACTGGA
AATTCATCACCAAATTTCTTAACACTCTTGCTCAGCACTTCTCTATTAAGGACTTGGGTTTTATCCATCTTTTCCTGG
GTGTTGAAGTTATTCCTATCCGATCTGGCTTGTTCTTATCACAGCACATGTACATCTGGGATCTTCTCATCCGTGCTC
ACATAGAAGGTGCCAAGGATGTTTCAACGCCCTTGTCTACCATTACTGCCCTTGTGCTCAACGATGGTGCTGTTGAAT
ATTTGGATTGCAAGGGAGCAAGAAATGTACTGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG
AGAGCAGAGAGCCTTAGATTGTTCTAACAGAATGCTTACTCTGCATGAACATTGCAGCTGAGCTTATATTCCTTCATG
ACTATTACATGTTCTCTTACATCAGTAGATTCAAATCTAACGGTTTGTAATAGTAAGCCAATGTGAATATGACACATG
GCAATACACAGCTGTCCTAACAGCTGGGAATTCAAAACAGACTCAAGCATTGCACCTAGCATATAAGCACAAGGCACT
CAGCTTAACACAAAGATTAGAACAGATTAAATATAAACTGACTTATAACCTACTAACTAATCAGAAATTAGCTAGACA
GTTTACATTTTAACACTCCTTTCTAAAGTGCTAGCTGATTTCACTCCAAGCATTCTCCTCAAATAGTCAAACCTGTCT
TTGGGAAGTGCTTTGGTGAAGATATCAGCAATCTGCTCTTCTCCCTTGCAGTAGAGCAGTTCAATCACTTCTTCTTGT
ATTGCATCTCTAATAAAATGAAACTTCCTTTTAATATGCTTGCTCCGTTGATGAAAAACTGGATTTTTAGCCATTGCT
ATGGCTGAAGTTGACAGGACCCGACCCAATTTCCACTTTGGAATTCGAGCCAAGTCCTGTGCGTGTCCAACGTCTGGC
GAATGTCGGGCACAAATGACCTTTTTACCATTCTTACTTCAACTTCTCTTTAAATTTCCTTAGACTTCTGCCGAAAAT
TCGGCAGAGTCTCCTCTGTATTTTGACCAATCCCAAAATTTTTCACCTGTCAAACAATCCATAAATTCACACCCAACA
GCCAGAATGTTTCCAGTAATCAACTCAATTCTAATCTCCAAATTTTCAACTGGATATCAGAGCATATTCTCAAGTTCT
CAAGGTTTAAAGGATTTTCTACAATTCTACCTTACTTGGTGGTGCGGAAGCTCTGACTAGCCCGGTGGTGGATCCCGC
GTACCTCTATGGCCTGGGGGCGAAAAACAGTTTGAAAATGTGAGTGGACAAAAATAATGTTCTTCAAAACAATTATCA
TAAACATAATATCCCCCATTGTAAAAAGGAAATTTAGCTAAATAAAACTGAATACGTACTTTCTACGCCAAGTATATT
CAACTCAAGGCATTCTATCTCAGTCATATTCAAACTTTAAAGTTTCATACTAAACCACTGAAATCAAAGCTCTCATAA
AAGTGCTGAAATTAAACGTGTATAAAAAGTTCTATGCTCAAACCTTGCATACTGAACAAAGATCAAAGTATCTATGCT
TGAAAAATCAGAAAAGCTGATTTAAAATAGCTGAAAATCATAATTAAATAAAAGAAACTCAAAATCTTTTGAAAATAC
TACCAGTTCGTACCCCTGTCATTTCCGTCAATTCCCTGGCAGGTCTCGGGCGTCACACAGGCTACCCGAGCCGCAAAC
TGGCGAAATCAGGGGACTATGATCCGCCTGTCCCGCCGGCAGATTCCTCGGTGACACCAAGTCAGCTCGAGTCGCTCT
GGCAGGATGCAGGGGACCGTCGTCAGCCTGATCCGCGATCCTGGCAGGTCTCGGGGACACAGAGTCAGCCGAGCCGCA
ATCCTGGCAGGTCTCGGGACACCAAGTCTGCCGAGCCGCAAATCCTGGCACTCACGGTTCGAGCGTCCCCGAAACTCG
TGAGGCAAAGTCAAGTGCACTGACTGAACTATAATCAGACTGGATGTCCCGTAGACATCGGTCCAACTCTGGGTAATC
ACCAAAGAAAATGGGTACGAGATGGTTTTAAAATAAATTCCTTTAAAAAAGAAATATCTGAATAATAACTGTAAAACT
TAAGTCGTGCTGCGGTCTCAACTGATTCGAAACTCAAACTCTGTTTTTCTAACTGGTAAATAAGCAGCACCAACTTAT
AGAACTATTACTGTAATAATCGTGTTCGGAACCATAATAAAACTTACTCAAGATCAAATAAGGAAATTTACTCGAAGA
AACTCATTTATCAAAACTCTCTTATATAAATCAAAGTAAAATCACTTATAAACTTATTTATATAAAATCGAATCAAAT
CATCCATAAAATCTGATTTACGAAAGAATATCCACTCACAGATGGTCCGAGCTACTTCGACCCCTCGAAGGTTTCTTT
TACACTTCTGCCGAGCTCCTGGTGCCTGATTATCCCGAAAGATTAAATTAATAAACTGCTGAATAAAACGAAATTCAA
CTAAACACCCTGCCCCCAGCTCCTAGAAATACAAACACTTATTCCAGTTATTCCTATCCCCGCCTCAGCTTTTTAAAT
AGTTAGGCCGGCCTCAAGAGACCCAGAACCTCGATAAGCGATGAGTTGCTCGATCGGCCGATCCGGGACCCCGTGGGT
CCACGGTCTCCGATGGCCAATCTGAGCTTCCCGGAAAGTTTCTCATAGGGCGGGAACAAAGTTCTGCGAAATTGGTCC
GAATCGGACGGTCGGATTGGCCAAAATCGCGTTATCGCTTAAAACCCTAACCCTATCCCCAGGGTTCGCGATTCCGGA
GTATCCGGGACTCCGATTCGCGATCCGTCGAATCCTACGCGATCCTGAAATCACGTAGACCGACATATCCAAAATTCA
ACGCGATCCAACGATCACACGACATTGCACCCACGGACCGCGCGATATGGAAAATCCGTTCGGGGCTCAAACGGACTC
CGAATCGGGATCCGTGAAATCTCACATGCTCGTGACGACATGAGGACCTCAAAACTGGCCAGAGCCGTGCCACCAGCC
TGCCCCACGCGCCGCCACACGCGCGGGGCAGAGCGGGTGTCCAAAGCGATTCGGGTGTGGCGAAAAATCGTGGAACCG
AGACTCCAAACTCCTATCCTAGGTAAAACACCCCATTTGGAGTCACTTTTGTTCTTGGACAACCCCCAAAAAGTGACC
GGAAACAGTAGTTTCGAAGGGCCGAAGTTCGGCCAAATTTTCAAGTTCAAAATCGAACCCCTTAGAGCTAAAATAGAT
CGAAGCCCATATACCCAACAGCTAGAGCACGAAAAATATCTCAAAAACCATACCTTACTCGATCAATTTGGTGGAGAA
ACGAGGAAGAATTTCAAGCTGGAAGTTCGGGTAGCTTCGAACGAACCTCCGTCGGAAAACACGAGTTTCCGGCCATCT
CAGAGCGGTCCCGGGGTTGATGTTGGTTGGAAAAGGCAGGGACTCGATGGCGGTTCCAACGCCACCGGTCCCGTGGCC
ATTGGAGCTCGGAGGCGGCGCCAGCACCCTCTGGAAGTCGGTGGCCCGTTTCGCGCAGAGTCTGGGTTTATATAGATG
CAACTTCGAAATATTTACGGTTATGCCACTGAGACTCTTTTGACCATAACTTTTTCGTTACAACTCCGATTCGGGCCC
ACTCCGTGTCTACGGACTCCTTTCGCCGTGCTCTACGCAATGGCATAAGCGGAATTTCCAAATTATTTCTCGATAAAA
AAGTCAAATTTTCCCCATTAAAAAAATGCAAGGGCAATTTGGTCTTTTCGCTAAAAGATATTTTCTTTACTTTTTAGA
TATTTTCTTTCTTTTTAGATATTTTATTTTGGGTTCTTACAGAAGTGTTGTCACAAAACACAGTTGTTGCAGTGGTCT
GTTCTTCCCCAAAATCTTCAAGAACAAACCTGAGCCAAATGGCTTGTGATGTAGCTTCTGCTGCACTCACATACTCTA
CTTCTGCAGTAGAAAGAGCCACACTGTGTTGTTTGACTGATGCCCACGAAAAAGCACCACTTCCAAATGAAAACGCAT
ATCCAGAAGTGCTTTTCATATCTTCCTCAGATCCACTCCAGTCACTGTCACAGTAACCAACTAAGAGTGCAGATTTTC
CAGTCACATACTCAATTCCATAGTCAATTGTGCCTTGTATGTACCTTAGAACCCTTTTAGCTGCCCCATAGTGCATCT
TAGAAGGGTTGTGCATGAATCTTGCAAGCAGGCAGGCAGAGAACATGATATCTGGCCTAGTTGCAGTAAGGTACAGCA
GGCTGCCTACAATTTTTCTGAACAAACTTTCATCTGCAGCATCACTTCCATCCTCTCTTTTCAATTTATCAGTAGCCA
CTAATGGAGTGCTTATTGACTTGCAGTCTTTGAGTCCAAACTTATCCAGGAGAGTGAGAGCATACTTCTTTTGATGAA
TGAAGATGCTCCCTTCAGTTTGTGTTACTCCCATACCAAGAAAATGGTGGAGTAAACCCAAGTCAGACATCTCATACT
TGTACATCATTTCAGCTTTGAATTCTTTCATCATTTCATCACTACTTCCTGTGTACACTATGTCATCTACATAGATTG
ACACTATTAGTGTTCCCACACCTTCCTTTGTTCTCACATAGAGAGTGGCTTCACTTGGACTTTTGTGAAAACCACACT
GATTCAAGTAGGTGTCGATTTCACTATACCAGGCCCTTGGAGCCTGCTTCAACCCATAGAGAGCTTTTCTTAACCTAT
ACACCTTATCCTCATCACCTTTAACCATAAAACCATCCGGTTGATCAACATAAACTTCTTCTTCAAGGACACCATTTA
AGAAGGCTGACTTGACATCCAATTGCCATAGTTTCCAGCCTTTCTGAGCAGCAAGAGCTATGAGAGTTCTAATGGTGT
CTAACCTTGCCACAGGAGCAAAGGTTTCATTGAAATCAATCCCTGGTTTTTGTGTGTATCCCTTGGCAACAAGTCTTG
CTTTATGTTTTTGAATGGAGCCATCAAGATTAAGCTTAATTTTGAATATCCACTTCACTCCCACAATTGGTTTACTAC
TTGGCCTATCAACCAATTCCCAAGTGGAGTTTTTCTCTATCATAAGTATCTCCTCAGTCATAGCCTTCCCCCAAGCTT
CATCTTTGACTGCTTCTTCAAAATTTTCAGGCTCAATGATGCTCATCTTGCATTGAGCATACACTTCACTCAAACTCT
TCCATTTCTTTGGGGTGTTATCATAAGTTTCAAATGGAGCAGAGTCTTGAGTAGCATGCAAATCACTACTTGTGTGTG
TTTCCATAGGAGACAACACAATCTGTTGCCGTAACAGATTTAGTTCTGAATCCAAATCTGATACTGTAGAACTTGCTC
CATCACCCCAAGACATAGGGCATTTGCAATGCCTCATTTGATTCCCAATTCCACATTGCTTCTTCATAAAAAATAACA
CTCCTAGACAGCTCAATCTTTTGAGTTTTCAAGTTGAGTACTCTATACCCCTTTTCACATACACCATATCCTACAAAT
ACTCCCTTCCCACCTGTGTCTTCCAGCGTGTGCCTTTTCTGTGTGGGGATGTGAATATAGCATAGAGAACCAAATATT
CTCAAATGCTTGACACCTGGTTTTCTTCCACTAAACTTTTCAAATGGAGTGGAATTGTCCACTGCACTTGTAGGGCAT
CTGTTTTGTAGATATACAGCTGTATTGACAGCTTCTGCCCAAAATTTCAAAGGGTTTTTCTTCTCATGCATCATGGCT
CTTGCCATTTCCATCACAATACAATTCTTTCTCTCTGCAACTCCATTCTGTTGTGGAGAGTAGCCTACTGTCAGTTGC
CTTTCTAATCCCATCTCTTCACAGAACTTTGAGAAATCCAAAGATGTGTATTCTCCACCTCTATCACTTCTTAGCTTC
TTAATTTGATAACCACTTTGTAGCTCAACCATGCTTTTGAACCTTTTGAATATGTTGAATGCTTGAGACTTATGCTGC
AAGAAGAACACCCAACACATTCTGGTGTGGTCATCAATGAAGGTGAGGAAATATCTGTTCCCTCCAAGAGTGATGGTC
TGCATTGGACCACATATGTCTGAGTGAATCAGTTCTAGTGGTTGAGAGGCTCTCCAAGCTCCTTCCTTATCAAAAGAG
CTTCTGTGGTTCTTGCTTACAGCACAACCAGAGCAGACCTTCTCATGTTCTTGTAAATTAGGCAGTCCCTGAACCATA
TCTCTCTCTTGTAACAACTTCAAACTAATATAGTTTAGGTGCCCAAATCTTCTGTGCCACAGCCAGGATGTTTCTCCA
ACTGTTGCTCTGTTTGCCATAGGAGGATTGACATATTCAAGATTTAAAGGAAAACATCTGTTTCCCTTCATTGGCACT
CTTGCAATGCAATCTTCCAGCTGCCTATCTCCATAGATATCAACTGCATTATCACCAAATACAAGCCAATGCCCATGT
TCTATCATTTGACCTACACTTAGCAAATTTTCATATAAACCTGGTACAATCATGACTTATTTGATATATCTAGTCACA
CCCTTCATTTCTATAGCCAAAGTCCCTTTGCCTATTGACTGCACTAGATCACCAGTCCCCATTTTGACTTTACTCTTC
ACACTTTTATCAACATTTATAAGTAATGACTCATGGGAAGTCATGTGATTGCTACATGCACTATCAACATACCACATA
TTCACATTCTTCCAATTGTTGCAGCATGACATGCATAGAACATAATGGCAGGTTCAGTTACCTGATTTGCAATGTTAG
CAAGTTTCCCTGCCTTGTTTGCTTGGTCACAGTCCTTGACAAAATGACCAAATCGATTGCAGCCATGGCACTTTGGTT
TTCCTTTAAACCAACACTCACCATAGTGTAGCTTCTCACAATGTTTGCATTTTCCAGATTTGTCTCCCTGACTCGGTT
TTCCCCCTTGATTGGCACTGTTTTGAGGTTTAGAATCCCATTTCTTATCCTTGGACTTCCAGCTTTTCTTTGATTTAT
TAGTGCCAGAACTAGAACTTGACTGAGATCCTTTTGAGTTTATGCTCATACTGCTGAAAGCTTTCTCAGTGGTGCTTT
CAGCATGTCTGTCAAGACGCTGAGCAAATCCTCTTAATGCTGCAATTACCTCCTGCACTTCAATGGTTTCAATGTCCC
TAGTTTGCTCAATCACATAGCAGACTGGATCAAACTCCTTGGTTAAGCTTATTAGCAGTTTTTGAACTATCCTCCCTT
TGGTCAGATCTTCCCCATATCCCTTCATTTGATTTACAAGTTCAAGTAGCCGAGTGATGTAGCCAGACAAGATCTCAT
CATCCCTCATCCTGGTGTACTCGAAATCTCGACGCAGACCCTGCAACATGATGGATCTGACTTGCTTATCACCATGAA
ACTCCTGATGCAAGATATCCCAAGCACCTTTTGAGGTTTCTTCATTTGAGATTCTAGGGAAGATATCATCTGAAACAG
CACCTTGGATAATACCAAGAGCCTTAGCATCCTTCATCAACAAGGACACCATCTCTGAATCTGATGACCCTTCTTTAT
CTACTTTTGAATCTGGAACCTGAAGACCTTTCTCAACCAAATTCCAGATTCCATGAGATTTGAAAATTGTTCTCATTC
GAATCTTCCAAAACTCATAGTTCTCCCCATTGAATATTGGAGCTCTAAGATCACTCCCTCCTGACCCAGCCATCTGAG
ACCAGACTCAATGAGCTGAGAGTTGGAAATTTCTCGTTGGATTTCCAGACTCAGTTCCCACAGCTTCAACGCCCTCTA
TCCAAATCCAACTTGCGCACCTGATACCATGTTGAATATTTGGATTGCAAAGGGAGCAAGAAATGTACTAGAGAGAGA
GATAGCACAGAGAGCCTTAGATTGTTCTAACAGAATGCTTACTCTGCATGAACATTGCAGCTGAGCTTATATTCCTTC
ATGACTATTACATGTTCTCTTACATCAGTAGATTCAAATCTAACGGTTTGTAATAGTAAGCCAATGTGAATATGACAC
ATGGCAATACACAGCTGTCCTAACAGCTGGGAATTCAAAACAGACTCAAGCATTGCACCTGGCATATAAGCACAAGGC
ACTCAGCTTAACACAAAGATTAGAACAGATTAAATATAAACTGACTTATAACCTACTAACTAATCAGAAATTAGCTAG
ACAGTTACATTTTAACAGGTGCAACCCCAACCGATGCCACTTTATTTTCGCAGTCTTATTAATGGTCTCTAATATCTT
AGTTTTACACATCCAAACATTGCCTTTGCAATCAACAAACTCTCTCAATTCATGCACCGGCCTTCTGAACTCCATTGG
GCTGATCTCAAATGCCTGTCCGCTATCTCAAACGCACCATTTATCATGGTCTTCATCTTCATCGCAACACCATTTTCT
CTCTTTCCATGCCTTCTCTGATGCGGATTAGGCCGGCAATCCTGACGATCGCACATCCACCACTGCTTATACCATTTT
TCTTGGTGGCAATTTGATCTCATGGAGTTCCTGCAAACAACACTTTGTTGCTCGCTCCTTTACTGAAGCCGAGTATCG
TGCTGTTGCTTGCACTGCTGCCGAGCTCTCATGGTTACAGAATTTACTTCGTGAACTGGGTGTTTCGCGTCCTTCACC
CCCTGTTATTGCCTACGACAACATTGGTGCTACCTTTTTCTGTGCAAATCATGTTCTCCATTCCCACATGAAACACAT
TGCCATTGATTTTCACTTTGTTCGTGATCTTGTCGCTCAAGGCCTTCTAAAGGTGGCTCATGTTTCCACTATTGATCA
GTTAGACGATGCCTTGACTAAACCTCTTTCTCGCCAGCGCTTCCATTTACTTTGTTCAAAGATTGGAGTCACCGACGG
CGGCTCCATTTTGCGAGGGCGTATAAGGGAAGTTGTAATTTCTCCTCCACTACAGCTATATCATAATCAAATAGAATA
GTTGTTTGCTATTAGTTTACTTTCCTTGTATGTATTATTGACTTAGAGTATTCAATTGTAATTTATTTTCTTTCCTTC
TTAGATACAGAAATCTTGGTGTATATGTAAAGGGATTTGCCCACTCAATGCCATCATTGGCCTTCTTCGTTTTCGATG
AAAAACAAACAAAATCTCTATCTCTGAAAACATTTTCCCTCCCCCTCCCTTCGTTGAGCCTTTCCTTTAATGGTTGGG
GAAAGCATTCCCTTATTTGAACTTGGCGGGCATTCCGCCTTAGTAAAAAAAATATAAAAAAACAGGGCAGTTTGAACA
TAGGCTCAAACATGATTTGGGCAACTAAGGACGAGATTACCATAGGCTTTTATGTACCTAGTGTTCTCCTTTAATAAG
GTCGCCTTGTATCGAGCTGGGCTCTTCACCATATAACCTTTACCCGAAAAACTGGAGCACAACTATTACTTTCATCGC
TTTCACTATAACTAGAGTCATATGGGCACTTTTTTGTTTTGCCTTAAGTTCAGGAGGAAGGACTCCCTATGTTTTTTC
ATGGAGCGTAGAATTTGCCTTCATCCAAGTATCAAATCCACCTTCGTACCTCAAAGGCGTGCCTAAATCTATCCCACT
TCCACTCACACCAACTCTTGCTCCTGATTCAACTACTTTGAAAAGTACTTCCATATCCTCCATTTCATCCAAGTTCGG
ATTTTGAACCCCAACGACAAATGAACTACGGGCGGGGCATTTTCGGAGAGTAGCCTACTTCTTTCTTACTTCCAATTG
TTCGGTCTGATCGGCATGAAATTGATATTGAAAGGGTTGATTGTGTTAGGTATTGTATTGGATCTAATAAGCTCTATT
AGATCTTAAAATTAGGGATAATTATTTAATTCATTGACAACGATGATGAAGTTTCCTGGTTGCAACAATTTATGATGT
AGCACGGGTTTACAAATCAACAAACGCCTAAACCCGAACAGATAAACTGAAATCCATCAGCGATTAGAATCCACTAGG
AAAATAGAGAATCTCTAAACTTGATTAATAATATGATTAAACTGATTAATACAATGTCATGAGTTGGCTTAAATAGAA
AACAAAGAAACCTTAGGTTCCAAAATATTCCTAAAACTTAACTAAAAAGAAAATAATTTAAATCCTAATTAAAATCAT
GTCAGGAAAATAATATATTGATTGATAACTTATTCTAGAAATATAAATATAATATAGATCTTCTCAAGAAATCAAGCA
ACCCGAAAATCCTAACGATACACCTTCCTTCTTTTCCTAATGCCATAATTGATGTTCAAGCATGATTTTCCATATTTG
AAGCCCAATTTTCTGATTTTGAAAATTTCGCCTTTTTTAAATTTCCTTCGTAGGAACAAACCCATGATTTGTCATACA
TCAGACCCCTTCACTTGTAAAGAACTCGACCTTGAATTTTCCTTGAATTGAACTTGGGTAGACATAGAATTTGATGTG
TGAATAAACTCTTCAATTCTTGGAGTCCAAACTTGCTCATACTTGGATGGAATAATCATACAATTAATTCCATAAACA
AGATTAGAATATGCCAGTTGATAATCAAACTCCTTGAATAAATGTGTTTCCTCCTCATATTCGGATTTATTCGTATCT
TCAATTTTCCCCTCTGTCTTGTGGGTTACTAGATCATCAACTAATTCAACCTCCATTACAATTTCTTCTTCTTTGATC
TCTTCCTCCATCTTTTATTGGCTCGCCATAATTTTGGGTTGATCAATCTTGTAACCATTCTTTGACAAATATAAATCA
TATTTAAAATGAAATTTTTTTCCACAGGAAGTCTCTTCATTCTACGCTAAGAAGCGATATGATTTTTACCTTGTTGCT
TCATAAATTTTAGCATCTAATACCACCAAGAAGCGACATCGCCTCTTAAATGGGGATACAACAATTTTCACCATCTTC
TCTTCTGAAATTGCTATTGTATCAAATATTTCCTCTACATCTGTAACCCATTCGAGAAACCTTTCAATGCAGCCAGTT
CCCATAAAGCATGGAACATCTGCAACATAGGATTGATGAGGTTGGCTTCAGGTAAATCCACTAGCGCGTTCCTCTTCA
ATATTTGATACCATCGTCGATGAGGTTTGCGTATCTCTCATCCTTGCTCATCATTGAGAAGGCAAATCCTTGCTCTGA
ATGATTACCCGCTCTGATACAATTTGATGCAGCATGGAAGCACAGGTTTATGGATTGACAAATGTCTAAACCTAAAAA
GATAAATTGAAATCCATCAGCGATTAGAATCCACCAGGAAAATAGAGAAAATCTCTAAACTTGATTAATAATATGATT
AAACTGATTAATACAATGCCATGAGTTGCTTAAATAGAAAACAAAGAAACCCTAGGTTCCAGAATATTCCTAAAACTT
AACTAATAAGAAAATAATTTAAATCTTAATTGAAATCATATCAGGAAAATAATATCCTGATTGATAACTTATTCTAGA
AATATAAATATAATACAGATCTTCTCATGAAATCAAGCAACTTGAAAATCTCAACGATACGCCTTCCTTATTTTCCAA
ACGCCATAATTGATGTTGAAGCAGTGATTTTCCATATTTAAAACCCAATTTTCTGATTTTCAAATTTTCCCTTTTTTC
AAATTTCCTTCGTAGGAACAAACCTATGATTTGTTCTACAAAGCTATGAGGATTTGGCTTACTCGCAAGCAAGAGGAA
GAGGAAGATGCTGGGTGGCGTAGGGGTAGGGGTTGGGTTGCTGGTATATTCTCTCTTTTTTCCTTAAGTTTTTTATTT
TTCTAATTTTATTTCAGTGGATAAAAATAAGTCTAGCTATAAAGTAAAGTTTGAGTTGTTAAAAAATTAAGACACATG
ACATATTTTGAGTAGGAGTATCACCAGCTGACATGGTGATTCGAAACCATTCTATAATTTCTCCAAAAGGTGACAATT
AGATTAGTTTTTGGGATTTACTTTAGAGATTTTATGCAACTTTAATTTGCATTGATGTCTTATTTTTGTGTTACATAT
AGAGTGCTGCTATTTTCACATATCTATCCTATTTTCTCACCCACCTTATTTTTAAAATTTTTAAAATAAATTTATCTC
TTTGTAAAATAACTTCTAAGGAGCTAAGTTAAAAACTTTTTAAAAGCATTTCAAATAAAAATAAAACAATATTTTTTT
AAAACAAAAACTCTTTGTCCTCTGTCCCCTTTCCTGACCACGTCTTCTGAGCTACTGACGAAGTCTCTCAGCAGCAAC
AGCAACAGCCGCGAGTACTGGCTCGTCGGCGGAGCAATTTCGAACTCGGCGGCGAAGTCGAGATCCACGAAGTACCGG
ATCTGCCACGTGGACGAGCTCGATTGGGCGCTGACGATGTCGATGAACTCTTTCTTTCATTATGTTGGATTTGGTGAC
AGCGGTTAAATGAATATGTGTTCCTCCTTTCCTCCTTTGTTTTTTTTATAAAAAAAAAAATTTCTTTTGTGTGGTCTC
TTTTTTTGTTGGTAGTGGTTGCAATTTTTTTATTAAAATAAAAATAAAAATCAAGTGTTGTGGATGCCATATCCACCC
TTTTAATACAATCATTTCTCTTTATGATAAAATAAAAAAATAAAAAAAACTCACTTGGTGTATGAGATTAAAGCCTCT
CTCTCTGCTTCTTTACTATTTCTTCTTTCTATATTTTTGTTTCTGTTTTTTTTTTTCTCTTCTGAATTTGTGGTGAAT
TAGTATTTTATTGATATTAGACTAGAGGTGAATTCGTAAGGTGGGTGCAGATGAATTCGCAAGAGTTTTGTGTAGAGG
TGAATTCGCCTTTTTTTTTTTGTATTAATCGTGCTTCGTCTTATAGCTCCCAGCAGCAGAGATTGAAGAAGCTCTGCA
CAAATAACTAAGGTTTTTTTAGGATTTTGCTCAAGCCATGGTGGAGGAGGGTGAAGAGGTAGGGGAGGGGTTGACGGC
TAATGTAGTGTTGCTGAGGGGGTGGGGCTGCGTCGGGAAGGAGGGAGAGAGACTTTTGTTTTTATTTTTTATTTTTTA
AAATGTTATTTTATTATTAATTTACTTTAATAATTTAAGGGTATTTTAGGAATAATGGTGGGTGGAAAGATAAGATTT
TGTTTTTTTTTAAAAAATTTATATGGTGAGTGGGAAAATAAGGTGGGTGAGGAAATAGGACAAGGGGGTGGAAATAGC
AGCACTCTAGATATATTAGCTGACCCTAATTCAATTACGCCAAGTTAATTTTATTTTAATATACTTTTATGAATAATG
CTTCTCTTACCACATTCTCATACCACATGTTGAGGCCTAAAAATACAGGGTTATGCCCAAATAAATTCTCGGCCCAAC
GCAATGCCTTATTAAGAAAAGACCCGGTTTGGAGAACGCAAAAATTCGTCATGCATGCTTGCACGAGCTACGACCACA
TGTCATGCCAAATAAAATATGCAATCCATCATGCTAAGAATAAAAATGAGCCTATAAAAGGCACTTGCTCTACAAGCC
CATGCTAATTATTCCGTCAAGCATTATGTCTCTTTCCAAAGATGATAAAATTCAAGCACGCCAATTGACATGTCATGC
CAAGCAGGAAATCATTATTTCACACCTAGCCACATTACAAGCATAAGTGGGCTCAAGCCACGCAAATGCCCAGGCTCG
CTTGAGTGGGTTGTGGTATGGATGGTAACAAACTTTCATGAGGCCCATTGATGAGCCGAGAAATGGAAGTTTTGGGCT
GCTTGGGAGCCCCAAAACTCAAGCCCATTTCTTGAGCCTAAATATGTGGGTAAGCATAAAAGAGAGGAAAAAGCCCAA
ATACCCTAGAAAATTAGCCCATCACTTAAGGAAATTAGCCCATGTCCTTAATGGGCTAACTCATCACTTTAGCAAGGC
CCAAGAAAGCTATAGTCTCCAGCGCTTAGCTGAAACATGAACCACGATGAAAAGCTAAAATGTCTATGTCCGTAAGCT
GCTGGGAGGCTCTAGCACATGGGCAAAAACAAACCTCAAGGCAGATCCTTCAAGAAACCAGAGGATATTGACGCGCGC
AAGAGAAAAGGCAGACTTTAGACCAGCCAAAGTTATCTATCTCCTTCCTTTACTAGACCTTGCCATGAAATAGGGGAG
GAAATGAGGAGAGATGCTAGCCAAAAAATAAGAAATCACCACTGAAACAGCTAAAGTCTAGAGCTCCCAAGACCCTAT
TTTTGTGCAATTGGGCAGAGAGAATTTCACCAAATAGGATGAGTCAAAGGAAGAGAAGAGAAAGATGAGGAAAGACTT
GGCCAAATTGGATAGAAACTATTAGGGTTTCTTAGGAAGAAGGAGCTTCCAACGCCTATAAAAGGAAGCTTCTTCTAC
CCAGCAAAACCATCATCTAGAGTGCGACCAAGCTTTGTCAAGCAACTGGAAATTCACTCAAATCACATCCAGAGAGCA
AGCTTCATCTCTCATCCCAGAAACCTTTGCAATTTCGAGCCCTAATTCCTCAATCTCTTCCATTTTCTCTTATGGTAA
GCCATTCTAGAGCCTGACAAAGCTTTTTTCAGGCCGTTGGAAACTACTCAACACACCCATTATACCCCCATCTCTCTC
TCTTCAACAAACCCTTTTAGAATCCTTTCCCCCATTTCCTTAGAACCCATGTCTTTCATAAGAACTCACAGCTCTCTC
TCTGTTTATGCTAAACTCATGATTGTTTTGCTCACACGCCACAAGCTTCTCATGCCAAGCTAAGAATCTATCTGTAAG
CCATTGTTGTTTTTGCTAGTGAAGACAACCAAGATGCTTCCTAAGGCTTCACTACCCTTTCGAAGCATTCTTTGGGCC
TGATTCTTGAACTTAGGCACATAAGTTAATTTCACCTATTTCTCTTTTCGGCAGCCCAAGCTCATTCATCAGGCTGCT
GGAATAAAAAGACCCCCGCATTATGTGGCAAATGAGGTGGACAACATGAGGTGGGCAACATACGGCGGACAACCACAT
CAATTATTTTTTTTTCTTTTATGATTTCTTAACACTTAAAAAAAAAACTGTTAATTAAACTTTCTTTATTAAAATACA
CTTCATTGATTTAACTGATGTGACATATGACATGGACATGCCACCTCATATGATATAAAAATATAGCATAAAATTATG
GTAAGTGTAGCATTACTCTAATTTTATTATTTTACTCATGCAAATTTGGGAAAATGAATAACGTAAACTAACTTGCAA
TTTAATGTAAGAATGTAAGGTGGTTAATGTAATAATATAGTATATATTTTCTCAGAATCTGGAGGATGCTTGACATTT
CTTTTTTATTCTAGGTATCTTTAGCAGTAACTCTCCGTTTAGATGATGAAAAATAACTAGTAATTTAGCTAAAAGTCA
GATTTTTTTTTTTTTGGGTCAACGAAAAAGCTAAAAGTCAGGTTTTTAGTAGGAGAAAATTGACAATTTCCTTGTTTG
GTAACTTACTTAAGTGTGAAATTTATTAAATGACGCATGAAAAAAATCGTTGAAATTGGGGTATCAAATTCCCGCGTT
TAATTTTCACCAAAATAGTTGTCCTTTCAAAATTTTCATAGTGCCATTTATAAAATTCGATATGCATAAATCCAAACA
CTGAAATATTTAATTGCCATAAATTGAAATGATGGGAATCTAAATTCCGTCATTGTAGAATTTTATGTACTTTTCAAT
TCCTTCATCCAAACAAATGGTAAGTTATTTACTCAATATTTGTTTAAAATAAATTTTCCATCTTCTTTTGTAGATTTC
TTGTTATGGGTTTGTTGAGGATTTAGAGAATGAAGATTAGAATCTTAGATTGTGAACTAATGCTACTAATAATTTGTC
CGCAAAATTGCAGCAGTTTGTCATGAACCTCATATGCCACATTTGAGTCTCCTTTATGCGAACCTGACAGAGGAAGAA
CGGATGAGAGCTCAAGAAAAAGTTACAAGTTTGGATGAGAGCATTACTAGCTAGCCTCAGCTTCCCAATAAATCGTTT
TGAGTTGTACAAAACCAACAACGTAGGTAGAGATCAACAATCTTGGGAGAAGGTTCTTGAATACACCGTCCCACTTTT
TCGACTCGGGTGGGCTAGGCTACAGTTCAGTTCAAATGTTGAAAAAAAAAAATTAAGAGTTTATTGCTAATTGTTAGT
AAGTTCACCTATGTTTATGTTGAGAGTGTTTGTCTCACATTGAAAAGTTAAGGGACTTAGCCTGGGTTTATAAGGAGT
TGGACTACTCTCCCCATAGCCAATTGATTTTGGAGTGGAACCTCAACTTCCTTCATAGTATCAAATCAAGGCTTCATG
TGTTGGGCTCAACGGCCACACGTACTCCCACGCCACCCAAAATGTGTTATCCACATGTTAGGCTTGAAAATTTGCCAC
GCATACGGAAGCGTGTTGAGAATGTTTGTCCCACATTGAAAAGTTAAGGGACTTAGCCTGGATTTATAAGGAGTTGGG
CTACTCTTCCTATTGTCAATTGATTTTGAAATGTAACCTCAACTTCCTCTTATTGTCCCACTCTACCTCCCTGTCTTC
TCTTGCCTGATGAACTAGTTAACAGGTTGATGTTTTATTGTAAGATGAAAGGCTAAAATCTCTCACATATGTTGATCC
AGTTAACTAATACATTTGGTGTTGGATCGGACTAAGAAGCTGGATTGTAAAAATAGTGAAGACCTATGTTTGGAGTTG
TGTCGGACTAAAAATAATTATTTTAATATTTAATTTTAATTAATAAATTCTAATATTTAATTTTAATTAGGGCTTTTT
TTACCTAAAAATAAATAAAAAGAAAACAAATAAGTGAGTATGTGGTGGTTTATTATCTTATCTCTAGTTAAACAAACA
ATTGAACCACGCACTTCAAACTATATTATCTTCTTCTTAATTTTTTTTTTTTCTTTCTTCCTCTTCTACCCATTAACT
TTTCTTCTTCTTCCTTATCTCAGGCCCGTTTCTTTCTTCTTCCTTTCTTATTCCTTCCAAAGCTTTTTTTTTTTTTTT
TTCTTTCTTCATTTCCAGACTGTTCCTTCTATTTCTTTTTTTCTTCCTATTCTTTCCTCTCTTTTCTTCTTCCTTCAT
TCCTTTTCACTCTCTCTTCATGCTGCACCCCAACTTTTAAGAGAGCCATATCCACTTCTGGATATGTGGTGGCTGCAA
ACACCCACCCCTCTCTCTTTCTAGTTCCACTAATTAATGGTTGTGGTGGTTTAATTAGGTGATGATGGTTGTTGAACT
GAGTATGTGGTGGCTGTTTATGGGTGGTGATGATGCTTTGTTTGACTAATTGGGTGGTGATGATGGTTCGATTGGGTC
TTTGGCGGCTGGTTATGGGTTTGATGGTGGTGGTCTGACAGAGATGGCGAAGAGAGATGGTTCTGGGTTTTGCGAGTG
GCTGTGGTGGCGAAGAGAGATGGGTCTGTGTGTGGCTTACGGGTGGTGGTTATGAGGGAGAACAAATTCGGGGGAGAA
GAGGGAGAGCTGGGCATTGCCAGAGTCTGTCGATTGGGTTTGTGGTGGTGGTGTTTTGATTCAAGGCGTAAGGAAATC
CAACCGGACTCGTGTGTTCAAAATAGCGATGGTGCTATTTTGCGAACTGCATTTGGGGCTCACTAAATTAGACATGCG
AGTCCGGTTATTTTTTCACTGTTGGACTATGCAGTCTCATTTAAGTTAATTCCCTTTCTTACCAAACATGGATTTTAA
GTGTTATTTAACACAATCCAGTCCAGTAAAGCATAATGAAGCCTACCAAACATGACCTAATGGAGCACCCTCACATGA
CCTCTCAAAACTAATGGAGCTCCAAGTGCGAATATAAAACCAAAAATATAAGGTAAAGGGCCCACCTGCAAATTCTAT
ATTGAAGGTCCAATGAACTTGTATAAACCATAGACAAACAAACATTGGAAGATTGTGCTCACTTCCTATAACAACATG
CCTCTCATAGATTGTGCTCACAAACATTGGAAGAAATTCAAAGATGCAAAGGCCGAAAGTACAAAAACCCTATTACTC
AACACACCCAACCACAATATAGGAAATATAATACTTGCTCAACATACCTTAGCACATAAATTCAAAATTTCTTATTTC
TTTAAAACTTAGAAAAGTCGTACAACTTTGGTAAATAAAAAATATCATGACATGATTGATTTCATAGAACAACAACCA
TGTTTACGATATCAATAATGCTAACGGCACCAATTATGTCAAATTTCAAGTTTTATAATAACTAAGGTGGCTAATATA
TATTACGAGAGACCTTGTTACAAATTAGGGGTCAAGAAAGTTTAAAATGAATAATAGATGCGTAATGCGATATATTCA
TACAGAAAACTAAACAAGAATGTAGAGGTCACGTCCTCAATGGTCAACATCATTGGTGATGACTGAGGACCCAAGAAC
ATTATCCACGTGTACTACGTTGCTATCATGCGCCGGTCTATGTTCTTGGCGCACTTGGTCGTCCAACTTTGAAGGTTT
CAACAAAACTGAGATCTACATGGCACTGCGAGAAAAATTTAGGGGGAAGTAGAAAAATAGAAAAAAAGATAAAGAAAC
ATTCAAGCCAAAAATTTGCCAACCCATCTCTATCTATCCCATCATTCGCTTCCTTCCTCAATTTCCTTTTGTTGCTTC
TCCTTGGAATCCAAAGCTTTAATCTTACCTCCTCCTCAGTTGGCCATCTCTCTCTGTTCTCATTTTCTGTTTTTTTCT
TTTTCAACTTTTGCTGCCAATAAATTATTGGCTTTCCTTTATTGACCCACTTCATCTTTCTTCTTCTTCTATCTATAA
AGTTGAATTCTTGATTAATCTCTCTGGATTTGGAAGCTACCCATTTCCCAAATCTCTATCGTTCTTCTCCAATTTTTG
ACAATTTCAATCTGGGTTCTTTGGAGATTTGGTGCATCGTTTGGAGCAGAAGAGGCAGAGGAGATGATGATGATGACA
ATGGAGGGGATGATGGATAAGGGTGTATTGGATGATATAATAAGGAGGCTATTGGAAGGCAAAGGAGGAAAACAAGTG
CAGTTATCAGAGGCAGAGATCCGTCAACTTTGCGTCAACGCCCGCCAAATCTTCCTTTCTCAGCCTAATCTTCTTGAG
GTGCGAGCTCCGGTTCGCATATGTGGTCAGCTCTCTCATCCTCTCTCTCTCTCTCTCTCTCTCACAGTATTTTTCATG
ATCATGATGGTAATTTGAATTGTCCAATTACCAGGATCATTTATTCTTTTGTGCTTTCATGCTTCTGGATGATTATGT
AAAAGATTGGTTTTGAATAAGAATGATGTCGGAATTGATAATTGGATTAAATTGGGATGTAACAATTTTGCATTTCTC
ATGCCCTGTATTCGATAATGAACTTTTGGAGTATTCTGTTTGAATTTTTGAGAAAAATATGATCGTTCTTATGCTATG
TTCATTAGATGAATTGGAAATCTATTTGAGTGATCAACATGTGGCATTGTATGTCATTTTGTTCATTAGATGCAATTT
CTGTCTAATAATGTTCATTTTCTGCTCAACAAAGAACATGAAAGGCAAAGAAATAACTCTATTTCGTAATGGCCAGTT
TTTTTTTAATTTTGTAAAAGCTTTTGAAAACAACTTGATTTGGATGTTCCTTTGCTGCATTTTGAGTACTTGATACCA
TTTTGTTTTCTTGGTCCTCTTGTTGTACATCATGGGACAGTGTATCAATGATGCTCTAATGTAGCTTGCGTCAAATAC
AGGGCAGAAATGATAGTTGAAAGAAAACATAACAATTATCTCCTTATATTTCTCTCTGTCCTTGGTGTTCCTAATATT
GCAGGCGTCTTACAGGTGATATACATGGACAATACCAAGACCTGCTAAGGCTATTTGAATATGGTGGTTACCCTCCTT
CTGCAACCTACCTGTTTCTCGGAGATTATGTGGATCGAGGCAAGCAAAGTTTGGAGACAATATGTTTGCTTCTGGCGT
ATAAAATAAGATATCCTGACAAAATTTTCCTTTTGAGAGGAAACCATGAAGATGCAAAGATTAATCGAATATACGGGT
TCTATGATGAGTGTAAAAGGAGATTTAATGTTAGGCTTTGGAAAATATTTACTGAGTGCTTTAATTGTTTGCCTGTCG
CTGCACTTATTGATGAGAAGATACTTTGTATGCATGGGGGGCTGTCACCGGAGTTGGAAAATTTGGATCAAATAAAGG
AACTTCAAAGGCCAACTGACATTCCAGATAATGGTCTTTTATGCGATCTGCTTTGGTCTGATCCTGATGCTAGGATTG
AGGGCTGGGCAGAGAGTGATCGAGGTGTTTCCTGCACTATTGGAGCTGATAAAGTTATTGAGG"
      },
      annot {
        {
          data ftable {
            {
              data gene {
                locus "SLF7"
              },
              partial TRUE,
              location int {
                from 0,
                to 1012,
                strand plus,
                id local str "S7_haplotype",
                fuzz-from lim lt
              }
            },
            {
              data imp {
                key "exon"
              },
              partial TRUE,
              location int {
                from 0,
                to 1012,
                strand plus,
                id local str "S7_haplotype",
                fuzz-from lim lt
              }
            },
            {
              data gene {
                locus "S7-RNase"
              },
              location int {
                from 7628,
                to 10179,
                strand plus,
                id genbank {
                  accession "MH029536"
                }
              }
            },
            {
              data imp {
                key "exon"
              },
              location int {
                from 7628,
                to 7756,
                strand plus,
                id genbank {
                  accession "MH029536"
                }
              },
              qual {
                {
                  qual "number",
                  val "1"
                }
              }
            },
            {
              data imp {
                key "exon"
              },
              location int {
                from 8032,
                to 8219,
                strand plus,
                id local str "S7_haplotype"
              },
              qual {
                {
                  qual "number",
                  val "2"
                }
              }
            },
            {
              data imp {
                key "exon"
              },
              location int {
                from 9745,
                to 10179,
                strand plus,
                id local str "S7_haplotype"
              },
              qual {
                {
                  qual "number",
                  val "3"
                }
              }
            },
            {
              data gene {
                locus "SFB7"
              },
              location int {
                from 11708,
                to 13124,
                strand minus,
                id genbank {
                  accession "MH029536"
                }
              }
            },
            {
              data imp {
                key "exon"
              },
              location int {
                from 11708,
                to 12916,
                strand minus,
                id genbank {
                  accession "MH029536"
                }
              },
              qual {
                {
                  qual "number",
                  val "2"
                }
              }
            },
            {
              data imp {
                key "exon"
              },
              location int {
                from 13002,
                to 13124,
                strand minus,
                id local str "S7_haplotype"
              },
              qual {
                {
                  qual "number",
                  val "1"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        local str "S7_haplotype_prot_1",
        general {
          db "TMSMART",
          tag id 90976020
        }
      },
      descr {
        title "F-box protein, partial [Prunus dulcis]",
        molinfo {
          biomol peptide,
          completeness no-left
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "LocalId",
              data str "S7_haplotype_prot_1"
            },
            {
              label str "General",
              data str "gnl|TMSMART|90976020"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 325,
        seq-data iupacaa "DDEHNLNFVVEDIKFPLSSGQFIGLEDVESPSILGHCNGIVCLSPCSDNLVL
CNPAIKEIKLLPKSGLPDWWGCAVGFGYDPKSKDYKVSRIASYQVEIDGLIPPPRVEIYSLSTDSWREIKNNSLETDT
TCFFPDYFQMYFQGICYWVGYEQPKQSVEYEDEEQKPMVIFFDTGDEIFNHILFPDSFYMYEEGSSYAYEMSYLMYCD
LRIILWNGSIALFGFNRFSVFPDSYGVWVLDDFDGAKGSWTKHLTFEPLMGIKRVLEFWRSDEILMVTEDGDIVSYNL
ATQKLENLPMNSLSDFETIVYVNSLVSITRGNKLESVDI"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "F-box protein"
                },
                desc "S locus F-box7"
              },
              partial TRUE,
              location int {
                from 0,
                to 324,
                id local str "S7_haplotype_prot_1",
                fuzz-from lim lt
              }
            }
          }
        }
      }
    },
    seq {
      id {
        local str "S7_haplotype_prot_2",
        general {
          db "TMSMART",
          tag id 90976021
        }
      },
      descr {
        title "ribonuclease [Prunus dulcis]",
        molinfo {
          biomol peptide
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "LocalId",
              data str "S7_haplotype_prot_2"
            },
            {
              label str "General",
              data str "gnl|TMSMART|90976021"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 223,
        seq-data iupacaa "MGMLKSSLAFLVLGFAFFFCYVMSSGSYDYFQFVQQWPPTNCRVRMKRPCSN
PRPLQYFTIHGLWPSNFSNPTKPSNCNGTKFDARKVYPEMRSDLKISWPDVESGNDTKFWEDEWNKHGTCSEQTLNQF
QYFERSHEMWMSYNITEILKNASIVPHPAKTWTYSDIVSPIKAATGRTPLLRCKYDNNTQLLHEVVFCYGYKAIKQID
CNRPGCKNKIDIKFQ"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "ribonuclease"
                }
              },
              location int {
                from 0,
                to 222,
                id local str "S7_haplotype_prot_2"
              }
            }
          }
        }
      }
    },
    seq {
      id {
        local str "S7_haplotype_prot_5",
        general {
          db "TMSMART",
          tag id 90976024
        }
      },
      descr {
        title "S haplotype-specific F-box7 [Prunus dulcis]",
        molinfo {
          biomol peptide
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "LocalId",
              data str "S7_haplotype_prot_5"
            },
            {
              label str "General",
              data str "gnl|TMSMART|90976024"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 374,
        seq-data ncbieaa "MTFKLGKKEILIDILARLTAKSLVRFLCTCKSWSDLIGRSSFVSTHINRNVT
KHAHVYLLCLHHPTFERQNDNDDPFVEEELLWSLFSNETFEQFSKLSNPLGSTEHYGIYGSSNGLVCISDEILNYDSP
IHIWNPSVRKFRTPPISPNNIKFVYVALQFGFHSGVNDYKAVRMMRSNKDTFAVEVYSLRTDSWKMIETIPPWLKCTW
QHHTGTFFNGAAYHIIEKGPLFSIMSFDSGSEEFEEFIAPDAICNSRGLCIDAYKDQICLLFRFYGCEEEGMRKVDLW
VLQEKRWKQLCPFIIPWKYCRTIGTSIDNELLLQKKDFNKGAADLCLCNYESKQVLETGIKLAIMTYGEIDFLFSFTY
IESLVLLNNY"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "S haplotype-specific F-box7"
                },
                desc "SFB7"
              },
              location int {
                from 0,
                to 373,
                id local str "S7_haplotype_prot_5"
              }
            }
          }
        }
      }
    }
  },
  annot {
    {
      data ftable {
        {
          data cdregion {
            frame three,
            code {
              id 1
            }
          },
          partial TRUE,
          product whole local str "S7_haplotype_prot_1",
          location int {
            from 0,
            to 979,
            strand plus,
            id local str "S7_haplotype",
            fuzz-from lim lt
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 1
            }
          },
          product whole local str "S7_haplotype_prot_5",
          location int {
            from 11791,
            to 12915,
            strand minus,
            id genbank {
              accession "MH029536"
            }
          }
        },
        {
          data cdregion {
            code {
              id 1
            }
          },
          product whole local str "S7_haplotype_prot_2",
          location packed-int {
            {
              from 7681,
              to 7756,
              strand plus,
              id local str "S7_haplotype"
            },
            {
              from 8032,
              to 8219,
              strand plus,
              id local str "S7_haplotype"
            },
            {
              from 9745,
              to 10152,
              strand plus,
              id local str "S7_haplotype"
            }
          }
        }
      }
    }
  }
}
