Variation ::= {
  id {
    db "dbSNP",
    tag str "rs7"
  },
  placements {
    {
      loc int {
        from 2338270,
        to 2338274,
        id other {
          accession "NC_000001",
          version 10
        }
      },
      mol genomic,
      seq {
        length 1,
        seq-data iupacna "C"
      }
    }
  },
  variant-prop {
    version 5,
    resource-link preserved,
    gene-location 0,
    effect no-change,
    mapping 0,
    frequency-based-validation 0,
    genotype 0,
    quality-check 0
  },
  data set {
    type package,
    variations {
      {
        data instance {
          type del,
          delta {
            {
              seq this NULL,
              action del-at
            }
          }
        }
      }
    }
  },
  ext {
    {
      type str "VcfAttributes",
      data {
        {
          label str "filter",
          data str "PASS"
        },
        {
          label str "info",
          data str "DB"
        }
      }
    },
    {
      type str "Description",
      data {
        {
          label str "Output dbSNP Context",
          data str "This is deleting a C, and the output should be an interval"
        }
      }
    }
  }
}
