include $(builddir)/Makefile.mk

all all_r:
	$(SHELL) -c ' \
		cd "$(srcdir)" || exit 2; \
	    if test -x "$(bindir)/datatool"; then \
	        NCBI_DATATOOL_PATH="$(bindir)"; \
			export NCBI_DATATOOL_PATH; \
		fi; \
		$(MAKE) all_files; \
	'

clean clean_r purge purge_r:
