# $Id$
#
# Generate ASN.1 serialization code in the "objects/" projects

include $(builddir)/Makefile.mk

all all_r all_p:
	cd "$(srcdir)" || exit 2; $(MAKE) all_files

clean clean_r clean_p purge purge_r purge_p:
