Variation ::= {
  name "NC_000007.13:g.126096600_126096601insAAAAAAAA",
  data set {
    type package,
    variations {
      {
        placements {
          {
            loc int {
              from 126096599,
              to 126096600,
              strand plus,
              id gi 224589819
            },
            mol unknown
          }
        },
        data instance {
          type ins,
          delta {
            {
              seq literal {
                length 8,
                seq-data iupacna "AAAAAAAA"
              },
              action ins-before
            }
          }
        }
      }
    }
  }
}
