Seq-annot ::= {
  data ftable {
    {
      data variation {
        name "NC_000007.13:g.126096600_126096601insAAAAAAAA",
        data instance {
          type ins,
          delta {
            {
              seq literal {
                length 8,
                seq-data iupacna "AAAAAAAA"
              },
              action ins-before
            }
          }
        }
      },
      location int {
        from 126096573,
        to 126096600,
        strand plus,
        id gi 224589819
      }
    }
  }
}
