Seq-annot ::= {
  desc {
    user {
      type str "vcf-meta-info",
      data {
        {
          label str "meta-information",
          num 5,
          data strs {
            "fileformat=VCFv4.0",
            "source=dbSNP",
            "dbSNP_BUILD_ID=138",
            "reference=GRCh37.p10",
            "phasing=partial"
          }
        }
      }
    }
  },
  data ftable {
    {
      data variation {
        id {
          db "local",
          tag str "rs111033223"
        },
        variant-prop {
          version 5,
          resource-link 0,
          gene-location 0,
          effect no-change,
          mapping 0,
          frequency-based-validation 0,
          genotype 0,
          quality-check 0
        },
        data set {
          type package,
          variations {
            {
              data instance {
                type identity,
                delta {
                  {
                    seq literal {
                      length 22,
                      seq-data iupacna "GGAGGCGGGGACACCAGGGCCT"
                    }
                  }
                },
                observation reference
              }
            },
            {
              data instance {
                type del,
                delta {
                  {
                    seq this NULL,
                    action del-at
                  }
                }
              }
            }
          }
        }
      },
      location int {
        from 76895770,
        to 76895792,
        id other {
          accession "NC_000011",
          version 9
        }
      },
      ext {
        type str "VcfAttributes",
        data {
          {
            label str "filter",
            data str "."
          },
          {
            label str "info",
            data str "RS=111033223;RSPOS=76895772"
          }
        }
      }
    }
  }
}
