# $Id$
##################################

include $(builddir)/Makefile.mk

SCRIPT_NAME = get_species_taxids.sh

all:
	@if [ '$(BINCOPY)' != '@:' -a -d $(bindir) -a -w $(bindir) -a $(srcdir) != . ]; then \
	        echo $(BINCOPY) $(srcdir)/$(SCRIPT_NAME) $(bindir) && \
	        $(BINCOPY) $(srcdir)/$(SCRIPT_NAME) $(bindir) || exit $? ; \
	fi

purge:
	-$(RM) $(bindir)/$(SCRIPT_NAME)

clean:

CHECK_REQUIRES = in-house-resources
CHECK_COPY = ${SCRIPT_NAME}
CHECK_CMD = ${SCRIPT_NAME} -t 9606
CHECK_CMD = ${SCRIPT_NAME} -t mouse

WATCHERS = fongah2 camacho
