# $Id
##################################

include $(builddir)/Makefile.mk

SCRIPT_NAME = legacy_blast.pl

all:
	@if [ '$(BINCOPY)' != '@:' -a -d $(bindir) -a -w $(bindir) -a $(srcdir) != . ]; then \
	        echo $(BINCOPY) $(SCRIPT_NAME) $(bindir)/ && \
	        $(BINCOPY) $(SCRIPT_NAME) $(bindir)/ || exit $? ; \
	fi

purge:
	( cd $(bindir)  &&  -$(RM) $(SCRIPT_NAME) )

clean:
	;

