# $Id$

all: sources

sources:
	for x in mmdb1 mmdb2 mmdb3; do \
	    d=$(srcdir)/../$$x ; \
	    (cd $$d  &&  $(builddir)/new_module.sh) ; \
	    echo "#include \"$$d/$${x}__.cpp\""  > $${x}__.cpp ; \
	    echo "#include \"$$d/$${x}___.cpp\"" > $${x}___.cpp ; \
	done

clean:;
purge:;
