APP = feat_trim
SRC = feat_trim

CPPFLAGS = $(ORIG_CPPFLAGS)

LIB = $(OBJEDIT_LIBS) xobjutil  $(DATA_LOADERS_UTIL_LIB) $(OBJMGR_LIBS)

LIBS = $(DATA_LOADERS_UTIL_LIBS) $(NETWORK_LIBS) $(DL_LIBS) $(ORIG_LIBS)

REQUIRES = objects

WATCHERS = foleyjp


