Seq-annot ::= {
  id {
    local str "ctg123"
  },
  data ftable {
    {
      id local str "gene00001",
      data gene {
      },
      location int {
        from 999,
        to 8999,
        strand plus,
        id local str "ctg123"
      },
      qual {
        {
          qual "gff_source",
          val "."
        },
        {
          qual "gff_type",
          val "gene"
        },
        {
          qual "ID",
          val "gene00001"
        },
        {
          qual "Name",
          val "EDEN"
        }
      }
    },
    {
      data imp {
        key "TF_binding_site"
      },
      location int {
        from 999,
        to 1011,
        strand plus,
        id local str "ctg123"
      },
      qual {
        {
          qual "gff_source",
          val "."
        },
        {
          qual "gff_type",
          val "TF_binding_site"
        },
        {
          qual "Parent",
          val "gene00001"
        }
      },
      xref {
        {
          id local str "gene00001"
        }
      }
    },
    {
      id local str "mRNA00001",
      data rna {
        type mRNA
      },
      location mix {
        int {
          from 1049,
          to 1499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 2999,
          to 3901,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 8999,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "gff_source",
          val "."
        },
        {
          qual "gff_type",
          val "mRNA"
        },
        {
          qual "ID",
          val "mRNA00001"
        },
        {
          qual "Parent",
          val "gene00001"
        }
      },
      xref {
        {
          id local str "gene00001"
        }
      }
    },
    {
      id local str "mRNA00002",
      data rna {
        type mRNA
      },
      location mix {
        int {
          from 1049,
          to 1499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 8999,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "gff_source",
          val "."
        },
        {
          qual "gff_type",
          val "mRNA"
        },
        {
          qual "ID",
          val "mRNA00002"
        },
        {
          qual "Parent",
          val "gene00001"
        }
      },
      xref {
        {
          id local str "gene00001"
        }
      }
    },
    {
      id local str "mRNA00003",
      data rna {
        type mRNA
      },
      location mix {
        int {
          from 1299,
          to 1499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 2999,
          to 3901,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 8999,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "gff_source",
          val "."
        },
        {
          qual "gff_type",
          val "mRNA"
        },
        {
          qual "ID",
          val "mRNA00003"
        },
        {
          qual "Parent",
          val "gene00001"
        }
      },
      xref {
        {
          id local str "gene00001"
        }
      }
    },
    {
      data cdregion {
        frame one
      },
      location mix {
        int {
          from 1200,
          to 1499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 2999,
          to 3901,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 7599,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "gff_source",
          val "."
        },
        {
          qual "gff_type",
          val "CDS"
        },
        {
          qual "ID",
          val "cds00001"
        },
        {
          qual "Parent",
          val "mRNA00001"
        }
      },
      xref {
        {
          id local str "mRNA00001"
        }
      }
    },
    {
      data cdregion {
        frame one
      },
      location mix {
        int {
          from 1200,
          to 1499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 7599,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "gff_source",
          val "."
        },
        {
          qual "gff_type",
          val "CDS"
        },
        {
          qual "ID",
          val "cds00002"
        },
        {
          qual "Parent",
          val "mRNA00002"
        }
      },
      xref {
        {
          id local str "mRNA00002"
        }
      }
    },
    {
      data cdregion {
        frame one
      },
      location mix {
        int {
          from 3300,
          to 3901,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 7599,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "gff_source",
          val "."
        },
        {
          qual "gff_type",
          val "CDS"
        },
        {
          qual "ID",
          val "cds00003"
        },
        {
          qual "Parent",
          val "mRNA00003"
        }
      },
      xref {
        {
          id local str "mRNA00003"
        }
      }
    }
  }
}
