Seq-align-set ::= {
  {
    type global,
    dim 2,
    score {
      {
        id str "consensus_splices",
        value int 0
      },
      {
        id str "splices",
        value int 0
      }
    },
    segs spliced {
      product-id local str "TRINITY_DN20162_c0_g1_i1",
      genomic-id local str "scaffold7_cov82",
      product-strand plus,
      genomic-strand plus,
      product-type transcript,
      exons {
        {
          product-start nucpos 0,
          product-end nucpos 184,
          genomic-start 548211,
          genomic-end 548395,
          parts {
            match 8,
            mismatch 1,
            match 50,
            mismatch 1,
            match 2,
            mismatch 2,
            match 25,
            mismatch 1,
            match 12,
            mismatch 1,
            match 6,
            mismatch 1,
            match 10,
            mismatch 1,
            match 11,
            mismatch 1,
            match 12,
            mismatch 1,
            match 4,
            mismatch 1,
            match 3,
            mismatch 1,
            match 4,
            mismatch 2,
            match 2,
            mismatch 1,
            match 3,
            mismatch 1,
            match 4,
            mismatch 1,
            match 2,
            mismatch 1,
            match 4,
            mismatch 2,
            match 3
          },
          scores {
            {
              id str "splign",
              value real { 144119995117188, 10, -12 }
            },
            {
              id str "idty",
              value real { 891891891891892, 10, -15 }
            }
          },
          partial TRUE
        }
      },
      product-length 212
    },
    ext {
      {
        type str "origin",
        data {
          {
            label str "algo",
            data str "Splign:2.1.0"
          }
        }
      }
    }
  }
}
