/*  $Id$
 * =========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * =========================================================================
 *
 * Author:  Jie Chen
 *
 * File Description:
 *   data file for the static suspect product list
 *
 * $Log:$ 
 */

#include <ncbi_pch.hpp>
#include <objtools/discrepancy_report/hDiscRep_config.hpp>
#include <objtools/discrepancy_report/hDiscRep_tests.hpp>

BEGIN_NCBI_SCOPE

USING_NCBI_SCOPE;
USING_SCOPE(DiscRepNmSpc);

static CDiscRepInfo thisInfo;

static const s_SuspectProductNameData suspect_prod_terms111[] = {
  { "beginning with period, comma, or hyphen" , CTestAndRepData::BeginsWithPunct, eSuspectNameType_InappropriateSymbol, NULL, NULL } ,
  { "begins or ends with quotes", CTestAndRepData::BeginsOrEndsWithQuotes, eSuspectNameType_QuickFix, NULL, CTestAndRepData::RemoveBeginningAndEndingQuotes } ,
  { "binding" , CTestAndRepData::EndsWithPattern, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "domain", CTestAndRepData::EndsWithPattern, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "like" , CTestAndRepData::EndsWithPattern, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "motif" , CTestAndRepData::EndsWithPattern, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "related" , CTestAndRepData::EndsWithPattern, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "repeat", CTestAndRepData::EndsWithPattern, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "fold" , CTestAndRepData::EndsWithFold, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "Arabidopsis" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Aspergillus" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "B.subtilis" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Bacillus" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Bacteroides" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Campylobacter" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Chlamydial" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Chlamydomonas" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Drosophila" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "E.coli" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Escherichia" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Helicobacter" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Includes:" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_InappropriateSymbol, NULL, NULL } ,
  { "Jejuni" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Leishmania" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Marinococcus" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Mus musculus" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Mycobacterium" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Pestis" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Rhodobacter" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Salmonella" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Staphlococcal" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Staphlococcus" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Staphylococcus" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Streptococcus" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Subtilis" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Tuberculosis" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Typhimurium" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Yersinia" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "aminotransferasee" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo , "aminotransferase", CTestAndRepData::SimpleReplaceFunc } ,
  { "arginin " , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo , "arginine ", CTestAndRepData::SimpleReplaceFunc } ,
  { "argininte" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo , "arginine", CTestAndRepData::SimpleReplaceFunc } ,
  { "aureus" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "bioin" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo , "biotin", CTestAndRepData::SimpleReplaceFunc } ,
  { "biosythesis" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo , "biosynthesis", CTestAndRepData::SimpleReplaceFunc } ,
  { "cerevisiae" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "chelatin" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo , "chelating", CTestAndRepData::SimpleReplaceFunc } ,
  { "coli" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "contain" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_None, NULL, NULL } ,
  { "deydrogenase" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "dehydrogenase", CTestAndRepData::SimpleReplaceFunc } ,
  { "diacyglycerol" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "diacylglycerol", CTestAndRepData::SimpleReplaceFunc } ,
  { "domainl", CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "domain", CTestAndRepData::SimpleReplaceFunc } ,
  { "enterica" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "exporte" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "exported", CTestAndRepData::SimpleReplaceFunc } ,
  { "familie" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "family", CTestAndRepData::SimpleReplaceFunc } ,
  { "gene" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_None, NULL, NULL } ,
  { "genes" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_None, NULL, NULL } ,
  { "glycin" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "glycine", CTestAndRepData::SimpleReplaceFunc } ,
  { "glycosy" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "glucosyl", CTestAndRepData::SimpleReplaceFunc } ,
  { "halophilus" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "hemaggltinin" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "hemagglutinin", CTestAndRepData::SimpleReplaceFunc } ,
  { "hexpeptide" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "hexapeptide", CTestAndRepData::SimpleReplaceFunc } ,
  { "histide" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "histidine", CTestAndRepData::SimpleReplaceFunc } ,
  { "homo" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "homocystein" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "homocysteine", CTestAndRepData::SimpleReplaceFunc } ,
  { "hyp domain protein" , CTestAndRepData::IsSingleWord, eSuspectNameType_Typo, "hypothetical protein", CTestAndRepData::SimpleReplaceFunc },
  { "hypot" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypothe" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypothet" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypothetic" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypothetica" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypothetical domain protein" , CTestAndRepData::IsSingleWord, eSuspectNameType_Typo, "hypothetical protein", CTestAndRepData::SimpleReplaceFunc },
  { "inactivated derivative" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_None, NULL, NULL } ,
  { "initation" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "initiation", CTestAndRepData::SimpleReplaceFunc } ,
  { "invertion" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "inversion", CTestAndRepData::SimpleReplaceFunc } ,
  { "isomaerase" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "isomerase", CTestAndRepData::SimpleReplaceFunc } ,
  { "mobilisation" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "mobilization", CTestAndRepData::SimpleReplaceFunc } ,
  { "mouse" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "mutatrotase" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "mutarotase", CTestAndRepData::SimpleReplaceFunc } ,
  { "ncharacterized" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "uncharacterized", CTestAndRepData::SimpleReplaceFunc } ,
  { "ndoribonuclease" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "endoribonuclease", CTestAndRepData::SimpleReplaceFunc } ,
  { "niger" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "ntegral " , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "integral ", CTestAndRepData::SimpleReplaceFunc } ,
  { "obalt" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "cobalt", CTestAndRepData::SimpleReplaceFunc } ,
  { "odule" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_None, NULL, NULL } ,
  { "orf, hyp" , CTestAndRepData::IsSingleWord, eSuspectNameType_Typo, "hypothetical protein", CTestAndRepData::SimpleReplaceFunc },
  { "orf, hypothetical" , CTestAndRepData::IsSingleWord, eSuspectNameType_Typo, "hypothetical protein", CTestAndRepData::SimpleReplaceFunc },
  { "oxidoreductasee" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "oxidoreductase", CTestAndRepData::SimpleReplaceFunc } ,
  { "oxidoredutase" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "oxidoreductase", CTestAndRepData::SimpleReplaceFunc } ,
  { "periplamic" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "periplasmic", CTestAndRepData::SimpleReplaceFunc } ,
  { "periplasmc" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "periplasmic", CTestAndRepData::SimpleReplaceFunc } ,
  { "phosphatidyltransferse" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "phosphatidyltransferase", CTestAndRepData::SimpleReplaceFunc } ,
  { "phosphopantethiene" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "phosphopantetheine", CTestAndRepData::SimpleReplaceFunc } ,
  { "pombe" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "portein" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "protein", CTestAndRepData::SimpleReplaceFunc } ,
  { "protei" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "protein", CTestAndRepData::SimpleReplaceFunc } ,
  { "protwin" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "protein", CTestAndRepData::SimpleReplaceFunc } ,
  { "pseudo" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "pseudomonas" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "puter" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "outer", CTestAndRepData::SimpleReplaceFunc } ,
  { "pylori" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "rat" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "reductasee" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "reductase", CTestAndRepData::SimpleReplaceFunc } ,
  { "rsponse" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "response", CTestAndRepData::SimpleReplaceFunc } ,
  { "serovar" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "sigm" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "sigma", NULL } ,
  { "sreptomyces" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_None, NULL, NULL } ,
  { "staphylococcal" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "start codon" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "streptococcal" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "streptomyces" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "subsp" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "tetracenpmycin" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "tetracenomycin", CTestAndRepData::SimpleReplaceFunc } ,
  { "thaliana" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "thiamin/thiamin" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "thiamin/thiamine", CTestAndRepData::SimpleReplaceFunc } ,
  { "thioderoxin" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "thioredoxin", CTestAndRepData::SimpleReplaceFunc } ,
  { "threonin" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "threonine", CTestAndRepData::SimpleReplaceFunc } ,
  { "transcrIptional" , CTestAndRepData::ContainsWholeWordCaseSensitive, eSuspectNameType_Typo, "transcriptional", CTestAndRepData::SimpleReplaceFunc } ,
  { "transemembrane" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "transmembrane", CTestAndRepData::SimpleReplaceFunc } ,
  { "transferasee" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "transferase", CTestAndRepData::SimpleReplaceFunc } ,
  { "transmebrane" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "transmembrane", CTestAndRepData::SimpleReplaceFunc } ,
  { "unkn", CTestAndRepData::IsSingleWord, eSuspectNameType_None, "hypothetical protein", CTestAndRepData::SimpleReplaceFunc },
  { "unnamed" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_None, NULL, NULL } ,
  { "utilisation" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "utilization", CTestAndRepData::SimpleReplaceFunc } ,
  { "xenopus" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "yeast" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "ypothetical" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "ytochrome" , CTestAndRepData::ContainsWholeWord, eSuspectNameType_Typo, "cytochrome", CTestAndRepData::SimpleReplaceFunc } ,
  { "containing" , CTestAndRepData::StartsWithPattern, eSuspectNameType_None, NULL, NULL } ,
  { "from" , CTestAndRepData::StartsWithPattern, eSuspectNameType_None, NULL, NULL } ,
  { "CHC2 zinc finger" , CTestAndRepData::IsSingleWord, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "SWIM zinc finger" , CTestAndRepData::IsSingleWord, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "probable protein" , CTestAndRepData::IsSingleWord, eSuspectNameType_None, NULL, NULL } ,
  { "protein" , CTestAndRepData::IsSingleWord, eSuspectNameType_None, NULL, NULL } ,
  { "sodium" , CTestAndRepData::IsSingleWord, eSuspectNameType_None, NULL, NULL } ,
  { "IS" , CTestAndRepData::PrefixPlusNumbersOnly, eSuspectNameType_None, NULL, NULL } ,
  { "three or more numbers together, not after 'UPF' or 'DUF' or 'IS' and not followed by the word 'family' and not preceded by either 'cytochrome' or 'coenzyme'" , CTestAndRepData::ThreeOrMoreNumbersTogether,
 eSuspectNameType_Database, NULL, NULL } ,
  { "all capital letters" , CTestAndRepData::AllCapitalLetters, eSuspectNameType_InappropriateSymbol, NULL, NULL } ,
  { "#" , CTestAndRepData::NormalSearch, eSuspectNameType_InappropriateSymbol, NULL, NULL } ,
  { ". " , CTestAndRepData::NormalSearch, eSuspectNameType_InappropriateSymbol, NULL, NULL } ,
  { "=" , CTestAndRepData::NormalSearch, eSuspectNameType_InappropriateSymbol, NULL, NULL } ,
  { "?" , CTestAndRepData::NormalSearch, eSuspectNameType_InappropriateSymbol, NULL, NULL } ,
  { "%" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "Chloroplast" , CTestAndRepData::NormalSearch, eSuspectNameType_NoOrganelleForProkaryote, NULL, NULL } ,
  { "ECOLI" , CTestAndRepData::NormalSearch, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Fragment" , CTestAndRepData::NormalSearch, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "Frameshift" , CTestAndRepData::NormalSearch, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "Homolog" , CTestAndRepData::NormalSearch, eSuspectNameType_EvolutionaryRelationship, NULL, NULL } ,
  { "Intein" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "Intiation" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "initiation", CTestAndRepData::SimpleReplaceFunc } ,
  { "K potassium" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "K+ potassium" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "Mitochondrial" , CTestAndRepData::NormalSearch, eSuspectNameType_NoOrganelleForProkaryote, NULL, NULL } ,
  { "No definition line found" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "Plasmodium" , CTestAndRepData::NormalSearch, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "Portein" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "Related to" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "Similar to" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "Transemembrane" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "Transmebrane" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "\\-PA" , CTestAndRepData::NormalSearch, eSuspectNameType_InappropriateSymbol, NULL, NULL } ,
  { "accessroy" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "accessory", CTestAndRepData::SimpleReplaceFunc } ,
  { "aceytltranferase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "acetyltransferase", CTestAndRepData::SimpleReplaceFunc } ,
  { "active site" , CTestAndRepData::NormalSearch, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "adenylattransferase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "adenylate transferase", CTestAndRepData::SimpleReplaceFunc } ,
  { "adenylytransferase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "adenylyltransferase", CTestAndRepData::SimpleReplaceFunc } ,
  { "alternate protein name" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "aluminium" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "aluminum", CTestAndRepData::SimpleReplaceFunc } ,
  { "aminopetidase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "aminopeptidase", CTestAndRepData::SimpleReplaceFunc } ,
  { "aparaginase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "asparaginase", CTestAndRepData::SimpleReplaceFunc } ,
  { "asparate" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "aspartate", CTestAndRepData::SimpleReplaceFunc } ,
  { "authentic point mutation" , CTestAndRepData::NormalSearch, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "bifunctional" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "bifunctionnal" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "bifunctional", CTestAndRepData::SimpleReplaceFunc } ,
  { "bigenesis" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "biogenesis", CTestAndRepData::SimpleReplaceFunc } ,
  { "biosyntesis" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "biosynthesis", CTestAndRepData::SimpleReplaceFunc } ,
  { "bnding" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "binding", CTestAndRepData::SimpleReplaceFunc } ,
  { "bos taurus" , CTestAndRepData::NormalSearch, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "carboxilic" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "carboxylic", CTestAndRepData::SimpleReplaceFunc } ,
  { "cell divisionFtsK/SpoIIIE" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "characteris" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "characteriz", CTestAndRepData::SimpleReplaceAnywhereFunc } ,
  { "coantaining" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "containing", CTestAndRepData::SimpleReplaceFunc } ,
  { "coenzye" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "coenzyme", CTestAndRepData::SimpleReplaceFunc } ,
  { "componenet" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "component", CTestAndRepData::SimpleReplaceFunc } ,
  { "componnent" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "component", CTestAndRepData::SimpleReplaceFunc } ,
  { "consevered" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "conserved", CTestAndRepData::SimpleReplaceFunc } ,
  { "containg" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "containing", CTestAndRepData::SimpleReplaceFunc } ,
  { "cotaining" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "containing", CTestAndRepData::SimpleReplaceFunc } ,
  { "degration" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "degradation", CTestAndRepData::SimpleReplaceFunc } ,
  { "deletion" , CTestAndRepData::NormalSearch, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "dependant" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "dependent", CTestAndRepData::SimpleReplaceFunc } ,
  { "dimerisation" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "dimerization", CTestAndRepData::SimpleReplaceFunc } ,
  { "dimerising" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "dimerizing", CTestAndRepData::SimpleReplaceFunc } ,
  { "dioxyenase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "dioxygenase", CTestAndRepData::SimpleReplaceFunc } ,
  { "disulphide" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "disulfide", CTestAndRepData::SimpleReplaceFunc } ,
  { "divison" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "division", CTestAndRepData::SimpleReplaceFunc } ,
  { "domain domain" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "domain protein domain protein" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "domian" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "domain", CTestAndRepData::SimpleReplaceFunc } ,
  { "dyhydrogenase" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "dyhydrogenase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "dehydrogenase", CTestAndRepData::SimpleReplaceFunc } ,
  { "enentioselective" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "enantioselective", CTestAndRepData::SimpleReplaceFunc } ,
  { "facotr" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "factor", CTestAndRepData::SimpleReplaceFunc } ,
  { "fagella", CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "flagella", CTestAndRepData::SimpleReplaceFunc } ,
  { "family family" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "family", CTestAndRepData::SimpleReplaceFunc } ,
  { "flageller" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "flagellar", CTestAndRepData::SimpleReplaceFunc } ,
  { "frame shift" , CTestAndRepData::NormalSearch, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "gIycerol" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "glycerol", CTestAndRepData::SimpleReplaceFunc } ,
  { "glcosyl" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "glycosyl", CTestAndRepData::SimpleReplaceFunc } ,
  { "glucosainyl" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "glucosaminyl", CTestAndRepData::SimpleReplaceFunc } ,
  { "glutaminne" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "glutamine", CTestAndRepData::SimpleReplaceFunc } ,
  { "golgi" , CTestAndRepData::NormalSearch, eSuspectNameType_NoOrganelleForProkaryote, NULL, NULL } ,
  { "haem" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "heme", CTestAndRepData::HaemReplaceFunc } ,
  { "haemagglutination" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hemagglutination", CTestAndRepData::SimpleReplaceFunc } ,
  { "heam" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "heme", CTestAndRepData::HaemReplaceFunc } ,
  { "hemelysin" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hemolysin", CTestAndRepData::SimpleReplaceFunc } ,
  { "hemoglobine" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hemoglobin", CTestAndRepData::SimpleReplaceFunc } ,
  { "hexapaptide" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hexapeptide", CTestAndRepData::SimpleReplaceFunc } ,
  { "highly conserved" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "histadine" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "histidine", CTestAndRepData::SimpleReplaceFunc } ,
  { "homeserine" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "homoserine", CTestAndRepData::SimpleReplaceFunc } ,
  { "homo sapiens" , CTestAndRepData::NormalSearch, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "hpothetical" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "human" , CTestAndRepData::NormalSearch, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "hyphotetical" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hyphotheical" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypotehtical" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypotethical" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypotetical" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypotheical" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypotheitcal" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypothetcial" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypothteical" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypothtical" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hypthetical" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "hyptothetical" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "hypothetical", CTestAndRepData::SimpleReplaceFunc } ,
  { "inductible" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "inducible", CTestAndRepData::SimpleReplaceFunc } ,
  { "interrupt" , CTestAndRepData::NormalSearch, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "isomerse" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "isomerase", CTestAndRepData::SimpleReplaceFunc } ,
  { "majour" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "major", CTestAndRepData::SimpleReplaceFunc } ,
  { "mambrane" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "membrane", CTestAndRepData::SimpleReplaceFunc } ,
  { "meausure" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "measure", CTestAndRepData::SimpleReplaceFunc } ,
  { "membranne" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "membrane", CTestAndRepData::SimpleReplaceFunc } ,
  { "methlytransferase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "methyltransferase", CTestAndRepData::SimpleReplaceFunc } ,
  { "metylase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "methylase", CTestAndRepData::SimpleReplaceFunc } ,
  { "molibdenum" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "molybdenum", CTestAndRepData::SimpleReplaceFunc } ,
  { "molybopterin" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "molybdopterin", CTestAndRepData::SimpleReplaceFunc } ,
  { "molydopterin" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "molybdopterin", CTestAndRepData::SimpleReplaceFunc } ,
  { "monooxigenase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "monooxygenase", CTestAndRepData::SimpleReplaceFunc } ,
  { "monoxyde" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "monoxide", CTestAndRepData::SimpleReplaceFunc } ,
  { "monoxygenase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "monooxygenase", CTestAndRepData::SimpleReplaceFunc } ,
  { "mulitdrug" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "multidrug", CTestAndRepData::SimpleReplaceFunc } ,
  { "multifunctional", CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "narrowly conserved" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "nickle" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "nickel", CTestAndRepData::SimpleReplaceFunc } ,
  { "novel protein" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "nucelar" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "nuclear", CTestAndRepData::SimpleReplaceFunc } ,
  { "nucleotydyl" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "nucleotidyl", CTestAndRepData::SimpleReplaceFunc } ,
  { "nulcear" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "nuclear", CTestAndRepData::SimpleReplaceFunc } ,
  { "open reading frame" , CTestAndRepData::NormalSearch, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "or related" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "orphan protein" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "ortholog" , CTestAndRepData::NormalSearch, eSuspectNameType_EvolutionaryRelationship, NULL, NULL } ,
  { "outers" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "outer", CTestAndRepData::SimpleReplaceFunc } ,
  { "oxidoreducatse" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "oxidoreductase", CTestAndRepData::SimpleReplaceFunc } ,
  { "oxidoreductasse" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "oxidoreductase", CTestAndRepData::SimpleReplaceFunc } ,
  { "oxidoreduxtase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "oxidoreductase", CTestAndRepData::SimpleReplaceFunc } ,
  { "oxydase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "oxidase", CTestAndRepData::SimpleReplaceFunc } ,
  { "paralog" , CTestAndRepData::NormalSearch, eSuspectNameType_EvolutionaryRelationship, NULL, NULL } ,
  { "partial" , CTestAndRepData::NormalSearch, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "peptidodoglycan" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "peptidoglycan", CTestAndRepData::SimpleReplaceFunc } ,
  { "periplsmic" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "periplasmic", CTestAndRepData::SimpleReplaceFunc } ,
  { "phophate" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "phosphate", CTestAndRepData::SimpleReplaceFunc } ,
  { "phopho" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "phospho", CTestAndRepData::SimpleReplaceFunc } ,
  { "phophoserine" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "phosphoserine", CTestAndRepData::SimpleReplaceFunc } ,
  { "phoshate" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "phosphate", CTestAndRepData::SimpleReplaceFunc } ,
  { "phosphatransferase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "phosphotransferase", CTestAndRepData::SimpleReplaceFunc } ,
  { "phosphotase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "phosphatase", CTestAndRepData::SimpleReplaceFunc } ,
  { "posible" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "possible", CTestAndRepData::SimpleReplaceFunc } ,
  { "presursor" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "precursor", CTestAndRepData::SimpleReplaceFunc } ,
  { "probable putative" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "proein" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "protein", CTestAndRepData::SimpleReplaceFunc } ,
  { "prortein" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "protein", CTestAndRepData::SimpleReplaceFunc } ,
  { "proteine" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "protein", CTestAndRepData::SimpleReplaceFunc } ,
  { "proteinn" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "protein", CTestAndRepData::SimpleReplaceFunc } ,
  { "protien" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "protein", CTestAndRepData::SimpleReplaceFunc } ,
  { "protrein" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "protein", CTestAndRepData::SimpleReplaceFunc } ,
  { "prptein" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "protein", CTestAndRepData::SimpleReplaceFunc } ,
  { "pseudogene" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "puatative" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "puative" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "putaitive" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "putaitve" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "putaive" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "putataive" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "putatitve" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "putative orphan protein" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "putative probable" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "putative putative" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "putative, putative" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "putatuve" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "putatve" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "putatvie" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "putayive" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "putitive" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "putative", CTestAndRepData::SimpleReplaceFunc } ,
  { "qlcohol" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "alcohol", CTestAndRepData::SimpleReplaceFunc } ,
  { "recognised" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "recognized", CTestAndRepData::SimpleReplaceFunc } ,
  { "regulatot" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "regulator", CTestAndRepData::SimpleReplaceFunc } ,
  { "reponse" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "response", CTestAndRepData::SimpleReplaceFunc } ,
  { "resistence" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "resistance", CTestAndRepData::SimpleReplaceFunc } ,
  { "ribosimal" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "ribosomal", CTestAndRepData::SimpleReplaceFunc } ,
  { "ribosoml" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "ribosomal", CTestAndRepData::SimpleReplaceFunc } ,
  { "sapiens" , CTestAndRepData::NormalSearch, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "serinr" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "serine", CTestAndRepData::SimpleReplaceFunc } ,
  { "signalling" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "signaling", CTestAndRepData::SimpleReplaceFunc } ,
  { "similar" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "simmilar" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "specfic" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "specific", CTestAndRepData::SimpleReplaceFunc } ,
  { "sphaeroides" , CTestAndRepData::NormalSearch, eSuspectNameType_RemoveOrganismName, NULL, NULL } ,
  { "spscific" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "specific", CTestAndRepData::SimpleReplaceFunc } ,
  { "stabilisation" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "stabilization", CTestAndRepData::SimpleReplaceFunc } ,
  { "subnit" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "subunit", CTestAndRepData::SimpleReplaceFunc } ,
  { "suger" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "sugar", CTestAndRepData::SimpleReplaceFunc } ,
  { "sulpho" , CTestAndRepData::NormalSearch, eSuspectNameType_None, "sulfo", CTestAndRepData::SimpleReplaceFunc } ,
  { "sulphur" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "sulfur", CTestAndRepData::SimpleReplaceFunc } ,
  { "systhesis" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "synthesis", CTestAndRepData::SimpleReplaceFunc } ,
  { "sythase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "synthase", CTestAndRepData::SimpleReplaceFunc } ,
  { "thiredoxin" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "thioredoxin", CTestAndRepData::SimpleReplaceFunc } ,
  { "trancsriptional" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transcription", CTestAndRepData::SimpleReplaceFunc } ,
  { "tranferase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transferase", CTestAndRepData::SimpleReplaceFunc } ,
  { "tranporter" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transporter", CTestAndRepData::SimpleReplaceFunc } ,
  { "transcirbed" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transcribed", CTestAndRepData::SimpleReplaceFunc } ,
  { "transcriptonal" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transcriptional", CTestAndRepData::SimpleReplaceFunc } ,
  { "transcritional" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transcriptional", CTestAndRepData::SimpleReplaceFunc } ,
  { "transebrane" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transmembrane", CTestAndRepData::SimpleReplaceFunc } ,
  { "transglycolase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transglycosylase", CTestAndRepData::SimpleReplaceFunc } ,
  { "transorter" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transporter", CTestAndRepData::SimpleReplaceFunc } ,
  { "transpoase" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transposase", CTestAndRepData::SimpleReplaceFunc } ,
  { "transportor" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transporter", CTestAndRepData::SimpleReplaceFunc } ,
  { "transproter" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transporter", CTestAndRepData::SimpleReplaceFunc } ,
  { "transulfuration" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transsulfuration", CTestAndRepData::SimpleReplaceFunc } ,
  { "trnasporter" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "transporter", CTestAndRepData::SimpleReplaceFunc } ,
  { "truncat" , CTestAndRepData::NormalSearch, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "ttg start" , CTestAndRepData::NormalSearch, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "tumour" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "tumor", CTestAndRepData::SimpleReplaceFunc } ,
  { "typr" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "type", CTestAndRepData::SimpleReplaceFunc } ,
  { "uncharacterized protein", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } ,
  { "uncharaterized" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "undecapaprenyl" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "undecaprenyl", CTestAndRepData::SimpleReplaceFunc } ,
  { "unkown" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "utilising" , CTestAndRepData::NormalSearch, eSuspectNameType_Typo, "utilizing", CTestAndRepData::SimpleReplaceFunc } ,
  { "weakly conserved" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "widely conserved" , CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "|" , CTestAndRepData::NormalSearch, eSuspectNameType_InappropriateSymbol, NULL, NULL } ,
  { "C term" , CTestAndRepData::ProductContainsTerm, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "C-term" , CTestAndRepData::ProductContainsTerm, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "N term" , CTestAndRepData::ProductContainsTerm, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "N-term" , CTestAndRepData::ProductContainsTerm, eSuspectNameType_MightBeNonfunctional, NULL, NULL } ,
  { "Two or more sets of brackets or parentheseis" , CTestAndRepData::ContainsTwoSetsOfBracketsOrParentheses, eSuspectNameType_None, NULL, NULL } ,
  { "unknown" , CTestAndRepData::ContainsUnknownName, eSuspectNameType_None, NULL, NULL } ,
  { "double space" , CTestAndRepData::ContainsDoubleSpace, eSuspectNameType_None, NULL, NULL } ,
  { "COG" , CTestAndRepData::ContainsWholeWordCaseSensitive, eSuspectNameType_Database, NULL, NULL } ,
  { "DUF" , CTestAndRepData::ContainsWholeWordCaseSensitive, eSuspectNameType_Database, NULL, NULL } ,
  { "EST" , CTestAndRepData::ContainsWholeWordCaseSensitive, eSuspectNameType_Database, NULL, NULL } ,
  { "FOG" , CTestAndRepData::ContainsWholeWordCaseSensitive, eSuspectNameType_Database, NULL, NULL } ,
  { "UPF" , CTestAndRepData::ContainsWholeWordCaseSensitive, eSuspectNameType_Database, NULL, NULL } ,
  { "_" , CTestAndRepData::ContainsUnderscore, eSuspectNameType_Database, NULL, NULL } ,
  { "ending with period, comma, hyphen, underscore, colon, or forward slash" , CTestAndRepData::EndsWithPunct, eSuspectNameType_InappropriateSymbol, NULL, NULL } ,
  { "PTS system" , CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "helix-turn-helix" , CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "transposase of" , CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_None, NULL, NULL } ,
  { "zinc finger" , CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_UseProtein, NULL, NULL } ,
  { "may contain a plural" , CTestAndRepData::MayContainPlural, eSuspectNameType_None, NULL, NULL } ,
  { "unbalanced brackets or parentheses" , CTestAndRepData::ContainsUnbalancedParentheses, eSuspectNameType_InappropriateSymbol, NULL, NULL } ,
  { "long product name that may contain descriptive information more appropriate in a note", CTestAndRepData::IsTooLong, eSuspectNameType_QuickFix, NULL, NULL } ,
  { "Product name begins with possible, potential, predicted or probable.  Please use putative.", CTestAndRepData::StartsWithPutativeReplacement, eSuspectNameType_QuickFix, "putative", CTestAndRepData::UsePutative } ,
  { "CDS", CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "doubtful", CTestAndRepData::NormalSearch, eSuspectNameType_None, NULL, NULL } ,
  { "alternate protein name", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "conser", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "conserve", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "conserved hypothetical", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "conserved hypothetical protein", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "conserved", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "domain family", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "domain of unknown function", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "domain protein", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "domain", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "doubtful CDS found within S. typhi pathogenicity island", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "factor", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "family protein", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "hypo", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "hypothetical ORF", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "hypothetical", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "hypothetical domain protein", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "No definition line found", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "orphan protein", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "ORF", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "orf, hyp", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "orf, hypothetical", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "peptide", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "precursor", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "probable", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "predicted", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "predicted protein", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "probable protein", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "protein containing", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "protein of unknown function", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "protein-containing", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "pseudo", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "putative conserved hypothetical", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "putative hypothetical", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "putative protein", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "putative", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "uncharacterized conserved protein", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "unnamed", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameFunc } , 
  { "o252", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "o252 protein", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Alanine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Arginine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Asparagine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Aspartic acid", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Cysteine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "DNA", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Glutamic acid", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Glutamine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Glycine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Histidine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Isoleucine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Leucine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Lysine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Methionine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "NAD", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "PASTA", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_UseProtein, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Phenylalanine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Proline", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "RNA", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Serine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Threonine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Tryptophan", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Tyrosine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "Valine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "adenine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "amino acid", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "barrel", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "carbon", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "citrate", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "cytosine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "finger", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "ggdef", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "guanine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "helium", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "helix", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "hydrogen", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "insertion sequence", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "iron", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "mRNA", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "membrane", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "ncRNA", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "nitrogen", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "oxygen", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "p-loop", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_UseProtein, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "peptide", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "phage", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "plasmid", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "purine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "rRNA", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "repeat", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "secreted", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "signal peptide", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_UseProtein, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "signal", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "subunit", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "tRNA", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "thymine", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "transport-associated", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "transposon", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "uracil", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } , 
  { "zinc", CTestAndRepData::IsSingleWordOrWeaselPlusSingleWord, eSuspectNameType_QuickFix, "hypothetical protein", CTestAndRepData::ReplaceWholeNameAddNoteFunc } 
};

CDiscRepInfo :: CDiscRepInfo ()
{
   thisInfo.suspect_prod_terms = suspect_prod_terms111;
   thisInfo.num_suspect_prod_terms = ArraySize(suspect_prod_terms111);
}

END_NCBI_SCOPE
