#! /bin/sh
# $Id$

sqlitedir=${1:-sqlite}
sqlitebuilddir=${2:-${sqlitedir}-build}
sqliteinstalldir=${3:-${sqlitedir}-install}

# create and work out of the build directory.
if test ! -d ${sqlitebuilddir}
then
	mkdir ${sqlitebuilddir} || exit 1;
fi
cd ${sqlitebuilddir}

# NO, metrowerks compiler does not work for this.
# export CC=mwcc
# export CFLAGS=-char unsigned

{
 # echo "Error test: Oh, wretched failure! "; echo "Alack, alay!"; exit 1;
 { echo '** Configure'; ${sqlitedir}/configure -prefix=${sqliteinstalldir} ; } && \
 { echo '** Compile'; make all ; } && \
 { echo '** Install'; make install ; }
} >&2
