Variation ::= {
  id {
    db "dbSNP",
    tag str "rs5"
  },
  placements {
    {
      loc int {
        from 10689131,
        to 10689132,
        id other {
          accession "NT_005612",
          version 16
        }
      },
      mol genomic
    }
  },
  variant-prop {
    version 5,
    resource-link preserved,
    gene-location 0,
    effect no-change,
    mapping 0,
    frequency-based-validation 0,
    genotype 0,
    quality-check 0
  },
  data set {
    type package,
    variations {
      {
        data instance {
          type ins,
          delta {
            {
              seq literal {
                length 3,
                seq-data iupacna "TCG"
              },
              action ins-before
            }
          }
        }
      }
    }
  },
  ext {
    {
      type str "VcfAttributes",
      data {
        {
          label str "filter",
          data str "PASS"
        },
        {
          label str "info",
          data str "DB"
        }
      }
    },
    {
      type str "Description",
      data {
        {
          label str "dbSNP Output Context",
          data str "This insertion is out-of-sync with the repeat, and cannot
 be shifted"
        }
      }
    }
  }
}
