Variation ::= {
  id {
    db "local",
    tag str "rs111033223"
  },
  variant-prop {
    version 5,
    resource-link 0,
    gene-location 0,
    effect no-change,
    mapping 0,
    frequency-based-validation 0,
    genotype 0,
    quality-check 0
  },
  data set {
    type package,
    variations {
      {
        placements {
          {
            loc int {
              from 76895770,
              to 76895791,
              id other {
                accession "NC_000011",
                version 9
              }
            },
            mol genomic
          }
        },
        data set {
          type package,
          variations {
            {
              data instance {
                type identity,
                delta {
                  {
                    seq literal {
                      length 22,
                      seq-data iupacna "GGAGGCGGGGACACCAGGGCCT"
                    }
                  }
                },
                observation reference
              }
            },
            {
              data instance {
                type del,
                delta {
                  {
                    seq this NULL,
                    action del-at
                  }
                }
              }
            }
          }
        },
        ext {
          {
            type str "VcfAttributes",
            data {
              {
                label str "filter",
                data str "."
              },
              {
                label str "info",
                data str "RS=111033223;RSPOS=76895772"
              }
            }
          }
        }
      }
    }
  }
}
