Variation ::= {
  id {
    db "dbSNP",
    tag str "rs9"
  },
  variant-prop {
    version 5,
    resource-link preserved,
    gene-location 0,
    effect no-change,
    mapping 0,
    frequency-based-validation 0,
    genotype 0,
    quality-check 0
  },
  data set {
    type package,
    variations {
      {
        placements {
          {
            loc int {
              from 10689125,
              to 10689127,
              id other {
                accession "NT_005612",
                version 16
              }
            },
            mol genomic
          }
        },
        data set {
          type package,
          variations {
            {
              data instance {
                type identity,
                delta {
                  {
                    seq literal {
                      length 3,
                      seq-data iupacna "TGC"
                    }
                  }
                },
                observation reference
              }
            },
            {
              data instance {
                type del,
                delta {
                  {
                    seq this NULL,
                    action del-at
                  }
                }
              }
            }
          }
        },
        ext {
          {
            type str "VcfAttributes",
            data {
              {
                label str "filter",
                data str "PASS"
              },
              {
                label str "info",
                data str "DB"
              }
            }
          },
          {
            type str "Description",
            data {
              {
                label str "Input",
                data str "This deletion is in a triplet repeat.  It should be
 shifted left and right"
              }
            }
          }
        }
      }
    }
  }
}
