###  PATH TO A PRE-BUILT C++ TOOLKIT
builddir = $(NCBI)/c++/DebugMT/build
builddir = /home/boemker/dev/internal/c++/WorkShop53-DebugMT/build


###  DEFAULT COMPILATION FLAGS  -- DON'T EDIT OR MOVE THESE 4 LINES !!!
include $(builddir)/Makefile.mk
srcdir = .
BINCOPY = @:
LOCAL_CPPFLAGS = -I.


#############################################################################
###  EDIT SETTINGS FOR THE DEFAULT (APPLICATION) TARGET HERE              ### 

APP = blastcli
SRC = blastcli

LIB = xobjmgr dbapi_driver blast id1 seqset $(SEQ_LIBS) pub medline biblio\
 general xser xconnect xutil xncbi
LIBS = $(NETWORK_LIBS) $(ORIG_LIBS)


#############################################################################
###  APPLICATION BUILD RULES  -- DON'T EDIT OR MOVE THIS LINE !!!

include $(builddir)/Makefile.app


###  PUT YOUR OWN ADDITIONAL TARGETS (MAKE COMMANDS/RULES) HERE
