#ifndef DBAPI_DRIVER_ODBC_UNIX_ODBC___UNIXODBC_CONF__H
#define DBAPI_DRIVER_ODBC_UNIX_ODBC___UNIXODBC_CONF__H

#include <ncbiconf.h>
#define SIZEOF_LONG_INT SIZEOF_LONG
#ifdef SIZEOF_LONG_LONG
#  define HAVE_LONG_LONG 1
#endif

#endif /* DBAPI_DRIVER_ODBC_UNIX_ODBC___UNIXODBC_CONF__H */
