#ifndef DBAPI_DRIVER_ODBC_UNIX_ODBC___UNIXODBC_CONF__H
#define DBAPI_DRIVER_ODBC_UNIX_ODBC___UNIXODBC_CONF__H

#include <ncbiconf.h>
#define SIZEOF_LONG_INT SIZEOF_LONG

#endif /* DBAPI_DRIVER_ODBC_UNIX_ODBC___UNIXODBC_CONF__H */
