WATCHERS = camacho 

REQUIRES = objects

APP = convert2blastmask
SRC = convert2blastmask

LIB = $(BLAST_LIBS) $(OBJMGR_LIBS)

CFLAGS   = $(FAST_CFLAGS)
CXXFLAGS = $(FAST_CXXFLAGS)
LDFLAGS  = $(FAST_LDFLAGS) 

CPPFLAGS = -DNCBI_MODULE=BLASTDB $(ORIG_CPPFLAGS)
LIBS = $(CMPRS_LIBS) $(DL_LIBS) $(NETWORK_LIBS) $(ORIG_LIBS)
