# $Id$

APP = blastdbcheck
SRC = blastdbcheck blastdb_aux

LIB_ = $(BLAST_INPUT_LIBS) $(BLAST_DB_DATA_LOADER_LIBS) $(BLAST_LIBS) $(REGEX_LIBS) \
	$(OBJMGR_LIBS)
LIB = $(LIB_:%=%$(STATIC))

CFLAGS   = $(FAST_CFLAGS)
CXXFLAGS = $(FAST_CXXFLAGS)
LDFLAGS  = $(FAST_LDFLAGS)

CPPFLAGS = $(ORIG_CPPFLAGS)
LIBS = $(CMPRS_LIBS) $(DL_LIBS) $(PCRE_LIBS) $(NETWORK_LIBS) $(ORIG_LIBS)

REQUIRES = objects -Cygwin
