#ifndef __ID_CASS_SCOPE__
#define __ID_CASS_SCOPE__


#define IDBLOB_NS_IDBLOB idblob

#define BEGIN_IDBLOB_SCOPE BEGIN_SCOPE(IDBLOB_NS_IDBLOB)
#define END_IDBLOB_SCOPE   END_SCOPE(IDBLOB_NS_IDBLOB)
#define USING_IDBLOB_SCOPE USING_SCOPE(IDBLOB_NS_IDBLOB)


#endif
