Seq-annot ::= {
  desc {
    name "Demo Gene Models",
    title "Demo Gene Models"
  },
  data ftable {
    {
      id local id 1,
      data gene {
        locus "Danio rerio partial mRNA for SMG6 homolog nonsense mediated
 mRNA decay factor (C. elegans)cds (smg6 gene)"
      },
      location int {
        from 195029,
        to 196310,
        strand minus,
        id gi 258441149
      }
    },
    {
      id local id 2,
      data rna {
        type mRNA,
        ext name "Danio rerio partial mRNA for SMG6 homolog nonsense mediated
 mRNA decay factor (C. elegans)cds (smg6 gene)"
      },
      product whole gi 240248230,
      location packed-int {
        {
          from 195029,
          to 196310,
          strand minus,
          id gi 258441149
        }
      }
    },
    {
      id local id 3,
      data cdregion {
        frame two,
        code {
          id 1
        }
      },
      partial TRUE,
      except TRUE,
      product whole gi 240248231,
      location packed-int {
        {
          from 195029,
          to 196310,
          strand minus,
          id gi 258441149
        }
      },
      qual {
        {
          qual "inference",
          val "similar to AA sequence:UniProtKB:Q9VPS3"
        }
      },
      exp-ev not-experimental,
      except-text "unclassified translation discrepancy"
    }
  }
}
