Seq-entry ::= set {
    class genbank,
    seq-set {
        seq {
            id { local str "Seq1" },
            inst { 
                repr raw,
                mol dna,
                length 100,
                seq-data iupacna "AAAAAAAAAAAAAAAACCCCCCAAATTTTTTTTTTTTTTTTAAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAA"
            }
        },
        seq {
            id { local str "Seq2" },
            inst {
                repr delta,
                mol dna,
                length 3000,
                ext delta {
                    loc whole genbank { accession "U54469", version 1 },
                    literal { length 19, seq-data iupacna "GATTACAAAAAAAAAAAAA" },
                    literal { length 10, seq-data gap { type unknown } },
                    literal { length 40, seq-data gap { type unknown } },
                    literal { length 45, seq-data iupacna "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTAG" },
                    literal { length 5, seq-data gap { type unknown } }
                }
            }
        },
        seq {
            id { local str "Seq3" },
            inst {
                repr delta,
                mol dna,
                length 101,
                ext delta {
                    literal { length 101, seq-data gap { type unknown } }
                }
            }
        },
        seq {
            id { local str "Seq4" },
            inst {
                repr delta,
                mol dna,
                length 202,
                ext delta {
                    literal { length 101, seq-data gap { type unknown } },
                    literal { length 101, seq-data gap { type unknown } }
                }
            }
        }
    }
}
