/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * File Description:
 *   This code is generated by application DATATOOL
 *   using specifications from the ASN data definition file
 *   'twebenv.asn'.
 *
 * ATTENTION:
 *   Don't edit or check-in this file to the CVS as this file will
 *   be overridden (by DATATOOL) without warning!
 * ===========================================================================
 */

#ifndef DB_ENV_BASE_HPP
#define DB_ENV_BASE_HPP

// standard includes
#include <serial/serialbase.hpp>

// generated includes
#include <list>
#include <string>


// forward declarations
class CArgument;
class CDb_Clipboard;
class CFilter_Value;


// generated classes

class CDb_Env_Base : public ncbi::CObject
{
    typedef ncbi::CObject Tparent;
public:
    // constructor
    CDb_Env_Base(void);
    // destructor
    virtual ~CDb_Env_Base(void);

    // type info
    DECLARE_INTERNAL_TYPE_INFO();

    // members' types
    typedef std::string TName;
    typedef std::list< ncbi::CRef< CArgument > > TArguments;
    typedef std::list< ncbi::CRef< CFilter_Value > > TFilters;
    typedef std::list< ncbi::CRef< CDb_Clipboard > > TClipboard;

    // members' getters
    // members' setters
    void ResetName(void);
    const std::string& GetName(void) const;
    void SetName(const std::string& value);
    std::string& SetName(void);

    bool IsSetArguments(void) const;
    void ResetArguments(void);
    const std::list< ncbi::CRef< CArgument > >& GetArguments(void) const;
    std::list< ncbi::CRef< CArgument > >& SetArguments(void);

    bool IsSetFilters(void) const;
    void ResetFilters(void);
    const std::list< ncbi::CRef< CFilter_Value > >& GetFilters(void) const;
    std::list< ncbi::CRef< CFilter_Value > >& SetFilters(void);

    bool IsSetClipboard(void) const;
    void ResetClipboard(void);
    const std::list< ncbi::CRef< CDb_Clipboard > >& GetClipboard(void) const;
    std::list< ncbi::CRef< CDb_Clipboard > >& SetClipboard(void);

    // reset whole object
    virtual void Reset(void);


private:
    // Prohibit copy constructor and assignment operator
    CDb_Env_Base(const CDb_Env_Base&);
    CDb_Env_Base& operator=(const CDb_Env_Base&);

    // members' data
    TName m_Name;
    TArguments m_Arguments;
    TFilters m_Filters;
    TClipboard m_Clipboard;
};






///////////////////////////////////////////////////////////
///////////////////// inline methods //////////////////////
///////////////////////////////////////////////////////////
inline
const CDb_Env_Base::TName& CDb_Env_Base::GetName(void) const
{
    return m_Name;
}

inline
void CDb_Env_Base::SetName(const TName& value)
{
    m_Name = value;
}

inline
CDb_Env_Base::TName& CDb_Env_Base::SetName(void)
{
    return m_Name;
}

inline
bool CDb_Env_Base::IsSetArguments(void) const
{
    return !(m_Arguments).empty();
}

inline
const CDb_Env_Base::TArguments& CDb_Env_Base::GetArguments(void) const
{
    return m_Arguments;
}

inline
CDb_Env_Base::TArguments& CDb_Env_Base::SetArguments(void)
{
    return m_Arguments;
}

inline
bool CDb_Env_Base::IsSetFilters(void) const
{
    return !(m_Filters).empty();
}

inline
const CDb_Env_Base::TFilters& CDb_Env_Base::GetFilters(void) const
{
    return m_Filters;
}

inline
CDb_Env_Base::TFilters& CDb_Env_Base::SetFilters(void)
{
    return m_Filters;
}

inline
bool CDb_Env_Base::IsSetClipboard(void) const
{
    return !(m_Clipboard).empty();
}

inline
const CDb_Env_Base::TClipboard& CDb_Env_Base::GetClipboard(void) const
{
    return m_Clipboard;
}

inline
CDb_Env_Base::TClipboard& CDb_Env_Base::SetClipboard(void)
{
    return m_Clipboard;
}

///////////////////////////////////////////////////////////
////////////////// end of inline methods //////////////////
///////////////////////////////////////////////////////////






#endif // DB_ENV_BASE_HPP
