/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Author:  .......
 *
 * File Description:
 *   .......
 *
 * Remark:
 *   This code was originally generated by application DATATOOL
 *   using specifications from the data definition file
 *   'twebenv.asn'.
 */

#ifndef FULL_TIME_HPP
#define FULL_TIME_HPP


// generated includes
#include "Full_Time_.hpp"

// generated classes

class CFull_Time : public CFull_Time_Base
{
    typedef CFull_Time_Base Tparent;
public:
    // constructor
    CFull_Time(void);
    // destructor
    ~CFull_Time(void);

private:
    // Prohibit copy constructor and assignment operator
    CFull_Time(const CFull_Time& value);
    CFull_Time& operator=(const CFull_Time& value);

};



/////////////////// CFull_Time inline methods

// constructor
inline
CFull_Time::CFull_Time(void)
{
}


/////////////////// end of CFull_Time inline methods



/*
* ===========================================================================
*
* $Log$
* Revision 1.2  2004/01/21 15:18:19  grichenk
* Re-arranged webenv files for serial test
*
*
* ===========================================================================
*/

#endif // FULL_TIME_HPP
/* Original file checksum: lines: 85, chars: 2212, CRC32: 84734f27 */
