Variation ::= {
  id {
    db "dbSNP",
    tag str "rs61752872"
  },
  variant-prop {
    version 5,
    resource-link 29,
    gene-location intron,
    effect no-change,
    mapping 0,
    frequency-based-validation 0,
    genotype 0,
    quality-check 0
  },
  data set {
    type package,
    variations {
      {
        placements {
          {
            loc pnt {
              point 68910540,
              id other {
                accession "NC_000001",
                version 10
              }
            },
            mol genomic
          }
        },
        data set {
          type package,
          variations {
            {
              data instance {
                type snv,
                delta {
                  {
                    seq literal {
                      length 1,
                      seq-data iupacna "A"
                    }
                  }
                }
              }
            },
            {
              data instance {
                type identity,
                delta {
                  {
                    seq literal {
                      length 1,
                      seq-data iupacna "G"
                    }
                  }
                },
                observation reference
              }
            }
          }
        }
      }
    }
  }
}
Variation ::= {
  id {
    db "dbSNP",
    tag str "rs61752872"
  },
  variant-prop {
    version 5,
    resource-link 29,
    gene-location intron,
    effect no-change,
    mapping 0,
    frequency-based-validation 0,
    genotype 0,
    quality-check 0
  },
  data set {
    type package,
    variations {
      {
        placements {
          {
            loc pnt {
              point 68910540,
              id other {
                accession "NC_000001",
                version 10
              }
            },
            mol genomic
          }
        },
        data set {
          type package,
          variations {
            {
              data instance {
                type snv,
                delta {
                  {
                    seq literal {
                      length 1,
                      seq-data iupacna "A"
                    }
                  }
                }
              }
            },
            {
              data instance {
                type identity,
                delta {
                  {
                    seq literal {
                      length 1,
                      seq-data iupacna "G"
                    }
                  }
                },
                observation reference
              }
            }
          }
        }
      }
    }
  }
}
Variation ::= {
  id {
    db "dbSNP",
    tag str "rs61752872"
  },
  variant-prop {
    version 5,
    resource-link 29,
    gene-location intron,
    effect no-change,
    mapping 0,
    frequency-based-validation 0,
    genotype 0,
    quality-check 0
  },
  data set {
    type package,
    variations {
      {
        placements {
          {
            loc pnt {
              point 68910540,
              id other {
                accession "NC_000001",
                version 10
              }
            },
            mol genomic
          }
        },
        data set {
          type package,
          variations {
            {
              data instance {
                type snv,
                delta {
                  {
                    seq literal {
                      length 1,
                      seq-data iupacna "T"
                    }
                  }
                }
              }
            },
            {
              data instance {
                type snv,
                delta {
                  {
                    seq literal {
                      length 1,
                      seq-data iupacna "A"
                    }
                  }
                },
                observation 5
              }
            },
            {
              data instance {
                type identity,
                delta {
                  {
                    seq literal {
                      length 1,
                      seq-data iupacna "G"
                    }
                  }
                },
                observation reference
              }
            }
          }
        }
      }
    }
  }
}
