# Find Berkley DB

if (APPLE)
    set(BUILD_PREFIX "Clang320-")
endif (APPLE)

FIND_PATH( BERKELEYDB_INCLUDE db.h 
    PATHS ${NCBI_TOOLS_ROOT}/BerkeleyDB/include/
    NO_DEFAULT_PATH )

IF (BERKELEYDB_INCLUDE)
    FIND_LIBRARY( BERKELEYDB_LIBRARY NAMES db
        PATHS ${CMAKE_PREFIX_PATH} "${NCBI_TOOLS_ROOT}/BerkeleyDB/${BUILD_PREFIX}${CMAKE_BUILD_TYPE}/"
        NO_DEFAULT_PATH )

    IF (BERKELEYDB_LIBRARY)
        get_filename_component(BERKELEYDB_LIBDIR ${BERKELEYDB_LIBRARY} DIRECTORY)
        set(BERKELEYDB_FOUND true)
        set(BERKELEYDB_LIBS -L${BERKELEYDB_LIBDIR} -ldb -Wl,-rpath,${BERKELEYDB_LIBDIR})
    ELSE (BERKELEYDB_LIBRARY)
        MESSAGE(WARNING "Include ${BERKELEYDB_INCLUDE}/db_cxx.h found, but no library in ${NCBI_TOOLS_ROOT}/BerkeleyDB/${BUILD_PREFIX}${CMAKE_BUILD_TYPE}/ ")
    ENDIF (BERKELEYDB_LIBRARY)

    MESSAGE(STATUS "Found BerkeleyDB: ${BERKELEYDB_LIBRARY}")
    MESSAGE(STATUS "      BerkeleyDB LIBS: ${BERKELEYDB_LIBS}")
ENDIF (BERKELEYDB_INCLUDE)
