# Find Berkley DB

if (APPLE)
    set(BUILD_PREFIX "Clang320-")
endif (APPLE)

FIND_PATH( BERKELEYDB_INCLUDE db.h 
    PATHS ${NCBI_TOOLS_ROOT}/BerkeleyDB/include/
    NO_DEFAULT_PATH )

IF (BERKELEYDB_INCLUDE)
    FIND_LIBRARY( BERKELEYDB_LIBRARY NAMES db
        PATHS "${NCBI_TOOLS_ROOT}/BerkeleyDB/${BUILD_PREFIX}${CMAKE_BUILD_TYPE}/"
        NO_DEFAULT_PATH )

    IF (BERKELEYDB_LIBRARY)
        set(BERKELEYDB_FOUND true)
        set(BERKELEYDB_LIBS -L"${NCBI_TOOLS_ROOT}/BerkeleyDB/${BUILD_PREFIX}${CMAKE_BUILD_TYPE}/" -ldb -Wl,-rpath,"${NCBI_TOOLS_ROOT}/BerkeleyDB/${BUILD_PREFIX}${CMAKE_BUILD_TYPE}/")
    ELSE (BERKELEYDB_LIBRARY)
        MESSAGE(WARNING "Include ${BERKELEYDB_INCLUDE}/db_cxx.h found, but no library in ${NCBI_TOOLS_ROOT}/BerkeleyDB/${BUILD_PREFIX}${CMAKE_BUILD_TYPE}/ ")
    ENDIF (BERKELEYDB_LIBRARY)
ENDIF (BERKELEYDB_INCLUDE)
