#


###  PATH TO A PRE-BUILT C++ TOOLKIT
include Makefile.builddir


###  DEFAULT COMPILATION FLAGS  -- DON'T EDIT OR MOVE THESE LINES !!!
include $(builddir)/Makefile.mk
srcdir = .
BINCOPY = @:
LOCAL_CPPFLAGS = -I.
LOCAL_LDFLAGS = -L.
ORIG_LDFLAGS = $(LOCAL_LDFLAGS) $(CONF_LDFLAGS)
LDFLAGS = $(ORIG_LDFLAGS)


###  PROJECT-SPECIFIC SETTINGS, SUITABLE FOR IN-TREE USE
include Makefile.DdRpc.lib

###  APPLICATION BUILD RULES -- DON'T EDIT OR MOVE THESE 2 LINES !!!
include $(builddir)/Makefile.lib
MAKEFILE = Makefile.DdRpc_lib

###  Kludge around issues with potentially-absent .dep and .files files
$(status_dir)/.%.dep:;
$(status_dir)/.%.files:;


###  PUT YOUR OWN ADDITIONAL TARGETS (MAKE COMMANDS/RULES) BELOW HERE
