Bioseq-set ::= {
  seq-set {
    seq {
      id {
        local str "BasicObj3"
      },
      descr {
        update-date std {
          year 2013,
          month 5,
          day 13
        },
        create-date std {
          year 2013,
          month 5,
          day 13
        }
      },
      inst {
        repr delta,
        mol dna,
        length 458,
        ext delta {
          loc int {
            from 10,
            to 87,
            strand plus,
            id local str "U54469.1"
          },
          literal {
            length 26
          },
          loc int {
            from 103,
            to 218,
            strand minus,
            id genbank {
              accession "U54469",
              version 1
            }
          },
          literal {
            length 100,
            fuzz lim unk
          },
          loc int {
            from 20,
            to 47,
            strand plus,
            id genbank {
              accession "U54470",
              version 1
            }
          },
          literal {
            length 100
          },
          loc int {
            from 5,
            to 14,
            strand plus,
            id genbank {
              accession "U54471",
              version 1
            }
          }
        }
      }
    },
    seq {
      id {
        local str "BasicObj4"
      },
      descr {
        update-date std {
          year 2013,
          month 5,
          day 13
        },
        create-date std {
          year 2013,
          month 5,
          day 13
        }
      },
      inst {
        repr delta,
        mol dna,
        length 478,
        ext delta {
          loc int {
            from 10,
            to 87,
            strand plus,
            id local str "U54469.1"
          },
          literal {
            length 26
          },
          loc int {
            from 103,
            to 218,
            strand minus,
            id genbank {
              accession "U54469",
              version 1
            }
          },
          literal {
            length 100,
            fuzz lim unk
          },
          loc int {
            from 20,
            to 47,
            strand plus,
            id genbank {
              accession "U54470",
              version 1
            }
          },
          literal {
            length 100
          },
          loc int {
            from 5,
            to 34,
            strand plus,
            id genbank {
              accession "U54472",
              version 1
            }
          }
        }
      }
    }
  }
}
