#!/bin/sh
#Template compare method

#Environment variables provided by the framework
#$NCBI_TESTRES_UNIT                 Name of the test unit
#$NCBI_TESTRES_RESOURCE1            Name of the resource #1
#$NCBI_TESTRES_RESOURCE2            Name of the resource #2
#$NCBI_TESTRES_RUN_DIR1             Working directory of the test run method for resource #1
#$NCBI_TESTRES_RUN_DIR2             Working directory of the test run method for resource #2
#$NCBI_TESTRES_RESULT               Name of the result file
#$NCBI_TESTRES_VERSION_DIR          Name of the test version configuration directory (R/O)
#$NCBI_TESTRES_TEST_DIR             Name of the test configuration directory (R/O)
#$NCBI_TESTRES_WORK_DIR              Name of the specially created working directory (R/W)#$NCBI_TESTRES_UNIT
#$NCBI_TESTRES_INIT_DIR             Name of the initialization script dir results

echo ?Success!? > 1>&2
exit 0

