/*  $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Authors:  Josh Cherry
 *
 * File Description:  SWIG interface file for algo_ms
 *
 */

%%

objects/omssa/MSChargeHandle.hpp
objects/omssa/MSChargeHandle_.hpp
objects/omssa/MSEnzymes.hpp
objects/omssa/MSEnzymes_.hpp
objects/omssa/MSHitError.hpp
objects/omssa/MSHitError_.hpp
objects/omssa/MSHits.hpp
objects/omssa/MSHits_.hpp
objects/omssa/MSHitSet.hpp
objects/omssa/MSHitSet_.hpp
objects/omssa/MSIonType.hpp
objects/omssa/MSIonType_.hpp
objects/omssa/MSMod.hpp
objects/omssa/MSMod_.hpp
objects/omssa/MSModHit.hpp
objects/omssa/MSModHit_.hpp
objects/omssa/MSMZHit.hpp
objects/omssa/MSMZHit_.hpp
objects/omssa/MSPepHit.hpp
objects/omssa/MSPepHit_.hpp
objects/omssa/MSRequest.hpp
objects/omssa/MSRequest_.hpp
objects/omssa/MSResponse.hpp
objects/omssa/MSResponse_.hpp
objects/omssa/MSResponseError.hpp
objects/omssa/MSResponseError_.hpp
objects/omssa/MSSearch.hpp
objects/omssa/MSSearch_.hpp
objects/omssa/MSSearchSettings.hpp
objects/omssa/MSSearchSettings_.hpp
objects/omssa/MSSpectrum.hpp
objects/omssa/MSSpectrum_.hpp
objects/omssa/MSSpectrumset.hpp
objects/omssa/MSSpectrumset_.hpp
objects/omssa/NameValue.hpp
objects/omssa/NameValue_.hpp

%%

/*
 * ===========================================================================
 * $Log$
 * Revision 1.1  2005/05/11 21:27:35  jcherry
 * Initial version
 *
 * ===========================================================================
 */
