/*  $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Authors:  Josh Cherry
 *
 * File Description:  SWIG interface file for data_loaders
 *
 */

%%

objtools/data_loaders/loaders.hpp

objtools/data_loaders/blastdb/bdbloader.hpp

objtools/data_loaders/cdd/cdd.hpp

objtools/data_loaders/genbank/gbload_util.hpp
objtools/data_loaders/genbank/gbloader.hpp

objtools/data_loaders/lds/lds_dataloader.hpp

objtools/data_loaders/patcher/loaderpatcher.hpp

objtools/data_loaders/trace/trace_chgr.hpp

objtools/data_loaders/genbank/blob_id.hpp
objtools/data_loaders/genbank/cache_manager.hpp
objtools/data_loaders/genbank/dispatcher.hpp
objtools/data_loaders/genbank/processor.hpp
objtools/data_loaders/genbank/processors.hpp
objtools/data_loaders/genbank/reader.hpp
objtools/data_loaders/genbank/reader_id1_base.hpp
objtools/data_loaders/genbank/reader_interface.hpp
objtools/data_loaders/genbank/reader_snp.hpp
objtools/data_loaders/genbank/request_result.hpp
objtools/data_loaders/genbank/seqref.hpp
objtools/data_loaders/genbank/split_parser.hpp
objtools/data_loaders/genbank/statistics.hpp
objtools/data_loaders/genbank/writer.hpp
objtools/data_loaders/genbank/writer_interface.hpp

objtools/data_loaders/genbank/readers/readers.hpp

objtools/data_loaders/genbank/readers/cache/reader_cache.hpp
objtools/data_loaders/genbank/readers/cache/reader_cache_entry.hpp
objtools/data_loaders/genbank/readers/cache/writer_cache.hpp
objtools/data_loaders/genbank/readers/cache/writer_cache_entry.hpp

objtools/data_loaders/genbank/readers/id1/reader_id1.hpp
objtools/data_loaders/genbank/readers/id1/reader_id1_entry.hpp

objtools/data_loaders/genbank/readers/id2/reader_id2.hpp
objtools/data_loaders/genbank/readers/id2/reader_id2_entry.hpp

objtools/data_loaders/genbank/readers/pubseqos/reader_pubseq.hpp
objtools/data_loaders/genbank/readers/pubseqos/reader_pubseq_entry.hpp

objtools/data_loaders/genbank/readers/pubseqos2/reader_pubseq2.hpp
objtools/data_loaders/genbank/readers/pubseqos2/reader_pubseq2_entry.hpp

%%
