/*  $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Authors:  Josh Cherry
 *
 * File Description:  SWIG interface file for data_loaders
 *
 */

%%

objtools/data_loaders/cdd/cdd.hpp
objtools/data_loaders/genbank/gbload_util.hpp
objtools/data_loaders/genbank/gbloader.hpp
objtools/data_loaders/lds/lds_dataloader.hpp
objtools/data_loaders/table/sage_dload.hpp
objtools/data_loaders/table/sqlite_table.hpp
objtools/data_loaders/table/user_feature_dload.hpp
objtools/data_loaders/table/table.hpp
objtools/data_loaders/trace/trace_chgr.hpp
objtools/data_loaders/lds/lds_dataloader.hpp
objtools/data_loaders/genbank/reader.hpp
objtools/data_loaders/genbank/reader_snp.hpp
objtools/data_loaders/genbank/request_result.hpp
objtools/data_loaders/genbank/seqref.hpp
objtools/data_loaders/genbank/split_parser.hpp
objtools/data_loaders/genbank/readers/id1/reader_id1.hpp
objtools/data_loaders/genbank/statistics.hpp
objtools/data_loaders/genbank/readers/pubseqos/reader_pubseq.hpp

%%

/*
 * ===========================================================================
 * $Log$
 * Revision 1.1  2005/05/11 21:27:35  jcherry
 * Initial version
 *
 * ===========================================================================
 */
