/*  $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Authors:  Josh Cherry
 *
 * File Description:  SWIG interface file for general
 *
 */

%%

objects/general/Date.hpp
objects/general/Date_.hpp
objects/general/Date_std.hpp
objects/general/Date_std_.hpp
objects/general/Dbtag.hpp
objects/general/Dbtag_.hpp
objects/general/Int_fuzz.hpp
objects/general/Int_fuzz_.hpp
objects/general/Name_std.hpp
objects/general/Name_std_.hpp
objects/general/Object_id.hpp
objects/general/Object_id_.hpp
objects/general/Person_id.hpp
objects/general/Person_id_.hpp
objects/general/User_field.hpp
objects/general/User_field_.hpp
objects/general/User_object.hpp
objects/general/User_object_.hpp

%%

/*
 * ===========================================================================
 * $Log$
 * Revision 1.1  2005/05/11 21:27:35  jcherry
 * Initial version
 *
 * ===========================================================================
 */
