/*  $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Authors:  Josh Cherry
 *
 * File Description:  SWIG interface file for pub
 *
 */

%%

objects/biblio/Affil.hpp
objects/biblio/Affil_.hpp
objects/biblio/ArticleId.hpp
objects/biblio/ArticleId_.hpp
objects/biblio/ArticleIdSet.hpp
objects/biblio/ArticleIdSet_.hpp
objects/biblio/Auth_list.hpp
objects/biblio/Auth_list_.hpp
objects/biblio/Author.hpp
objects/biblio/Author_.hpp
objects/biblio/Cit_art.hpp
objects/biblio/Cit_art_.hpp
objects/biblio/Cit_book.hpp
objects/biblio/Cit_book_.hpp
objects/biblio/Cit_gen.hpp
objects/biblio/Cit_gen_.hpp
objects/biblio/Cit_jour.hpp
objects/biblio/Cit_jour_.hpp
objects/biblio/Cit_let.hpp
objects/biblio/Cit_let_.hpp
objects/biblio/Cit_pat.hpp
objects/biblio/Cit_pat_.hpp
objects/biblio/Cit_proc.hpp
objects/biblio/Cit_proc_.hpp
objects/biblio/Cit_sub.hpp
objects/biblio/Cit_sub_.hpp
objects/biblio/CitRetract.hpp
objects/biblio/CitRetract_.hpp
objects/biblio/DOI.hpp
objects/biblio/DOI_.hpp
objects/biblio/Id_pat.hpp
objects/biblio/Id_pat_.hpp
objects/biblio/Imprint.hpp
objects/biblio/Imprint_.hpp
objects/biblio/label_util.hpp
objects/biblio/MedlineUID.hpp
objects/biblio/MedlineUID_.hpp
objects/biblio/Meeting.hpp
objects/biblio/Meeting_.hpp
objects/biblio/Patent_priority.hpp
objects/biblio/Patent_priority_.hpp
objects/biblio/PII.hpp
objects/biblio/PII_.hpp
objects/biblio/PmcID.hpp
objects/biblio/PmcID_.hpp
objects/biblio/PmcPid.hpp
objects/biblio/PmcPid_.hpp
objects/biblio/PmPid.hpp
objects/biblio/PmPid_.hpp
objects/biblio/PubMedId.hpp
objects/biblio/PubMedId_.hpp
objects/biblio/PubStatus.hpp
objects/biblio/PubStatus_.hpp
objects/biblio/PubStatusDate.hpp
objects/biblio/PubStatusDate_.hpp
objects/biblio/PubStatusDateSet.hpp
objects/biblio/PubStatusDateSet_.hpp
objects/biblio/Title.hpp
objects/biblio/Title_.hpp
objects/biblio/label_util.hpp
objects/medlars/Medlars_entry.hpp
objects/medlars/Medlars_entry_.hpp
objects/medlars/Medlars_record.hpp
objects/medlars/Medlars_record_.hpp
objects/medline/DocRef.hpp
objects/medline/DocRef_.hpp
objects/medline/Medline_entry.hpp
objects/medline/Medline_entry_.hpp
objects/medline/Medline_field.hpp
objects/medline/Medline_field_.hpp
objects/medline/Medline_mesh.hpp
objects/medline/Medline_mesh_.hpp
objects/medline/Medline_qual.hpp
objects/medline/Medline_qual_.hpp
objects/medline/Medline_rn.hpp
objects/medline/Medline_rn_.hpp
objects/medline/Medline_si.hpp
objects/medline/Medline_si_.hpp
objects/mla/Error_val.hpp
objects/mla/Error_val_.hpp
objects/mla/Mla_back.hpp
objects/mla/Mla_back_.hpp
objects/mla/mla_client.hpp
objects/mla/mla_client_.hpp
objects/mla/Mla_request.hpp
objects/mla/Mla_request_.hpp
objects/mla/Title_msg.hpp
objects/mla/Title_msg_.hpp
objects/mla/Title_msg_list.hpp
objects/mla/Title_msg_list_.hpp
objects/mla/Title_type.hpp
objects/mla/Title_type_.hpp
objects/pub/Pub.hpp
objects/pub/Pub_.hpp
objects/pub/Pub_equiv.hpp
objects/pub/Pub_equiv_.hpp
objects/pub/Pub_set.hpp
objects/pub/Pub_set_.hpp
objects/pubmed/Pubmed_entry.hpp
objects/pubmed/Pubmed_entry_.hpp
objects/pubmed/Pubmed_url.hpp
objects/pubmed/Pubmed_url_.hpp

%%

/*
 * ===========================================================================
 * $Log$
 * Revision 1.1  2005/05/11 21:27:35  jcherry
 * Initial version
 *
 * ===========================================================================
 */
