/*  $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Authors:  Josh Cherry
 *
 * File Description:  SWIG interface file for pub_chem
 *
 */

%%

objects/pcsubstance/PC_AtomInt.hpp
objects/pcsubstance/PC_AtomInt_.hpp
objects/pcsubstance/PC_AtomRadical.hpp
objects/pcsubstance/PC_AtomRadical_.hpp
objects/pcsubstance/PC_AtomSource.hpp
objects/pcsubstance/PC_AtomSource_.hpp
objects/pcsubstance/PC_AtomString.hpp
objects/pcsubstance/PC_AtomString_.hpp
objects/pcsubstance/PC_Atoms.hpp
objects/pcsubstance/PC_Atoms_.hpp
objects/pcsubstance/PC_BondAnnotation.hpp
objects/pcsubstance/PC_BondAnnotation_.hpp
objects/pcsubstance/PC_BondType.hpp
objects/pcsubstance/PC_BondType_.hpp
objects/pcsubstance/PC_Bonds.hpp
objects/pcsubstance/PC_Bonds_.hpp
objects/pcsubstance/PC_Compound.hpp
objects/pcsubstance/PC_CompoundType.hpp
objects/pcsubstance/PC_CompoundType_.hpp
objects/pcsubstance/PC_Compound_.hpp
objects/pcsubstance/PC_Compounds.hpp
objects/pcsubstance/PC_Compounds_.hpp
objects/pcsubstance/PC_Conformer.hpp
objects/pcsubstance/PC_Conformer_.hpp
objects/pcsubstance/PC_CoordinateType.hpp
objects/pcsubstance/PC_CoordinateType_.hpp
objects/pcsubstance/PC_Coordinates.hpp
objects/pcsubstance/PC_Coordinates_.hpp
objects/pcsubstance/PC_Count.hpp
objects/pcsubstance/PC_Count_.hpp
objects/pcsubstance/PC_DBTracking.hpp
objects/pcsubstance/PC_DBTracking_.hpp
objects/pcsubstance/PC_DrawAnnotations.hpp
objects/pcsubstance/PC_DrawAnnotations_.hpp
objects/pcsubstance/PC_Element.hpp
objects/pcsubstance/PC_Element_.hpp
objects/pcsubstance/PC_ID.hpp
objects/pcsubstance/PC_ID_.hpp
objects/pcsubstance/PC_InfoData.hpp
objects/pcsubstance/PC_InfoData_.hpp
objects/pcsubstance/PC_MMDBSource.hpp
objects/pcsubstance/PC_MMDBSource_.hpp
objects/pcsubstance/PC_Source.hpp
objects/pcsubstance/PC_Source_.hpp
objects/pcsubstance/PC_StereoCenter.hpp
objects/pcsubstance/PC_StereoCenter_.hpp
objects/pcsubstance/PC_StereoGroup.hpp
objects/pcsubstance/PC_StereoGroup_.hpp
objects/pcsubstance/PC_StereoOctahedral.hpp
objects/pcsubstance/PC_StereoOctahedral_.hpp
objects/pcsubstance/PC_StereoPentagonalBiPyram.hpp
objects/pcsubstance/PC_StereoPentagonalBiPyram_.hpp
objects/pcsubstance/PC_StereoPlanar.hpp
objects/pcsubstance/PC_StereoPlanar_.hpp
objects/pcsubstance/PC_StereoSquarePlanar.hpp
objects/pcsubstance/PC_StereoSquarePlanar_.hpp
objects/pcsubstance/PC_StereoTShape.hpp
objects/pcsubstance/PC_StereoTShape_.hpp
objects/pcsubstance/PC_StereoTetrahedral.hpp
objects/pcsubstance/PC_StereoTetrahedral_.hpp
objects/pcsubstance/PC_StereoTrigonalBiPyramid.hpp
objects/pcsubstance/PC_StereoTrigonalBiPyramid_.hpp
objects/pcsubstance/PC_Substance.hpp
objects/pcsubstance/PC_Substance_.hpp
objects/pcsubstance/PC_Substances.hpp
objects/pcsubstance/PC_Substances_.hpp
objects/pcsubstance/PC_Urn.hpp
objects/pcsubstance/PC_UrnDataType.hpp
objects/pcsubstance/PC_UrnDataType_.hpp
objects/pcsubstance/PC_Urn_.hpp
objects/pcsubstance/PC_XRefData.hpp
objects/pcsubstance/PC_XRefData_.hpp

objects/pcassay/PC_ActElement.hpp
objects/pcassay/PC_ActElement_.hpp
objects/pcassay/PC_ActOperator.hpp
objects/pcassay/PC_ActOperator_.hpp
objects/pcassay/PC_ActStatement.hpp
objects/pcassay/PC_ActStatement_.hpp
objects/pcassay/PC_ActSummary.hpp
objects/pcassay/PC_ActSummary_.hpp
objects/pcassay/PC_ActValue.hpp
objects/pcassay/PC_ActValue_.hpp
objects/pcassay/PC_AssayContainer.hpp
objects/pcassay/PC_AssayContainer_.hpp
objects/pcassay/PC_AssayData.hpp
objects/pcassay/PC_AssayDataSession.hpp
objects/pcassay/PC_AssayDataSession_.hpp
objects/pcassay/PC_AssayData_.hpp
objects/pcassay/PC_AssayDescription.hpp
objects/pcassay/PC_AssayDescription_.hpp
objects/pcassay/PC_AssayResults.hpp
objects/pcassay/PC_AssayResults_.hpp
objects/pcassay/PC_AssaySubmit.hpp
objects/pcassay/PC_AssaySubmit_.hpp
objects/pcassay/PC_ResultType.hpp
objects/pcassay/PC_ResultType_.hpp

%%

/*
 * ===========================================================================
 * $Log$
 * Revision 1.1  2005/05/11 21:27:35  jcherry
 * Initial version
 *
 * ===========================================================================
 */
