#define IDD_PTB_GUI_DIALOG              100
#define IDC_STATIC_TITLE               1000
#define IDC_STATIC_ROOT                1001
#define IDC_EDIT_ROOT                  1002
#define IDC_STATIC_SUBTREE             1003
#define IDC_EDIT_SUBTREE               1004
#define IDC_STATIC_SLN                 1005
#define IDC_EDIT_SLN                   1006
#define IDC_CHECK_DLL                  1007
#define IDC_CHECK_NOPTB                1008
#define IDC_CHECK_EXT                  1009
#define IDC_CHECK_NWT                  1010
#define IDC_STATIC_EXTROOT             1011
#define IDC_EDIT_EXTROOT               1012
#define IDC_STATIC_PROJTAG             1013
#define IDC_EDIT_PROJTAG               1014
#define IDC_STATIC_FRAME               1015
