Seq-annot ::= {
  data ftable {
    {
      data variation {
        name "NM_004584.2:c.-91_-90insGCGGGG",
        data instance {
          type ins,
          delta {
            {
              seq literal {
                length 6,
                seq-data iupacna "GCGGGG"
              },
              action ins-before
            }
          }
        }
      },
      location int {
        from 2,
        to 3,
        strand plus,
        id gi 19924112
      }
    }
  }
}
