Bioseq ::= {
  id {
    local str "dummy"
  },
  descr {
    source {
      genome proviral,
      org {
        taxname "Homo sapiens",
        common "val34_1",
        db {
          {
            db "notag",
            tag str "?"
          },
          {
            db "database",
            tag str "tag"
          }
        },
        orgname {
          mod {
            {
              subtype acronym,
              subname "val35_0"
            },
            {
              subtype acronym,
              subname "val36_0"
            },
            {
              subtype acronym,
              subname "val36_1"
            },
            {
              subtype anamorph,
              subname "val63_0"
            },
            {
              subtype anamorph,
              subname "val64_0"
            },
            {
              subtype anamorph,
              subname "val64_1"
            },
            {
              subtype authority,
              subname "val51_0"
            },
            {
              subtype authority,
              subname "val52_0"
            },
            {
              subtype authority,
              subname "val52_1"
            },
            {
              subtype bio-material,
              subname "val88_0"
            },
            {
              subtype bio-material,
              subname "val85_0"
            },
            {
              subtype bio-material,
              subname "val86_0"
            },
            {
              subtype bio-material,
              subname "val86_1"
            },
            {
              subtype bio-material,
              subname "val87_0"
            },
            {
              subtype biotype,
              subname "val25_0"
            },
            {
              subtype biotype,
              subname "val26_0"
            },
            {
              subtype biotype,
              subname "val26_1"
            },
            {
              subtype biovar,
              subname "val23_0"
            },
            {
              subtype biovar,
              subname "val24_0"
            },
            {
              subtype biovar,
              subname "val24_1"
            },
            {
              subtype breed,
              subname "val67_0"
            },
            {
              subtype breed,
              subname "val68_0"
            },
            {
              subtype breed,
              subname "val68_1"
            },
            {
              subtype chemovar,
              subname "val21_0"
            },
            {
              subtype chemovar,
              subname "val22_0"
            },
            {
              subtype chemovar,
              subname "val22_1"
            },
            {
              subtype cultivar,
              subname "val17_0"
            },
            {
              subtype cultivar,
              subname "val18_0"
            },
            {
              subtype cultivar,
              subname "val18_1"
            },
            {
              subtype culture-collection,
              subname "val84_0"
            },
            {
              subtype culture-collection,
              subname "val81_0"
            },
            {
              subtype culture-collection,
              subname "val82_0"
            },
            {
              subtype culture-collection,
              subname "val82_1"
            },
            {
              subtype culture-collection,
              subname "val83_0"
            },
            {
              subtype ecotype,
              subname "val59_0"
            },
            {
              subtype ecotype,
              subname "val60_0"
            },
            {
              subtype ecotype,
              subname "val60_1"
            },
            {
              subtype forma,
              subname "val53_0"
            },
            {
              subtype forma,
              subname "val54_0"
            },
            {
              subtype forma,
              subname "val54_1"
            },
            {
              subtype forma-specialis,
              subname "val58_0"
            },
            {
              subtype forma-specialis,
              subname "val55_0"
            },
            {
              subtype forma-specialis,
              subname "val56_0"
            },
            {
              subtype forma-specialis,
              subname "val56_1"
            },
            {
              subtype forma-specialis,
              subname "val57_0"
            },
            {
              subtype gb-acronym,
              subname "val72_0"
            },
            {
              subtype gb-acronym,
              subname "val69_0"
            },
            {
              subtype gb-acronym,
              subname "val70_0"
            },
            {
              subtype gb-acronym,
              subname "val70_1"
            },
            {
              subtype gb-acronym,
              subname "val71_0"
            },
            {
              subtype gb-anamorph,
              subname "val76_0"
            },
            {
              subtype gb-anamorph,
              subname "val73_0"
            },
            {
              subtype gb-anamorph,
              subname "val74_0"
            },
            {
              subtype gb-anamorph,
              subname "val74_1"
            },
            {
              subtype gb-anamorph,
              subname "val75_0"
            },
            {
              subtype gb-synonym,
              subname "val80_0"
            },
            {
              subtype gb-synonym,
              subname "val77_0"
            },
            {
              subtype gb-synonym,
              subname "val78_0"
            },
            {
              subtype gb-synonym,
              subname "val78_1"
            },
            {
              subtype gb-synonym,
              subname "val79_0"
            },
            {
              subtype group,
              subname "val27_0"
            },
            {
              subtype group,
              subname "val28_0"
            },
            {
              subtype group,
              subname "val28_1"
            },
            {
              subtype isolate,
              subname "val31_0"
            },
            {
              subtype isolate,
              subname "val32_0"
            },
            {
              subtype isolate,
              subname "val32_1"
            },
            {
              subtype metagenome-source,
              subname "val92_0"
            },
            {
              subtype metagenome-source,
              subname "val89_0"
            },
            {
              subtype metagenome-source,
              subname "val90_0"
            },
            {
              subtype metagenome-source,
              subname "val90_1"
            },
            {
              subtype metagenome-source,
              subname "val91_0"
            },
            {
              subtype nat-host,
              subname "val42_0"
            },
            {
              subtype nat-host,
              subname "val39_0"
            },
            {
              subtype nat-host,
              subname "val40_0"
            },
            {
              subtype nat-host,
              subname "val40_1"
            },
            {
              subtype nat-host,
              subname "val41_0"
            },
            {
              subtype pathovar,
              subname "val19_0"
            },
            {
              subtype pathovar,
              subname "val20_0"
            },
            {
              subtype pathovar,
              subname "val20_1"
            },
            {
              subtype serogroup,
              subname "val13_0"
            },
            {
              subtype serogroup,
              subname "val14_0"
            },
            {
              subtype serogroup,
              subname "val14_1"
            },
            {
              subtype serotype,
              subname "val11_0"
            },
            {
              subtype serotype,
              subname "val12_0"
            },
            {
              subtype serotype,
              subname "val12_1"
            },
            {
              subtype serovar,
              subname "val15_0"
            },
            {
              subtype serovar,
              subname "val16_0"
            },
            {
              subtype serovar,
              subname "val16_1"
            },
            {
              subtype specimen-voucher,
              subname "val50_0"
            },
            {
              subtype specimen-voucher,
              subname "val47_0"
            },
            {
              subtype specimen-voucher,
              subname "val48_0"
            },
            {
              subtype specimen-voucher,
              subname "val48_1"
            },
            {
              subtype specimen-voucher,
              subname "val49_0"
            },
            {
              subtype strain,
              subname "val1_0"
            },
            {
              subtype strain,
              subname "val2_0"
            },
            {
              subtype strain,
              subname "val2_1"
            },
            {
              subtype sub-species,
              subname "val46_0"
            },
            {
              subtype sub-species,
              subname "val43_0"
            },
            {
              subtype sub-species,
              subname "val44_0"
            },
            {
              subtype sub-species,
              subname "val44_1"
            },
            {
              subtype sub-species,
              subname "val45_0"
            },
            {
              subtype subgroup,
              subname "val29_0"
            },
            {
              subtype subgroup,
              subname "val30_0"
            },
            {
              subtype subgroup,
              subname "val30_1"
            },
            {
              subtype substrain,
              subname "val3_0"
            },
            {
              subtype substrain,
              subname "val4_0"
            },
            {
              subtype substrain,
              subname "val4_1"
            },
            {
              subtype subtype,
              subname "val7_0"
            },
            {
              subtype subtype,
              subname "val8_0"
            },
            {
              subtype subtype,
              subname "val8_1"
            },
            {
              subtype synonym,
              subname "val61_0"
            },
            {
              subtype synonym,
              subname "val62_0"
            },
            {
              subtype synonym,
              subname "val62_1"
            },
            {
              subtype teleomorph,
              subname "val65_0"
            },
            {
              subtype teleomorph,
              subname "val66_0"
            },
            {
              subtype teleomorph,
              subname "val66_1"
            },
            {
              subtype type,
              subname "val5_0"
            },
            {
              subtype type,
              subname "val6_0"
            },
            {
              subtype type,
              subname "val6_1"
            },
            {
              subtype type-material,
              subname "val96_0"
            },
            {
              subtype type-material,
              subname "val93_0"
            },
            {
              subtype type-material,
              subname "val94_0"
            },
            {
              subtype type-material,
              subname "val94_1"
            },
            {
              subtype type-material,
              subname "val95_0"
            },
            {
              subtype variety,
              subname "val9_0"
            },
            {
              subtype variety,
              subname "val10_0"
            },
            {
              subtype variety,
              subname "val10_1"
            }
          }
        }
      },
      subtype {
        {
          subtype altitude,
          name "val243_0"
        },
        {
          subtype altitude,
          name "val244_0"
        },
        {
          subtype altitude,
          name "val244_1"
        },
        {
          subtype cell-line,
          name "val124_0"
        },
        {
          subtype cell-line,
          name "val121_0"
        },
        {
          subtype cell-line,
          name "val122_0"
        },
        {
          subtype cell-line,
          name "val122_1"
        },
        {
          subtype cell-line,
          name "val123_0"
        },
        {
          subtype cell-type,
          name "val128_0"
        },
        {
          subtype cell-type,
          name "val125_0"
        },
        {
          subtype cell-type,
          name "val126_0"
        },
        {
          subtype cell-type,
          name "val126_1"
        },
        {
          subtype cell-type,
          name "val127_0"
        },
        {
          subtype chromosome,
          name "val107_0"
        },
        {
          subtype chromosome,
          name "val108_0"
        },
        {
          subtype chromosome,
          name "val108_1"
        },
        {
          subtype clone,
          name "val111_0"
        },
        {
          subtype clone,
          name "val112_0"
        },
        {
          subtype clone,
          name "val112_1"
        },
        {
          subtype clone,
          name "abc"
        },
        {
          subtype clone-lib,
          name "val136_0"
        },
        {
          subtype clone-lib,
          name "val133_0"
        },
        {
          subtype clone-lib,
          name "val134_0"
        },
        {
          subtype clone-lib,
          name "val134_1"
        },
        {
          subtype clone-lib,
          name "val135_0"
        },
        {
          subtype collected-by,
          name "val204_0"
        },
        {
          subtype collected-by,
          name "val201_0"
        },
        {
          subtype collected-by,
          name "val202_0"
        },
        {
          subtype collected-by,
          name "val202_1"
        },
        {
          subtype collected-by,
          name "val203_0"
        },
        {
          subtype collection-date,
          name "val200_0"
        },
        {
          subtype collection-date,
          name "val197_0"
        },
        {
          subtype collection-date,
          name "val198_0"
        },
        {
          subtype collection-date,
          name "val198_1"
        },
        {
          subtype collection-date,
          name "val199_0"
        },
        {
          subtype country,
          name "val175_0"
        },
        {
          subtype country,
          name "val176_0"
        },
        {
          subtype country,
          name "val176_1"
        },
        {
          subtype dev-stage,
          name "val140_0"
        },
        {
          subtype dev-stage,
          name "val137_0"
        },
        {
          subtype dev-stage,
          name "val138_0"
        },
        {
          subtype dev-stage,
          name "val138_1"
        },
        {
          subtype dev-stage,
          name "val139_0"
        },
        {
          subtype endogenous-virus-name,
          name "val182_0"
        },
        {
          subtype endogenous-virus-name,
          name "val179_0"
        },
        {
          subtype endogenous-virus-name,
          name "val180_0"
        },
        {
          subtype endogenous-virus-name,
          name "val180_1"
        },
        {
          subtype endogenous-virus-name,
          name "val181_0"
        },
        {
          subtype environmental-sample,
          name "val188_0"
        },
        {
          subtype environmental-sample,
          name "val185_0"
        },
        {
          subtype environmental-sample,
          name "val186_0"
        },
        {
          subtype environmental-sample,
          name "val186_1"
        },
        {
          subtype environmental-sample,
          name "val187_0"
        },
        {
          subtype frequency,
          name "val141_0"
        },
        {
          subtype frequency,
          name "val142_0"
        },
        {
          subtype frequency,
          name "val142_1"
        },
        {
          subtype genotype,
          name "val117_0"
        },
        {
          subtype genotype,
          name "val118_0"
        },
        {
          subtype genotype,
          name "val118_1"
        },
        {
          subtype germline,
          name "val143_0"
        },
        {
          subtype germline,
          name "val144_0"
        },
        {
          subtype germline,
          name "val144_1"
        },
        {
          subtype haplogroup,
          name "val235_0"
        },
        {
          subtype haplogroup,
          name "val236_0"
        },
        {
          subtype haplogroup,
          name "val236_1"
        },
        {
          subtype haplotype,
          name "val115_0"
        },
        {
          subtype haplotype,
          name "val116_0"
        },
        {
          subtype haplotype,
          name "val116_1"
        },
        {
          subtype identified-by,
          name "val208_0"
        },
        {
          subtype identified-by,
          name "val205_0"
        },
        {
          subtype identified-by,
          name "val206_0"
        },
        {
          subtype identified-by,
          name "val206_1"
        },
        {
          subtype identified-by,
          name "val207_0"
        },
        {
          subtype insertion-seq-name,
          name "val170_0"
        },
        {
          subtype insertion-seq-name,
          name "val167_0"
        },
        {
          subtype insertion-seq-name,
          name "val168_0"
        },
        {
          subtype insertion-seq-name,
          name "val168_1"
        },
        {
          subtype insertion-seq-name,
          name "val169_0"
        },
        {
          subtype isolation-source,
          name "val192_0"
        },
        {
          subtype isolation-source,
          name "val189_0"
        },
        {
          subtype isolation-source,
          name "val190_0"
        },
        {
          subtype isolation-source,
          name "val190_1"
        },
        {
          subtype isolation-source,
          name "val191_0"
        },
        {
          subtype lab-host,
          name "val150_0"
        },
        {
          subtype lab-host,
          name "val147_0"
        },
        {
          subtype lab-host,
          name "val148_0"
        },
        {
          subtype lab-host,
          name "val148_1"
        },
        {
          subtype lab-host,
          name "val149_0"
        },
        {
          subtype lat-lon,
          name "val196_0"
        },
        {
          subtype lat-lon,
          name "val193_0"
        },
        {
          subtype lat-lon,
          name "val194_0"
        },
        {
          subtype lat-lon,
          name "val194_1"
        },
        {
          subtype lat-lon,
          name "val195_0"
        },
        {
          subtype linkage-group,
          name "val234_0"
        },
        {
          subtype linkage-group,
          name "val231_0"
        },
        {
          subtype linkage-group,
          name "val232_0"
        },
        {
          subtype linkage-group,
          name "val232_1"
        },
        {
          subtype linkage-group,
          name "val233_0"
        },
        {
          subtype map,
          name "val109_0"
        },
        {
          subtype map,
          name "val110_0"
        },
        {
          subtype map,
          name "val110_1"
        },
        {
          subtype mating-type,
          name "val230_0"
        },
        {
          subtype mating-type,
          name "val227_0"
        },
        {
          subtype mating-type,
          name "val228_0"
        },
        {
          subtype mating-type,
          name "val228_1"
        },
        {
          subtype mating-type,
          name "val229_0"
        },
        {
          subtype metagenomic,
          name "val225_0"
        },
        {
          subtype metagenomic,
          name "val226_0"
        },
        {
          subtype metagenomic,
          name "val226_1"
        },
        {
          subtype other,
          name "val105_0"
        },
        {
          subtype other,
          name "val106_0"
        },
        {
          subtype other,
          name "val106_1"
        },
        {
          subtype other,
          name "val245_0"
        },
        {
          subtype other,
          name "val246_0"
        },
        {
          subtype other,
          name "val246_1"
        },
        {
          subtype other,
          name "val246_0"
        },
        {
          subtype phenotype,
          name "val241_0"
        },
        {
          subtype phenotype,
          name "val242_0"
        },
        {
          subtype phenotype,
          name "val242_1"
        },
        {
          subtype plasmid-name,
          name "val162_0"
        },
        {
          subtype plasmid-name,
          name "val159_0"
        },
        {
          subtype plasmid-name,
          name "val160_0"
        },
        {
          subtype plasmid-name,
          name "val160_1"
        },
        {
          subtype plasmid-name,
          name "val161_0"
        },
        {
          subtype plastid-name,
          name "val174_0"
        },
        {
          subtype plastid-name,
          name "val171_0"
        },
        {
          subtype plastid-name,
          name "val172_0"
        },
        {
          subtype plastid-name,
          name "val172_1"
        },
        {
          subtype plastid-name,
          name "val173_0"
        },
        {
          subtype pop-variant,
          name "val154_0"
        },
        {
          subtype pop-variant,
          name "val151_0"
        },
        {
          subtype pop-variant,
          name "val152_0"
        },
        {
          subtype pop-variant,
          name "val152_1"
        },
        {
          subtype pop-variant,
          name "val153_0"
        },
        {
          subtype rearranged,
          name "val145_0"
        },
        {
          subtype rearranged,
          name "val146_0"
        },
        {
          subtype rearranged,
          name "val146_1"
        },
        {
          subtype segment,
          name "val177_0"
        },
        {
          subtype segment,
          name "val178_0"
        },
        {
          subtype segment,
          name "val178_1"
        },
        {
          subtype sex,
          name "val119_0"
        },
        {
          subtype sex,
          name "val120_0"
        },
        {
          subtype sex,
          name "val120_1"
        },
        {
          subtype subclone,
          name "val113_0"
        },
        {
          subtype subclone,
          name "val114_0"
        },
        {
          subtype subclone,
          name "val114_1"
        },
        {
          subtype tissue-lib,
          name "val158_0"
        },
        {
          subtype tissue-lib,
          name "val155_0"
        },
        {
          subtype tissue-lib,
          name "val156_0"
        },
        {
          subtype tissue-lib,
          name "val156_1"
        },
        {
          subtype tissue-lib,
          name "val157_0"
        },
        {
          subtype tissue-type,
          name "val132_0"
        },
        {
          subtype tissue-type,
          name "val129_0"
        },
        {
          subtype tissue-type,
          name "val130_0"
        },
        {
          subtype tissue-type,
          name "val130_1"
        },
        {
          subtype tissue-type,
          name "val131_0"
        },
        {
          subtype transgenic,
          name "val183_0"
        },
        {
          subtype transgenic,
          name "val184_0"
        },
        {
          subtype transgenic,
          name "val184_1"
        },
        {
          subtype transposon-name,
          name "val166_0"
        },
        {
          subtype transposon-name,
          name "val163_0"
        },
        {
          subtype transposon-name,
          name "val164_0"
        },
        {
          subtype transposon-name,
          name "val164_1"
        },
        {
          subtype transposon-name,
          name "val165_0"
        },
        {
          subtype whole-replicon,
          name "val240_0"
        },
        {
          subtype whole-replicon,
          name "val237_0"
        },
        {
          subtype whole-replicon,
          name "val238_0"
        },
        {
          subtype whole-replicon,
          name "val238_1"
        },
        {
          subtype whole-replicon,
          name "val239_0"
        }
      },
      pcr-primers {
        {
          forward {
            {
              seq "GTT",
              name "fwd1"
            }
          }
        },
        {
          forward {
            {
              seq "CC",
              name "fwd2"
            }
          },
          reverse {
            {
              seq "GTAA",
              name "rev1"
            }
          }
        },
        {
          forward {
            {
              seq "GG",
              name "fwd3"
            }
          },
          reverse {
            {
              seq "CC",
              name "rev2"
            }
          }
        }
      }
    },
    user {
      type str "DBLink",
      data {
        {
          label str "BioProject",
          num 1,
          data strs {
            "PRJNA31873"
          }
        },
        {
          label str "BioSample",
          num 1,
          data strs {
            "SAMN1334554"
          }
        }
      }
    },
    molinfo {
      biomol mRNA,
      completeness partial
    },
    genbank {
      keywords {
        "keyword1",
        "keyword2"
      }
    },
    user {
      type str "TpaAssembly",
      data {
        {
          label id 0,
          data fields {
            {
              label str "accession",
              data str "M10102"
            }
          }
        }
      }
    },
    user {
      type str "GenomeProjectsDB",
      data {
        {
          label id 0,
          data fields {
            {
              label str "ProjectID",
              data int 112
            },
            {
              label str "ParentID",
              data int 0
            }
          }
        }
      }
    }
  },
  inst {
    repr not-set,
    mol rna,
    topology circular,
    strand mixed
  },
  annot {
    {
      data ftable {
        {
          data gene {
            allele "allele_mod"
          },
          location whole local str "dummy"
        }
      }
    }
  }
}
