Seq-entry ::= set {
  class nuc-prot,
  descr {
    source {
      org {
        taxname "Homo sapiens"
      },
      subtype {
        {
          subtype other,
          name "val246_0"
        }
      }
    },
    genbank {
      extra-accessions {
        "dummy1",
        "dummy2",
        "dummy3",
        "M10101",
        "M10102",
        "Q8Y7J9"
      },
      keywords {
        "dummy",
        "keyword1",
        "keyword2"
      }
    }
  },
  seq-set {
    seq {
      id {
        local str "dummy"
      },
      descr {
        molinfo {
          biomol ncRNA,
          tech both,
          completeness partial
        }
      },
      inst {
        repr not-set,
        mol rna,
        topology circular,
        strand mixed,
        hist {
          replaces {
            ids {
              swissprot {
                accession "dummy"
              },
              genbank {
                accession "M10101"
              },
              genbank {
                accession "M10102"
              },
              swissprot {
                accession "Q8Y7J9"
              }
            }
          }
        }
      }
    }
  }
}
