Seq-annot ::= {
  id {
    local str "ctg123"
  },
  data ftable {
    {
      id local id 1,
      data gene {
      },
      location int {
        from 999,
        to 8999,
        strand plus,
        id local str "ctg123"
      },
      qual {
        {
          qual "ID",
          val "gene00001"
        },
        {
          qual "Name",
          val "EDEN"
        }
      }
    },
    {
      id local id 2,
      data imp {
        key "TF_binding_site"
      },
      location int {
        from 999,
        to 1011,
        strand plus,
        id local str "ctg123"
      },
      qual {
        {
          qual "Parent",
          val "gene00001"
        }
      }
    },
    {
      id local id 3,
      data rna {
        type mRNA
      },
      location mix {
        int {
          from 1049,
          to 1499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 2999,
          to 3901,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 8999,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "ID",
          val "mRNA00001"
        },
        {
          qual "Parent",
          val "gene00001"
        }
      },
      xref {
        {
          id local id 6
        }
      }
    },
    {
      id local id 4,
      data rna {
        type mRNA
      },
      location mix {
        int {
          from 1049,
          to 1499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 8999,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "ID",
          val "mRNA00002"
        },
        {
          qual "Parent",
          val "gene00001"
        }
      },
      xref {
        {
          id local id 7
        }
      }
    },
    {
      id local id 5,
      data rna {
        type mRNA
      },
      location mix {
        int {
          from 1299,
          to 1499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 2999,
          to 3901,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 8999,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "ID",
          val "mRNA00003"
        },
        {
          qual "Parent",
          val "gene00001"
        }
      },
      xref {
        {
          id local id 8
        }
      }
    },
    {
      id local id 6,
      data cdregion {
        frame one
      },
      location mix {
        int {
          from 1200,
          to 1499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 2999,
          to 3901,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 7599,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "ID",
          val "cds00001"
        },
        {
          qual "Parent",
          val "mRNA00001"
        }
      },
      xref {
        {
          id local id 3
        }
      }
    },
    {
      id local id 7,
      data cdregion {
        frame one
      },
      location mix {
        int {
          from 1200,
          to 1499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 7599,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "ID",
          val "cds00002"
        },
        {
          qual "Parent",
          val "mRNA00002"
        }
      },
      xref {
        {
          id local id 4
        }
      }
    },
    {
      id local id 8,
      data cdregion {
        frame one
      },
      location mix {
        int {
          from 3300,
          to 3901,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 4999,
          to 5499,
          strand plus,
          id local str "ctg123"
        },
        int {
          from 6999,
          to 7599,
          strand plus,
          id local str "ctg123"
        }
      },
      qual {
        {
          qual "ID",
          val "cds00003"
        },
        {
          qual "Parent",
          val "mRNA00003"
        }
      },
      xref {
        {
          id local id 5
        }
      }
    }
  }
}
