Seq-annot ::= {
  id {
    local str "U00096.3"
  },
  data ftable {
    {
      id local id 1,
      data gene {
        locus "fdnG",
        syn {
          "ECK1468",
          "JW1470"
        },
        locus-tag "b1474"
      },
      location int {
        from 1547400,
        to 1550447,
        strand plus,
        id genbank {
          accession "U00096",
          version 3
        }
      },
      qual {
        {
          qual "ID",
          val "gene1509"
        },
        {
          qual "Name",
          val "fdnG"
        },
        {
          qual "gene_biotype",
          val "protein_coding"
        }
      },
      xref {
        {
          id local id 2
        }
      },
      dbxref {
        {
          db "EcoGene",
          tag str "EG11227"
        }
      }
    },
    {
      id local id 2,
      data cdregion {
        frame one,
        code {
          id 11
        },
        code-break {
          {
            loc int {
              from 1547985,
              to 1547987,
              strand plus,
              id genbank {
                accession "U00096",
                version 3
              }
            },
            aa ncbieaa 85
          }
        }
      },
      comment "formate dehydrogenase-N, nitrate-inducible, alpha subunit",
      location int {
        from 1547400,
        to 1550447,
        strand plus,
        id genbank {
          accession "U00096",
          version 3
        }
      },
      qual {
        {
          qual "ID",
          val "cds1460"
        },
        {
          qual "gene",
          val "fdnG"
        },
        {
          qual "product",
          val "formate dehydrogenase-N, alpha subunit, nitrate-inducible"
        },
        {
          qual "protein_id",
          val "AAD13438.1"
        },
        {
          qual "Parent",
          val "gene1509"
        }
      },
      xref {
        {
          id local id 1
        }
      },
      dbxref {
        {
          db "ASAP",
          tag str "ABE-0004917"
        },
        {
          db "UniProtKB/Swiss-Prot",
          tag str "P24183"
        },
        {
          db "NCBI_GP",
          tag str "AAD13438.1"
        },
        {
          db "EcoGene",
          tag str "EG11227"
        }
      }
    }
  }
}
