# -*- makefile-gmake -*-
# $Id$

### Requirements handling

reqs = $(REQUIRES:%=$(status_dir)/%.enabled)
requirements: $(reqs)

ifdef base_req_needers
  req_needers = $(base_req_needers:%=%.needs-reqs)
  missing_reqs = $(filter-out $(wildcard $(reqs)),$(reqs))
  ifeq "$(missing_reqs)" ""
    $(req_needers): %.needs-reqs: %.real ;
  else
    $(req_needers): %.needs-reqs:
	@echo 'NOTE: Skipping project $(notdir $(CURDIR)) due to unmet requirements:'
	@$(foreach r,$(missing_reqs),echo $(r:$(status_dir)/%.enabled=%))
  endif
  .PHONY: $(base_req_needers) $(req_needers)
endif
