# $Id$

all: sources

sources:
	+status=0 ; \
	MAKE="$(MAKE) $(MFLAGS)"; \
	export MAKE; \
	for x in seqalign seqblock seqfeat seqloc seqres seqtable; do \
	    d=$(srcdir)/../$$x ; \
	    (cd $$d  &&  $(builddir)/new_module.sh) || status=9 ; \
	    test -f $${x}__.cpp  ||  \
	        echo "#include \"../$$x/$${x}__.cpp\""  > $${x}__.cpp ; \
	    test -f $${x}___.cpp  ||  \
	        echo "#include \"../$$x/$${x}___.cpp\"" > $${x}___.cpp ; \
	done ; \
	exit $$status

clean:;
purge:;
