# $Id$

all: sources

sources:
	for x in seqalign seqblock seqfeat seqloc seqres seqtable; do \
	    d=$(srcdir)/../$$x ; \
	    (cd $$d  &&  $(builddir)/new_module.sh) ; \
	    test -f $${x}__.cpp  ||  \
	        echo "#include \"$$d/$${x}__.cpp\""  > $${x}__.cpp ; \
	    test -f $${x}___.cpp  ||  \
	        echo "#include \"$$d/$${x}___.cpp\"" > $${x}___.cpp ; \
	done

clean:;
purge:;
