-- ======================================
-- ! Testing sort order of mapped exons !
-- ======================================

-- Testing sort order of mapped exons: source
Seq-loc ::= int {
  from 100,
  to 900,
  id gi 4
}
-- Testing sort order of mapped exons: destination on plus
Seq-loc ::= int {
  from 1100,
  to 1900,
  id gi 5
}
-- Testing sort order of mapped exons: destination on minus
Seq-loc ::= int {
  from 1100,
  to 1900,
  strand minus,
  id gi 5
}

-- Both rows on plus, map genomic to plus: original
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 3,
    genomic-id gi 4,
    product-strand plus,
    genomic-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 200,
        product-end nucpos 779,
        genomic-start 200,
        genomic-end 789,
        parts {
          product-ins 20,
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50,
          product-ins 40,
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60,
          product-ins 10
        }
      }
    },
    product-length 580
  }
}

-- Both rows on plus, map genomic to plus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 3,
    genomic-id gi 5,
    product-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 220,
        product-end nucpos 479,
        genomic-start 1200,
        genomic-end 1489,
        genomic-strand plus,
        parts {
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50
        },
        partial TRUE
      },
      {
        product-start nucpos 520,
        product-end nucpos 769,
        genomic-start 1490,
        genomic-end 1789,
        genomic-strand plus,
        parts {
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}

-- Both rows on plus, map genomic to minus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 3,
    genomic-id gi 5,
    product-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 220,
        product-end nucpos 479,
        genomic-start 1511,
        genomic-end 1800,
        genomic-strand minus,
        parts {
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50
        },
        partial TRUE
      },
      {
        product-start nucpos 520,
        product-end nucpos 769,
        genomic-start 1211,
        genomic-end 1510,
        genomic-strand minus,
        parts {
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}

-- Both rows on plus, map product to plus: original
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 4,
    genomic-id gi 3,
    product-strand plus,
    genomic-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 200,
        product-end nucpos 779,
        genomic-start 200,
        genomic-end 789,
        parts {
          product-ins 20,
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50,
          product-ins 40,
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60,
          product-ins 10
        }
      }
    },
    product-length 580
  }
}

-- Both rows on plus, map product to plus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 5,
    genomic-id gi 3,
    genomic-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 1220,
        product-end nucpos 1319,
        genomic-start 200,
        genomic-end 299,
        product-strand plus,
        parts {
          match 100
        },
        partial TRUE
      },
      {
        product-start nucpos 1320,
        product-end nucpos 1609,
        genomic-start 330,
        genomic-end 579,
        product-strand plus,
        parts {
          match 110,
          mismatch 50,
          product-ins 40,
          match 90
        },
        partial TRUE
      },
      {
        product-start nucpos 1610,
        product-end nucpos 1769,
        genomic-start 630,
        genomic-end 789,
        product-strand plus,
        parts {
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}

-- Both rows on plus, map product to minus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 5,
    genomic-id gi 3,
    genomic-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 1681,
        product-end nucpos 1780,
        genomic-start 200,
        genomic-end 299,
        product-strand minus,
        parts {
          match 100
        },
        partial TRUE
      },
      {
        product-start nucpos 1391,
        product-end nucpos 1680,
        genomic-start 330,
        genomic-end 579,
        product-strand minus,
        parts {
          match 110,
          mismatch 50,
          product-ins 40,
          match 90
        },
        partial TRUE
      },
      {
        product-start nucpos 1231,
        product-end nucpos 1390,
        genomic-start 630,
        genomic-end 789,
        product-strand minus,
        parts {
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}

-- Genomic on minus, map genomic to minus: original
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 3,
    genomic-id gi 4,
    product-strand plus,
    genomic-strand minus,
    product-type transcript,
    exons {
      {
        product-start nucpos 200,
        product-end nucpos 779,
        genomic-start 200,
        genomic-end 789,
        parts {
          product-ins 20,
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50,
          product-ins 40,
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60,
          product-ins 10
        }
      }
    },
    product-length 580
  }
}

-- Genomic on minus, map genomic to minus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 3,
    genomic-id gi 5,
    product-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 220,
        product-end nucpos 479,
        genomic-start 1500,
        genomic-end 1789,
        genomic-strand minus,
        parts {
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50
        },
        partial TRUE
      },
      {
        product-start nucpos 520,
        product-end nucpos 769,
        genomic-start 1200,
        genomic-end 1499,
        genomic-strand minus,
        parts {
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}

-- Genomic on minus, map genomic to plus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 3,
    genomic-id gi 5,
    product-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 220,
        product-end nucpos 479,
        genomic-start 1211,
        genomic-end 1500,
        genomic-strand plus,
        parts {
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50
        },
        partial TRUE
      },
      {
        product-start nucpos 520,
        product-end nucpos 769,
        genomic-start 1501,
        genomic-end 1800,
        genomic-strand plus,
        parts {
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}

-- Genomic on minus, map product to plus: original
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 4,
    genomic-id gi 3,
    product-strand plus,
    genomic-strand minus,
    product-type transcript,
    exons {
      {
        product-start nucpos 200,
        product-end nucpos 779,
        genomic-start 200,
        genomic-end 789,
        parts {
          product-ins 20,
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50,
          product-ins 40,
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60,
          product-ins 10
        }
      }
    },
    product-length 580
  }
}

-- Genomic on minus, map product to plus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 5,
    genomic-id gi 3,
    genomic-strand minus,
    product-type transcript,
    exons {
      {
        product-start nucpos 1220,
        product-end nucpos 1319,
        genomic-start 690,
        genomic-end 789,
        product-strand plus,
        parts {
          match 100
        },
        partial TRUE
      },
      {
        product-start nucpos 1320,
        product-end nucpos 1609,
        genomic-start 410,
        genomic-end 659,
        product-strand plus,
        parts {
          match 110,
          mismatch 50,
          product-ins 40,
          match 90
        },
        partial TRUE
      },
      {
        product-start nucpos 1610,
        product-end nucpos 1769,
        genomic-start 200,
        genomic-end 359,
        product-strand plus,
        parts {
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}

-- Genomic on minus, map product to minus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 5,
    genomic-id gi 3,
    genomic-strand minus,
    product-type transcript,
    exons {
      {
        product-start nucpos 1681,
        product-end nucpos 1780,
        genomic-start 690,
        genomic-end 789,
        product-strand minus,
        parts {
          match 100
        },
        partial TRUE
      },
      {
        product-start nucpos 1391,
        product-end nucpos 1680,
        genomic-start 410,
        genomic-end 659,
        product-strand minus,
        parts {
          match 110,
          mismatch 50,
          product-ins 40,
          match 90
        },
        partial TRUE
      },
      {
        product-start nucpos 1231,
        product-end nucpos 1390,
        genomic-start 200,
        genomic-end 359,
        product-strand minus,
        parts {
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}

-- Product on minus, map genomic to plus: original
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 3,
    genomic-id gi 4,
    product-strand minus,
    genomic-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 200,
        product-end nucpos 779,
        genomic-start 200,
        genomic-end 789,
        parts {
          product-ins 20,
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50,
          product-ins 40,
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60,
          product-ins 10
        }
      }
    },
    product-length 580
  }
}

-- Product on minus, map genomic to plus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 3,
    genomic-id gi 5,
    product-strand minus,
    product-type transcript,
    exons {
      {
        product-start nucpos 500,
        product-end nucpos 759,
        genomic-start 1200,
        genomic-end 1489,
        genomic-strand plus,
        parts {
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50
        },
        partial TRUE
      },
      {
        product-start nucpos 210,
        product-end nucpos 459,
        genomic-start 1490,
        genomic-end 1789,
        genomic-strand plus,
        parts {
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}

-- Product on minus, map genomic to minus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 3,
    genomic-id gi 5,
    product-strand minus,
    product-type transcript,
    exons {
      {
        product-start nucpos 500,
        product-end nucpos 759,
        genomic-start 1511,
        genomic-end 1800,
        genomic-strand minus,
        parts {
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50
        },
        partial TRUE
      },
      {
        product-start nucpos 210,
        product-end nucpos 459,
        genomic-start 1211,
        genomic-end 1510,
        genomic-strand minus,
        parts {
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}

-- Product on minus, map product to minus: original
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 4,
    genomic-id gi 3,
    product-strand minus,
    genomic-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 200,
        product-end nucpos 779,
        genomic-start 200,
        genomic-end 789,
        parts {
          product-ins 20,
          match 100,
          genomic-ins 30,
          match 110,
          mismatch 50,
          product-ins 40,
          match 90,
          genomic-ins 50,
          match 100,
          mismatch 60,
          product-ins 10
        }
      }
    },
    product-length 580
  }
}

-- Product on minus, map product to minus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 5,
    genomic-id gi 3,
    genomic-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 1660,
        product-end nucpos 1759,
        genomic-start 200,
        genomic-end 299,
        product-strand minus,
        parts {
          match 100
        },
        partial TRUE
      },
      {
        product-start nucpos 1370,
        product-end nucpos 1659,
        genomic-start 330,
        genomic-end 579,
        product-strand minus,
        parts {
          match 110,
          mismatch 50,
          product-ins 40,
          match 90
        },
        partial TRUE
      },
      {
        product-start nucpos 1210,
        product-end nucpos 1369,
        genomic-start 630,
        genomic-end 789,
        product-strand minus,
        parts {
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}

-- Product on minus, map product to plus: expected
Seq-align ::= {
  type global,
  dim 2,
  segs spliced {
    product-id gi 5,
    genomic-id gi 3,
    genomic-strand plus,
    product-type transcript,
    exons {
      {
        product-start nucpos 1241,
        product-end nucpos 1340,
        genomic-start 200,
        genomic-end 299,
        product-strand plus,
        parts {
          match 100
        },
        partial TRUE
      },
      {
        product-start nucpos 1341,
        product-end nucpos 1630,
        genomic-start 330,
        genomic-end 579,
        product-strand plus,
        parts {
          match 110,
          mismatch 50,
          product-ins 40,
          match 90
        },
        partial TRUE
      },
      {
        product-start nucpos 1631,
        product-end nucpos 1790,
        genomic-start 630,
        genomic-end 789,
        product-strand plus,
        parts {
          match 100,
          mismatch 60
        },
        partial TRUE
      }
    },
    product-length 580
  }
}
