Seq-entry ::= set {
  class nuc-prot,
  descr {
    source {
      org {
        taxname "Klebsiella pneumoniae subsp. pneumoniae",
        db {
          {
            db "taxon",
            tag id 72407
          }
        },
        orgname {
          mod {
            {
              subtype strain,
              subname "TestABCDE"
            }
          },
          lineage "Bacteria; Proteobacteria; Gammaproteobacteria;
 Enterobacterales; Enterobacteriaceae; Klebsiella",
          gcode 11,
          mgcode 0,
          div "BCT"
        }
      }
    },
    pub {
      pub {
        gen {
          cit "Unpublished",
          authors {
            names std {
              {
                name name {
                  last "Wang",
                  first "Baozhan",
                  initials "B."
                }
              }
            }
          },
          title "An acidophilic Thaumarchaeota of Nitrosotalea cluster."
        }
      }
    },
    user {
      type str "DBLink",
      data {
        {
          label str "BioProject",
          num 1,
          data strs {
            "PRJNA588273"
          }
        },
        {
          label str "BioSample",
          num 1,
          data strs {
            "SAMN13234604"
          }
        }
      }
    },
    user {
      type str "NcbiCleanup",
      data {
        {
          label str "method",
          data str "ExtendedSeqEntryCleanup"
        },
        {
          label str "version",
          data int 1
        },
        {
          label str "month",
          data int 11
        },
        {
          label str "day",
          data int 21
        },
        {
          label str "year",
          data int 2019
        }
      }
    },
    create-date std {
      year 2018,
      month 9,
      day 7
    }
  },
  seq-set {
    seq {
      id {
        local str "ctg7180000000092"
      },
      descr {
        molinfo {
          biomol genomic
        },
        user {
          type str "Submission",
          data {
            {
              label str "AdditionalComment",
              data str "ALT EMAIL:mdna@majorbio.com"
            }
          }
        },
        user {
          type str "Submission",
          data {
            {
              label str "AdditionalComment",
              data str "Submission Title:None"
            }
          }
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "LocalId",
              data str "ctg7180000000092"
            }
          }
        }
      },
      inst {
        repr raw,
        mol dna,
        length 19271,
        seq-data iupacna "GCGGTAAAAGACCGCTTGCCAGCAACGACATCTTGTAGTATTACTCGGTAAT
ACTAGGAGAGAACATAACATGAACACCACCACAATAAGCCCTGTGGCTGTCAAAATTGACGCGGCTCTAAAAAACAGG
CTGAAGCGGTTAGCCAGCCTGCGGCAACGCAAACCCCACTGGCTGATGCGCGAAGCGATTGCTCAGTATGTAGAGCGG
GAAGAACAACGCGAAGACTTCAAAAAGGAAGCCCTCACTGCATGGAAGGACTATCAGACAACGGGAAAACATGTCACG
GGTGATGAGGTCATTACATGGCTGGAAACATGGGGTGAGCAACAAACAAAGCCCGCTCCCAAATGCCACAAGTAATCC
TTACCGAACGTGCTATCCGCAATCTTGAACGGGTGCAGGAATTTCTCCTTACAAAAACCCCTGTCAGCGCAAAGCGGG
CAGGACAAGCCATCATCAAAAACATCAGGTTACTCAAGAGCAACCCACAAATCGGGCGGCAGGTAGAAGGGATGCTGC
CGGAATTCCGCGAACTCATTATTCAGTTTGGTGATAGCGGCTATGTGGCGCTGTATCACTATGCAGGCGATGTTGTGA
CGGTCTTAACGATCCGCCATCAAAAAGAAGCAGGCCATTAGGTGAAAACGTGCTGGAGTACAAAAAGGTATTTTCAAG
AGGAAAAGCGCAAATCGCAGAGGGAACGGCTCCACACACTTTGACAGGCGCGTGGAGCCGCAATATCAAATTACTTCA
GGGCGTCGAGTCCGGCTCCGAAGTTAATATGAAACGGCTGCCCCTCAAGCACGAGGGCCGGTACGGACTTGACCCCCG
CAGCTTCAGCCTCAGTGATGCGACCCTTCTGCTCTCCCAAATGCACGATCTCGACGCTGTAGCGTGAGCGGTCAAGCG
CATTCGCGACGTTCTTTTCCGCGTCAACGCATACCGGACACCCTGCGTGGTAAAACACGGCCTTCTTGCTCATGTAGC
CCCTTACAAATGTGGTTGTGATGACAAACTGCATCATGCTCGCTTCGAACATAGCCGTCGTCAGACATGGCGGTCAAG
GGTCGTTGAGGGCGTATTTGTATTTCCAAAAATGGTTCCTTGCTGCGTCAGTGAATAAATCCGCCTTGCTCAGCGATG
GCGGCAGCATCCCGCGCACCATGAAGAACCCGGACGACGATAAGTGTTCTCTTGGTGACTTGGTAGTAAATGGCATAC
GGATGGTGAAACGTCACCCGCAAGCCCGTGCCGAGTTGGTCGCGGGTCGTGCCAATCAGTGGAGAGTGGCGTGCCACA
TCTATTGTCTTGGTAATCCGGTCAAGGTAACGGGTTGCAGTCGGTTCACCCGCTTCGGTCGCAATGTATCCCCAGATT
TCCGCAAGGTCGGTTTCCGCTGCATCGGTGAGGTGAAGGGTCAAGGCTTGGCTGATAACTTCCTCCCTTTGGCGATGA
TGCGCTTTTTATCAAACTTACGCACCGACCGGCGCAATATCCGCCAATCCTTTATCGATATCCGCTTTCAGTGCCGCG
AACTCATGAGACTGGAATGCCCGCCGCTGTTTCCACTCGCGCACAGCTTCTCGCACGACTTCACTGGTAGAGGCATAG
TCCCCATCGTCAACCGCCGTCTTGATAACCGCTGCCATGTCAGTAGGCATGGTGGATGGTCATGCGTTCAATACTCGC
CATAGCGTCCTCCGTGTATGATTCATAATTCATACTTTATCATACTATTTTACTAAGGCAACCGGGGATTACGGGCAG
CAATCTGAAACAGACTTATGCAACAGTCAAGAGCGAGTGTTTAGGCGGGTTGTGGTGTTGTTGCAGAAGTTACCACTT
GTGAAACAGGAGAGAGGAATCCAATGAGTTCCCGCCTGATACGCTTGTCGAAGTAAAGAATGCATCGTAAGTCTCATG
GGGCGGGAGGTGAGGTGCACCCCTTGTCCGGATCATTGATACCGTTCCATTGTATCGTAATCTTACTTGTTCCGGCTC
TCGTCGCGTTTGCATTCGATGTCGCAGTCGGTGAAGGCTGAACGTTAGCAGAAACTCCTGCATCCAACTCTTTTGTAG
CGTCAGCTTCGATGATAACGGAAGCAAGCTTTAGGCACGTGATGGATTGGGGCGCGCCAGTTTTCTTCTGTTCGAGTT
CCCACATTTTCAGCGCGGCAGTAACATCTGTGATGTCATGTTGTAAGTTCCTCTTCGTACACCCAGCTGTCGCAACTA
AGACCATAAGAATCAATCCAACCCTTAGATGTAATTGCATACCACCCTCTCAGGTTCGATCAAGAGATTCGATGTGCG
AGTTTGAAGGACGGGTATTCTAGAAGGCACCTCAGTTCGAAGCAATCGGGTCGAATAGGTTCTCACTTATGCAACGGA
AGACATCTTGCATGAAACCAGCATGGAGTGAACTTCATCTCTGGAGAAAAAAGTGAGGTGTGTCGCGCCAGAAGCGCA
CTGAGTGTTGAGTCCGCTTCTCGGCTCCTTCTCAAAAAACTTGATGTCTTCTGTGTTGCCCCACTGCTCCCCTGTCCG
ACCCGTTGGTGATGAGAGGAATACCCCCTGCTCTCCGAGACCAGCTCGGGTGGGCTGAGCGGATGAACTATCCGACTT
CCCGGGTGGGTCACAAACCAAGCCACCAGTCGGATGTCATTCGACCTGGAGCCGAAGCGTTTCTTCAATTCATCTATT
GCTTGCCTTCTCCGGACAATGCCGTAGGCTACCCAGAGAGATATCCCAATCGTTCTTCTACCAGGGAGGTGCCCATGG
AGATGGTTTTAGCAACGCTTCTTCCGTGCCCGTCCGTTCAAAGGGAGGCGCATCATGCGCAACCCTCCGTCGCTTTCT
TCTCTGCCTGAAGCGGTGACCCATTTCAAATCGGATAGCAAATTTTAATTATGTGTCGAACTGGAGCGGTTCTACGCT
CCGCAGACAAAGGAGTGAAAGAGAATGATGATTAATTGGAATGGCGGTCAGCTCATCACCCTCAACCCTGGAGATACG
GCGACTTGTGCCGGCGGACTTAACCCCGGCCAGGTTTATGCGATCTTTTTATATAATTCTGCCAACAATGACGCCAAT
GCGCCGGTGAATGTCGTGTGGAGTAACTCGCAACCGCCGGTACCGGTCACTGTCCCAGGCACCACGGCCAAAGCAAGG
TCTGGCGGCGCTATGTTTCGTATCGGGCGACGATACGAATACGGTCAGCATCTCGCTCGGTCAGAGCGCCTCAGGTGT
ACAAGTCCAAGCGTTTCTCGGAAGTGTGAAGATGCCGGTCAATACGTCCGGCATTAACAACATCGCGTTACCTCTCGA
CGGCCAGAACCATGCCTTCAACGCCTTCACCCGGTTTTATGCCGTGCCGCAGAGCCATTGGTATTCAGGGCAACTCCA
AAGCGACATCAACCAGTTCATCTCGGTACAGTTCAAGGAAGCGAGCGCTATCGTGAATATCGTCAATAAGCTCGTCGA
TCCAAGTACCGTTATTAAATATGCTGGTCCCAGCATCCAGCAGCCGAATGTAGTTACAATAAATCCATCAGACAGCCA
AACGATTTCCTGGAATCTTCAGGGAATGGGACGCAATTGGTCTGGATCAATGCCGACAGTGTACAAAATTCCCAAAGT
GCGACAATAAGCGTCCAATCGCTCGCGGCGGTTTACGACGCCTATAATCGAGGGTCGTTTGAAGAGTTGGAGGCGAAG
GTCATGGCGAAGGCAAAAGCGGCGCGACCCTAAGTCTCAGGATCGTCAGCACCCTGATGTGAATGCTTCAGGGTGCTG
ACGATCCGACACGGCATACCTGTATGTTCTGGCCTAATCCAATTATAAAAGAGCGCGATCCCTAGAAAGGGTGCCTGG
CGAGGGCATGCTTATACCACATCCGCAAGAGAGACTCTTACGTGAGGGGCGGGCGTTTCATAACTGACCACTTCTGAA
ACAGGCAGCCTATACTTTTTGGCAACACATTGATAACATCATCCATACTTGTTCCTATCACGTTACGTGATGACATTT
CTCGTTCACCAAGGCGGAGCCGGCAAGACGCCCCCCACCGCCGACACCATCGTGGTGTTGACGGCGCGAAGCCCTGAA
CGCATCATCCGTGAGGGCGGTTCGCAAGCGTGGGTGCTCAACCCCGCCCGCGCGAAGCAATGCACCTGGCTGCTCTGC
ACCCAAAATCGCCATCACCCCGACCCTGAGTTTTCGGATGCCACAGAACCGCACGGCATGGGCTTCCTGCTCGGGCGG
ATTGCGACCGTGCAGAAATCGAACGACCATGAGGGTCCCGGGGTCCGCTGGCTCATCGCCCTTCGCGAGTACGCGCGG
ATCCAGCTTCCCAAGGCCTGGGATCAGGGGCGCAATCCCGTGCGCTACCGGGCCCTCGCCGACTTCCGGATCAATCTC
GACAAGGTGACGTTTCAGCCGATGCCGCTGGAGGAGAAGCCGCCGCCGCGGCGGGCCGGACACCCCGCGCCGAGCATC
CTCACCCTCGCGGAGGCCAAGCGGCAGCTGGCGGACACCTTCGGCGTCAAGCCGGAGGCCGTCGAAATCACGATTCGC
GGCTGAGAGCCGGGGAAGGGGGCGGCCCTGGCGCGCCAATCCACGCCGGCCCCGTTCTGTGAGGGACGCCCGCGAGGA
GCCGCGCACCAACCGGGTAGCGCATTCTGTCAGGGAAACGAGCGCGGCTACATGTCTGCTCTGAGGTCGGAGCTGGGG
TTTGCTCACCCCCTCCATCCGCGAACGTCGATCAAGACCACCGCGCGGCACGGGTGTGCACGGGTGTGAATGGGTTAG
GAAGGCGAAACTGGATACTTGGTACGCGGAGGGATACCAATATGGACTTCTCACGAAGAGACACGAAGAGACAACCAG
GGATCACCGGCAAGACAGTGCTCTGTGAAAGCCTGATGAAGAGATCCATCCGTGAATCATTCACCATGATCACAGCTA
TTTATCTACCAGCGAGCGCAACCGCGCGAGCCGAGTGCGATGAGCCTGTTGTTGCAAATCGATGTGCTGCCCTCTCCG
GGTAATTAAAATACATTCCGTCACAGGCTGATCAATAATTTTATCGGAGATTGAAATATGGCTGAGGGTACTTGTCGC
TGCCTGGCTGAATAAATAAATAAATGAATAAATCATCAGATTGCCTGCATCTTTTTGTGCACTATTATTTATTTATTC
CCAATGATTTTCACGACCCCAATGATTTGCCCGACGCGGACTAATTTACGAACATTGGTGTTTGTTCCGGTGCAGAAC
CAATTCATAGTCAATATGTGCCGCAGAATTATCTGCGAATCTCCCCCTGTTCACCAAAGCCGAAATATAGGTGAGAAT
CTTCTCTAGGGAAGGTCTGATTTATTCAACGTTCCGACAACTAATCAGCTCCATTCGCCGTGTTGTGCGTGCCAACTG
AGTACAATCAGGAATTAATCAGACCTTCCTTAATAAATAAATGAATCATCAGATTGCCTACATCTTTTTGGGCACTAT
TATTTATTCCCAATGATTTGCCCGACGCGGACTGATTTAATAACATAGCGTTCTCCTTAATCGATGCCTTGGGCATTT
TTAAAACAATAACTGGCAGGGATGTCCGTGTGAAAATGCCGGTGTTGTAGCGCGTACATACTGATTCCCCAGGGCCCT
AATAGAAGCGGCCAGTTGCTGCCTTCTCTTCCGCTCCAGAAATTCCCTGTATTCGCGGCCCAATTTTCTTTATTGTAT
GCGTATAGACAGGTGTAGTGCTCCCCTAAAATCAAGCCATCTAAGGAAGGTCTGATTTATTCCTGATTGTACTCAGAC
CTTCCTTAGTTTTTCTGGTCTTGCGACAACACGGACGCCGAGTTAATAAAGCATTCCTCGATTGGCACAATGGCCTTT
GTGAGACCTAACCCACCAGCAAACAGCCAGTTTGGCCAAGACGTATTGGCTGATCGAGAGAGCCCGGTATAGGCGTTG
AGGCAATGCGCCCGCTCGAAATGTGTGAGGTCGTTACGCAATACCCAATATTCCGGCTTCGATCCAGCGCATCCGTAC
AGGGAGAACGACACCAATAATGAAATCATTTTAGGCATGGGTGACATCCTTTCCTGATGGTTGAGAAGTGTGAGAAAT
GTCGCTTGTTGCTGCAATAGGACTGGGGAGAAACTGAGAGATGAGCATCCCCAGCACGCTTATGGCAATGGCGATGCC
GGTATACTGCTCGTAAACACGGTTTGAATAGTCCTTACGGTTTGATCTTCTCAATCGCTGTTAGTGACCCGTTAGCTC
CGTATGTGAGATGATAGATCACGAGTCTGTCTTTGACGGCGATTTCAATCGGGGTAAAAATAAGTTCAGTCAAGAACA
ACGTAAAAAAATCACCCGCTAGGTATCCTACTGCTGTGAGCAGCTTGAGGCTCCAATGATGAGCACCAGGGTCTAATT
TATACCGGTCATCGTATCCCCCCCCGGCCAGGGTGGTGAAGTTGTCAGGTTCGCCGAGTTCGGCGATCACTAAGGATC
GTTGAACACCCATTTGAATGACATTTAGATCACCTCTTCTATTCTCGCGACTGGCCACCATGAGCACGGAACACCCCG
ACAGATTCAACAGAAGCAGGCACATGACGAACAGGTTTGGTTTACGCATTCTTCTTGCCCCCGCTAAGTAAAGATAAT
GAGAAAGGAGCTGGATACTTCCTCAGAGGAGGTTACGGCATTGGAAGGAGAAAGCAAGCACTCGCTGAATTGCGGCCG
TGAGAGGCTGCGTCCCTCACGGTAAGGCGTTGGCCACGAGCGCCGCCAGGGCCGTCATCAGCACGCTCACCAGCGTGC
GCTGGATTAGGGCTGCACCTGTTCGAGTTGCCGCTCGATGGTCATCAGCTTGGAAGTGTATTCCACTGCCTCCGTGGT
CTCTCTGACGGGATCAGTCTGTTTCACAACGAGCGGCACCATGACCGCCTGTCCGTTGAGTGGGTGCTTGATGTGTGT
GGATACTCTGAAGCGCGATGGTCACGCTCATCAAAGTTATCGAGGAATCCATAGAGCCGTCATCTTCGGCATACCCTG
CCCGACGGTCAACGGACAAGTTAAGAGGTTCTCTTACTCGGGAAGTCCGCTGCATTTCCCATGGTGATGAGCTATGTG
TTTTGTCCTCTTTGGCTTCACGAGCGGCGCATGCCGCCCGCTATAGCGGGGGAGGCTTCAAGGCTCGATGAGGGGGCA
CAGCCCCCGCATCTGTCTGAAGTTGTCCCTAGTGTGGGGTCACCAGCTATCGGAAATCTATCAGGTTTAACTAGAGGA
CATGTGAGGAGAAGTGGCCGTGGATCACCGCTTCTACGCCCAAATGACGACGGGTGGTTGATAAATCAATACTTCATT
GTAAATCAATATGTTGTGACGTTGCTGAGGGGAAGTGGCCGTGCTTTTTCTTACACAGGATCACTCCGCGAGCGGTTG
GCAGGGGCTACGTGCCGCCAATTAACCGCGGGACGGCACAGGCGGCGGGCTTATGGTCCAGCGTGAGGCCGTCTAGTG
GCTCACTGGACCAGTCCGGTAAGCCGTCGTCTTGTTCGGGGTCCCCGTACAGTTGGCGGAGAACGTCGCGGTTTCACA
TCGCACACGATGTTATTTCAATCACTTATCATGCGTCCAGTGTCTGGAGCGACGGGCGGCGCGCCTTCTTGATTGGAT
AAGCCTTTTTCATTCACACTGCGCCAAATTCCTTCAAATGGACGGGAACCCCAGGCCCGCCCATCGGAAAAGCTCGAG
TGAACGCTACCAGCGCGGGCCCTCCGAAAATCCGCGCGCGCCTTCCGGCCTCTCCAATTTCAAACGCCGGAAGGGGGC
CCTGCCACCGCCCCCTCCGAACATGTTTTGAAGCGAAAGGGTGAAGGTTACACGAAAAGCGATTTAAAAGGGCATACA
GGGGGGTAAATTTTGATGCCTTCCCCCCCCTTACCCTCACTCCGTTTCGTTGCTCTGTGGCCTTCCTAGGCGTTTTAT
GATGGCGTTCGATAGCATCCTGTGACCTCCCCCCTCCTCTGACACCCTTTTGAAGGCAATCTTCTTTCTTTCCTTTGG
CTCTAGCCTGAGTTGAGGGAAAGAAACAAAGTCTTTTTCCAATGCCCTACTGAGGGCTTACTGGAAGAAGGCACTACC
GGCAAATCATCTTTGGCTTTTCCCCTATTCCGAATCCAGATAACAAAGTTTTCCACAGTTCGGAACGAAACAACTACA
GAAATTACTATATTTCTTTATTAAAGATAGGGGGGCTATTTCAGCGTATCATAGGGGGGCTATTTCAGCGTATCATAG
GGGGGCTATTTCAGCGTGGATAACTTTTCTATTCAGTGTCGAATGTGGATAACTTTGGCAAATAAAGAATTACGGCAA
ATCAGGTGGTTATTAAGAAAGGTGGGCTATTTCAGGGTATCAAGATGATGGGTTAACTGTTGGGGTTTTAGTTTGATT
GTAATGGCAGGATTGCAGGGTAAGACGCTCACGCCACCCCTGATATATTGAAGCCCTAAGTCAGGATAAACTTGTTGG
ATTTTTTTGAAAGCAGCTTTGGCTTTCTTTGAAAAGTCCTTTATGTCGTGGTTTTCTGTCCCTAATTGGTTATGAAGG
ATTTTCCACGAGATACTACGAGCCTGTCCATTTTGCTGTGTTCGGTAGGCGGTGTAGGTAGCCCAAGAATAGAGGTCT
AACGCTAAGGGGCTGCTCTTTAAAGCTTTTAATGCTCGCATATCAACAGGAACCGGTGAGGAAGTAATAGCGGCAAAA
AATTCCTCTCCTAACTGAATCCAGCTTTTCCAAAGGGTGCTTTGATGTGGTTGCTTCTCATCCCACCACAACATGCCT
TTTGGTGCTACGTCCATGTTCATCCAGGCGTAACCTTTTTTTCCTTTTTGGTTGTGGCTCTGTTGAAAACTGATTTTG
GCATTAAAGAGGCGTTCCATCTGTTCACGTATTCGTTTGGCATCGCTACGTTTCCCGCCCCTACTTGGATCAAGGTCA
AGTTGACGCATGAATGAAGCTAAACTGTTACCGAGTTCAAGGCGGCGGTTCGCTGTTCGCAGTGCTTCGGTGGTTATC
CAAAAGAGCAAAAGTCTGGGAATCGTGCCATAAGGTAATCCGTACTTCTTATCGGTGAGCGCATCATAACCAGCTTGC
ATACCCAAAACAAAATTGCCGTTGGTTCGACGCCATGTATCAGTTTTAGGGTTTCTGTGTGGCAAGGTTGCTTGAACA
AGTTGGCGCGCGATAAAAGCAGCTTCCGCTTTATCGGGGTCAAGGCGGATGGCTACGGCAGCATCAAGGAAGTTTTCT
TGTTGTGGAGTAAGTGGCATGGAACAATCGTATATTTGTGGTTAATTTTGTGAGCGGTGGTCGGTATCGGTATAGGGT
TCCGGTTTGCCGTATTCCACAGCAAGTTGATTGATTGCACGTCCGAGAAGCTGTTTCAGGGTCAAGCCGCTTTCCGCT
TCAATGAAGCGTAGAGCCTTGCGGACTTCAGGCGCATAAAACGCGCCTACTAAAACATCTTTAGATTGCTGCTTTGTC
TTCGGTAGTACCGTGGGATTGGGTTCAAGTGGAACGGGTTTTCCGGCTGCGGCGGAAAGTGATTGTTTAAGCGCACTG
TGTTTTTTCATATTAATATAATCCTAGAGCATTATAATAATCTATAAATATAGATATATAATTGTTTCATTTCAACAG
CTGCTTTGCCGAGCGGGTCGAGTTCCCCGGCTGTCTTTCCAAGGTCTCCGGCGTCGGAATGAGCGGCACGATGAAACA
ACACAACAGGCGCAACCTTGAAGCCCTGCTCTATTAACCATTCCCGTGCGTCCTCGTGTCTGCGTCCCTGTACGGGAG
CATCATTGATAAGAACCTCAGCAGGTGGCTTCCCTGCAAGATTGAGAATATCGGATACCGTGGTGAGAGTCTCTAAAC
TGGAAATATGCGGTTCGATTGGAATCAAAATCCGGTCGGCAAGCTTTGCCGCTTCAATGGCTATCTGTCCGGCATGGG
GTGGGGTGTCAATGACGACAAAATCAACGCCCTCCGTTTTGGCTTGGTTTAAAACCTTTGGCAATCGTGCTGCTGGAC
TACATACAACAGCCAATCGGTCGGACTCTTCGCGTCGGTCGCTCCATTTACCAGTAGAAGCCTGTTGGTCAAGGTCGA
TTAAGGCAACTTTCAGACCTGTACGCATGGCTTCCACGGCTAAACCCTGCGCGGTGGTCGATTTACCACTACCGCCTT
TTTGACTGATAACAGCAAGGGATTTCATCGCGAATTATCCTAGCATGTTATATTATAATATCACTATAGTTATATAGG
TATAATATCATATATAATATGTGCTATATAAGACTAAAGGATTAGAGTCAATGGAAAGTCCAAAATACGTTTGCAAAT
TAGTGCGGCATTATAAGAGCGGGTGTTCGTTATTTTCGTCTTTCACAAACATGTTGTGTGGCGAATGGTTTTTACCTG
CTCTTCCTCTAAAATGGCTCAGGAAAAAGTTAGTGCTTGGCAGGGCGCAGCTCAAAACTCAGACCTGCCTGCTTCTGT
AAATAGCCAAGTACCGCAAACAGGTTCCGCGCCTGCGGATTACCGGATGGGCTGAACTGGCGCATCAGGCTTTTAGAA
GGCATCTTGGTCGCTTTGGACAAGGCTCCAAAGCCGATAGTCGCATTAATGTAATCGCGCATCACTGCTTTGCCCGCT
TCAACATCGCCTGAGACGAAGGCCTCAATTCCTTCGCGCAAGAGCGCGTCACGAAACGCCTTGTCCTTTTGCGCCCGC
GTGCGAATGGTCTCCTTAAAATCATGTGTCAGTGGCATATTCATATCCCTTTCTTCCGTAATTTATAGTCCGCCCAGC
GGGAAAGAGCCGTTTCAATGTCGCTGTTCTGTCTCCGCTTGGTGCCGCCTGCCAGAAGGATAATCAGAGCGTCTCCAT
CCTTCGCAAAATAAATCCGGTAACCCGCCCCCCAATCAATCCGGTATTCAAGCACACTGCTACCAACGCCATTGGTAT
TGGAGAAATTGCCCAGCTCCATCCGGGTCAACGCGATAGCGACTTTGGCACTTGCCGTAGCTTCCAACTCGTCAAACC
ACTCTTTGAACACCGCACGACCGTTTCGGTCGATGTAACCTCTCATCTCAATCATTTATAAATGGTACCACAAGCGTT
ACCATAAGCAAGAAGACATATCGCCTTCAGAAGTTTCATTTCCACACAAGGGATGCGATTCAGAGGTACCTAGTACGA
CAAACGACGCACCAGCTGTGAAGTAGGAGAAAAAGTTGTCGCGCATTCTCACGACTCATACAGAGTGGGGTCTGCTCA
GGTGCAGATAGTTGAACACCGTGCGCGGCGATACGTTCAGCGCGTTGGCGATTTCGGGAACGGTCAGACCTTGCCGCC
TGAGTTCCTGCGCTCGTTTCGGGGTAGCTTTCGTCGTGCCTGCCAGCCGTCCCTTGTACACCCCACGCTGACGGGCAA
GGGCAATGCCGATAGCTTGCCGTTCTTTGGTGTGCTGCAATTCCATTTCGGCAATGCCAAAGAGCAAGCTGGCAATGA
GATGTCCCACTGTGCCGCTCAGGTCGATTTGCTGCGTGACAGCAATCACCCGCACGTCACGTTTGCACCAGTCAGCGA
GGATATTGATTCCGTCCTTGAGGCTGCGGGCGAGGCGGTCGAGTTTCCACACCACCACCGTCTCAATTTCACCCTTGA
ATATTGCGCTTTGTAATTGCTGAAACGCTGGACGCTGGAAATTAGTCGCGCTGTCTTTATCTTCAAACCAGCGCACCG
CTTTCAACCGTTGCCGTGTGCGCCATGCTTCCAGCTCGGCGCGTTGGCTATCGGTCTTCTGTCCTCTGGGTGAGGACA
CGCGGATATAGAAGGCAGTACGCATGCACGTATGGGTACACCCTATATTGCAGTCTGTCAATCAAACAAAAACCCGCG
CAAGGGAAAAGGTTATGAGGGATAAAAACACCAGCACCCTATTGTGCAGGGTTGGAAGCAGGGGAGAGGAGTAGAGCG
GTAAAAGACCGCTTGCCAGCAACGACATCTTGTAGTATTACTCGGTAATACTAGGAGAGAACATAACATGAACACCAC
CACAATAAGCCCTGTGGCTGTCAAAATTGACGCGGCTCTAAAAAACAGGCTGAAGCGGTTAGCCAGCCTGCGGCAACG
CAAACCCCACTGGCTGATGCGCGAAGCGATTGCTCAGTATGTAGAGCGGGAAGAACAACGCGAAGACTTCAAAAAGGA
AGCCCTCACTGCATGGAAGGACTATCAGACAACGGGAAAACATGTCACGGGTGATGAGGTCATTACATGGCTGGAAAC
ATGGGGTGAGCAACAAACAAAGCCCGCTCCCAAATGCCACAAGTAATCCTTACCGAACGTGCTATCCGCAATCTTGAA
CGGGTGCAGGAATTTCTCCTTACAAAAACCCCTGTCAGCGCAAAGCGGGCAGGACAAGCCATCATCAAAAACATCAGG
TTACTCAAGAGCAACCCACAAATCGGGCGGCAGGTAGAAGGGATGCTGCCGGAATTCCGCGAACTCATTATTCAGTTT
GGTGATAGCGGCTATGTGGCGCTGTATCACTATGCAGGCGATGTTGTGACGGTCTTAACGATCCGCCATCAAAAAGAA
GCAGGCCATTAGGTGAAAACGTGCTGAGTACAAAAAGGTATTTTCAAGAGGAAAAGCGCAAATCGCAGAGGGAACGGC
TCCACACACTTTGACAGGCGCGTGGAGCCGCAATATCAAATTACTTCAGGGCGTCGAGTCCGGCTCCGAAGTTAATAT
GAAACGGCTGCCCCTCAAGCACGAGGGCCGGTACGGACTTGACCCCCGCAGCTTCAGCCTCAGTGATGCGACCCTTCT
GCTCTCCCAAATGCACGATCTCGACGCTGTAGCGTGAGCGGTCAAGCGCATTCGCGACGTTCTTTTCCGCGTCAACGC
ATACCGGACACCCTGCGTGGTAAAACACGGCCTTCTTGCTCATGTAGCCCCCTTACAAATGTGGTTGTGATGACAACT
GCATCATGCTCGCTTCGAACATAGCCGTCGTCAGACATGGCGGTCAAGGGTCGTTGAGGGCGTATTTGTATTTCCAAA
AATGGTTCCTTGCTGCGTCAGTGAATAAATCCGCCTTGCTCAGCGATGGCGGCAGCATCCCGCGCACCATGAAGAACC
CGGACGACGATAAGTGTTCTCTTGGTGACTTGGTAGTAAATGGCATACGGATGGTGAAACGTCACCCGCAAGCCCGTG
CCGAGTTGGTCGCGGGTCGTGCCAATCAGTGGAGAGTGGCGTGCCACATCTATTGTCTTGGTAATCCGGTCAAGGTAA
CGGGTTGCAGTCGGTTCACCCGCTTCGGTCGCAATGTATCCCCAGATTTCCGCAAGGTCGGTTTCCGCTGCATCGGTG
AGGTGAAGGGTCAAGGCTTGGCTGATAACTTCCTCCCTTTGGCGATGATGCGCTTTTTATCAAACTTACGCACCCGAC
CGGCGGCAATATCCGCCAATCCTTTATCGATATCCGCTTTCAGTGCCGCGAACTCATGAGACTGGAATGCCCGCCGCT
GTTTCCACTCGCGCACAGCTTCTCGCACGACTTCACTGGTAGAGGCATAGTCCCCATCGTCAACCGCCGTCTTGATAA
CCGCTGCCATGTCAGTAGGCATGGTGATGGTCATGCGTTCAATACTCGCCATAGCGTCCTCCGTGTATGATTCATAAT
TCATACTTTATCATACTATTTTACTAAGGCAACCGGGGATTACGGGCAGCAATCTGAAACAGACTTATGCAACAGTCA
AGAGCGAGTGTTTAGGCGGGTTGTGGTGTTGTTGCAGAAGTTACCACTTGTGAAACAGGAGAGAGGAATCCAATGAGT
TCCCGCCTGATACGCTTGTCGAAGTAAAGAATGCATCGTAAGTCTCATGGGGCGGGAGGTGAGGTGCACCCCTTGTCC
GGATCATTGATACCGTTCCATTGTATCGTAATCTTACTTGTTCCGGCTCTCGTCGCGTTTGCATTCGATGTCGCAGTC
GGTGAAGGCTGAACGTTAGCAGAAACTCCTGCATCCAACTCTTTTGTAGCGTCAGCTTCGATGATAACGGAAGCAAGC
TTTAGGCACGTGATGGATTGGGGCGCGCCAGTTTTCTTCTGTTCGAGTTCCCACATTTTCAGCGCGGCAGTAACATCT
GTGATGTCATGTTGTAAGTTCCTCTTCGTACACCCAGCTGTCGCAACTAAGACCATAAGAATCAATCCAACCCTTAGA
TGTAATTGCATACCACCCTCTCAGGTTCGATCAAGAGATTCGATGTGCGAGTTTGAAGGACGGGGTATTCTAGAAGGC
ACCTCAGTTCGAAGCAATCGGGTCGAATAGGTTCTCACTTATGCAACGGAAGACATCTTGCATGAAACCAGCATGGAG
TGAACTTCATCTCTGGAGAAAAAAGTGAGGTGTGTCGCGCCAGAAGCGCACTGAGTGTTGAGTCCGCTTCTCGGCTCC
TTCTCAAAAAACTTGATGTCTTCTGTGTTGCCCCACTGCTCCCCTGTCCGACCCGTTGGTGATGAGAGGAATACCCCC
TGCTCTCCGAGACCAGCTCGGGTGGGCTGAGCGGATGAACTATCCGACTTCCCGGGTGGGTCACAAACCAGCCACCAG
TCGGATGTCATTCGACCTGGAGCCGAAGCGTTTCTTCAATTCATCTATTGCTTGCCTTCTCCGGACAATGCCGTAGGC
TACCCAGAGAGATATCCCAATCGTTCTTCTACCAGGGAGGTGCCCATGGAGATGGTTTTAGCAACGCTTCTTCCGTGC
CCGTCCGTTCAAAGGGAGGCGCATCATGCGCAACCCTCCGTCGCTTTCTTCTCTGCCTGAAGCGGTGACCCATTTCAA
ATCGGATAGCAAATTTTAATTATGTGTCGAACTGGAGCGGTTCTACGCTCCGCAGACAAAGGAGTGAAAGAGAATGAT
GATTAATTGGAATGGCGGTCAGCTCATCACCCTCAACCCTGGAGATACGGCGACTTGTGCCGGCGGACTTAACCCCGG
CCAGGTTTATGCGATCTTTTTATATAATTCTGCCAACAATGACGCCAATGCGCCGGTGAATGTCGTGTGGAGTAACTC
GCAACCGCCGGTACCGGTCACTGTCCCAGGCACCACGGCCAAGCAAGGTCTGGCGGCGCTATGTTTCGTATCGGGCGA
CGATACGAATACGGTCAGCATCTCGCTCGGTCAGAGCGCCTCAGGTGTACAAGTCCAAGCGTTTCTCGGAAGTGTGAA
GATGCCGGTCAATACGTCCGGCATTAACAACATCGCGTTACCTCTCGACGGCCAGAACCATGCCTTCAACGCCTTCAC
CCGGTTTTATGCCGTGCCGCAGAGCCATTGGTATTCAGGGCAACTCCAAAGCGACATCAACCAGTTCATCTCGGTACA
GTTCAAGGAAGCGAGCGCTATCGTGAATATCGTCAATAAGCTCGTCGATCCAAGTACCGTTATTAAATATGCTGGTCC
CAGCATCCAGCAGCCGAATGTAGTTACAATAAATCCATCAGACAGCCAAACGATTTCCTGGAATCTTCAGGGGAATGG
GACGCAATTGGTCTGGATCAATGCCGACAGTGTACAAAATTCCCAAAGTGCGACAATAAGCGTCCAATCGCTCGCGGC
GGTTTACGACGCCTATAATCGAGGGTCGTTTGAAGAGTTGGAGGCGAAGGTCATGGCGAAGGCAAAAGCGGCGCGACC
CTAAGTCTCAGGATCGTCAGCACCCTGATGTGAATGCTTCAGGGTGCTGACGATCCGACACGGCATACCTGTATGTTC
TGGCCTAATCCAATTATAAAAGAGCGCGATCCCTAGAAAGGGTGCCTGGCGAGGGCATGCTTATACCACATCCGCAAG
AGAGACTCTTACGTGAGGGGCGGGCGTTTCATAACTGACCACTTCTGAAACAGGCAGCCTATACTTTTTGGCAACACA
TTGATAACATCATCCATACTTGTTCCTATCACGTTACGTGATGACATTTCTCGTTCACCAAGGCGGAGCCGGCAAGAC
GCCCCCCACCGCCGACACCATCGTGGTGTTGACGGCGCGAAGCCCTGAACGCATCATCCGTGAGGGCGGTTCGCAAGC
GTGGGTGCTCAACCCCGCCCGCGCGAAGCAATGCACCTGGCTGCTCTGCACCCAAAATCGCCATCACCCCGACCCTGA
GTTTTCGGATGCCACAGAACCGCACGGCATGGGCTTCCTGCTCGGGCGGATTGCGACCGTGCAGAAATCGAACGACCA
TGAGGGTCCCGGGGTCCGCTGGCTCATCGCCCTTCGCGAGTACGCGCGGATCCAGCTTCCCAAGGCCTGGGATCAGGG
GCGCAATCCCGTGCGCTACCGGGCCCTCGCCGACTTCCGGATCAATCTCGACAAGGTGACGTTTCAGCCGATGCCGCT
GGAGGAGAAGCCGCCGCCGCGGCGGGCCGGACACCCCGCGCCGAGCATCCTCACCCTCGCGGAGGCCAAGCGGCAGCT
GGCGGACACCTTCGGCGTCAAGCCGGAGGCCGTCGAAATCACGATTCGCGGCTGAGAGCCGGGGAAGGGGGCGGCCCT
GGCGCGCCAATCCACGCCGGCCCCGTTCTGTGAGGGACGCCCGCGAGGAGCCGCGCACCAACCGGGTAGCGCATTCTG
TCAGGGAAACGAGCGCGGCTACATGTCTGCTCTGAGGTCGGAGCTGGGGTTTGCTCACCCCCTCCATCCGCGAACGTC
GATCAAGACCACCGCGCGGCACGGGTGTGCACGGGTGTGAATGGGTTAGGAAGGCGAAACTGGATACTTGGTACGCGG
AGGGATACCAATATGGACTTCTCACGAAGAGACACGAAGAGACAACCAGGGATCACCGGCAAGACAGTGCTCTGTGAA
AGCCTGATGAAGAGATCCATCCGTGAATCATTCACCATGATCACAGCTATTTATCTACCAGCGAGCGCAACCGCGCGA
GCCGAGTGCGATGAGCCTGTTGTTGCAAATCGATGTGCTGCCCTCTCCGGGTAATTAAAATACATTCCGTCACAGGCT
GATCAATAATTTTATCGGAGATTGAAATATGGCTGAGGGTACTTGTCGCTGCCTGGCTGAATAAATAAATAAATGAAT
AAATCATCAGATTGCCTGCATCTTTTTGTGCACTATTATTTATTTATTCCCAATGATTTTCACGACCCCAATGATTTG
CCCGACGCGGACTAATTTACGAACATTGGTGTTTGTTCCGGTGCAGAACCAATTCATAGTCAATATGTGCCGCAGAAT
TATCTGCGAATCTCCCCCTGTTCACCAAAGCCGAAATATAGGTGAGAATCTTCTCTAGGGAAGGTCTGATTTATTCAA
CGTTCCGACAACTAATCAGCTCCATTCGCCGTGTTGTGCGTGCCAACTGAGTACAATCAGGAATTAATCAGACCTTCC
TTAAATAAATAAATGAATCATCAGATTGCCTACATCTTTTTGGGCACTATTATTTATTCCCAATGATTTGCCCCGACG
CGGACTGATTTAATAACATAGCGTTCTCCTTAATCGATGCCTTGGGCATTTTTAAAACAATAACTGGCAGGGAATGTC
CGTGTGAAAATGCCGGTGTTGTAGCGCGTACATACTGATTCCCCAGGGCCCTAATAGAAGCGGCCAGTTGCTGCCTTC
TCTTCCGCTCCAGAAATTCCCTGTATTCGCGGCCCAATTTCTTTATTGTATGCGTATAGACAGGTGTAGTGCTCCCCC
TAAAAATCAAGCCATCTAAGGAAGGTCTGATTTATTCCTGATTGTACTCAGACCTTCCTTAGTTTTTCTGGTCTTGCG
ACAACACGGACGCCGAGTTAATAAAGCATTCCTCGATTGGCACAAATGGCCTTTGTGAGACCTAAACCCCACCAGCAA
ACAGCCAGTTTGGCCAAGACGTATTGGCTGATCGAGAGAAGCCCGGTAATAGGCGTTGAGGCAATGCGCCCGCCTCGA
AATGTGTGAGGTCGTTACGCAATACCCAATAATTCCGGCTTCGATCCAGCGCATCCGTACAGGGAGAACGACACCAAT
AATGAAAATCATTTAAGGCATGGGTGACATCCTTTCCTGATGGTTGAGAAGTGTGAGAAATGTCGCTTGTTGCTGCAA
TAGGACTGGGGAGAAACTGAGAGATGAGCATCCCCAGCACGCTTATGGCAATGGCGATGCCGGTATAACTGCTCGTAA
ACACGGTTTGAATAGTCCTTACGTTTGATCTTCTCAATCGCTGTTAGTGACCCCGTTAGCTCCGTATGTGAGATGATA
AGATCACGAAGTCTGTCTTGACGGCGATTTCAATCGGGTAAAAATAAAGTTCAGTCAAGAACAACGTAAAAAAAATCA
CCCGCTAGGTATCCTACTGCTGTGAGCAGCTTGAGGCTCCAATGATGAGCACCAAGGGTCTAATTTATACCGGTCATC
GTATCCCCCCCCCGGCCAGGGTGGTGAAGTTGTCAGGTTCGCCGAGTTCGGCGATCACTAAGGATCGTTGAACACCCC
ATTTGAATGACATTTAGATCACCTCTTCTAATTCTCGCGACTGGCCACCATGAGCACGGAACACCCCGACAGATTCAA
CAGAAGCAGGCACATGACGAACAGGTTTCGGTTTACGCATTCTTCTTGCCCCCCGCTAAGTAAAGATAATGAGAAAGG
AGCTGGATAACTTCCTCAGAGGAGGTTACGGCATTGGAAGGAGAAAGCAAGCACTCGCTGAATTGCGGCCGTGAGAGG
CTGCGTCCCTCACGGTAAAGGCGTTGGCCACAGAGCGCCGCCAGGGCCGTCATCAGCACGCTCACCAGCGTGCGCTGG
ATTAGGGCTGCACCCTGTTCGAGTTGCCGCTCGATGGTCATCAGCTTGGAAGTGTATTCCACTGCCTCCGTGGTCTCT
CTGACGGGATCAGTCTGTTTCACAACGAGCGGCACCATGACCGCCTGTCCGTTGAGTGGGTGCTTGATGTGTGTGGAT
ACTCCTGAAGCGCGATGGTCACGCTCATCAAAAGTTATCGAGGAATCCAATAGAGCCGTGATCACCTCCCCAATAAAG
CTAAAACTCACCTGAGTTGTAAAAAAAACTCCAGTTGACACAAAATAGACTACGAAAGTGGCTTTAACATATCTGAAC
ACACAATAGCTAAGACCCAAACTGGGATTAG"
      },
      annot {
        {
          data ftable {
            {
              data gene {
                locus-tag "DYY67_2330"
              },
              location int {
                from 70,
                to 360,
                strand plus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2331"
              },
              location int {
                from 396,
                to 638,
                strand plus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2332"
              },
              location int {
                from 746,
                to 1021,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2333"
              },
              location int {
                from 1023,
                to 1694,
                strand plus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2334"
              },
              location int {
                from 1919,
                to 2275,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2335"
              },
              location int {
                from 3104,
                to 3649,
                strand plus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2336"
              },
              location int {
                from 4009,
                to 4863,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2337"
              },
              location int {
                from 6088,
                to 6267,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2338"
              },
              location int {
                from 6248,
                to 6628,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2339"
              },
              location int {
                from 7132,
                to 7527,
                strand plus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2340"
              },
              location int {
                from 7966,
                to 8127,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2341"
              },
              location int {
                from 8424,
                to 9353,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2342"
              },
              location int {
                from 9375,
                to 9656,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2343"
              },
              location int {
                from 9677,
                to 10297,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2344"
              },
              location int {
                from 10533,
                to 10859,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2345"
              },
              location int {
                from 10856,
                to 11182,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2346"
              },
              location int {
                from 11339,
                to 11932,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2347"
              },
              location int {
                from 12131,
                to 12421,
                strand plus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2348"
              },
              location int {
                from 12457,
                to 12699,
                strand plus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2349"
              },
              location int {
                from 12806,
                to 13042,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2350"
              },
              location int {
                from 13173,
                to 13481,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2351"
              },
              location int {
                from 13478,
                to 13783,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2352"
              },
              location int {
                from 13980,
                to 14336,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2353"
              },
              location int {
                from 15023,
                to 15811,
                strand plus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2354"
              },
              location int {
                from 16070,
                to 16924,
                strand minus,
                id local str "ctg7180000000092"
              }
            },
            {
              data gene {
                locus-tag "DYY67_2355"
              },
              partial TRUE,
              location int {
                from 18726,
                to 19270,
                strand minus,
                id local str "ctg7180000000092",
                fuzz-to lim gt
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2330"
        }
      },
      descr {
        title "Prevent host death protein, Phd antitoxin [Candidatus
 Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2330"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 96,
        seq-data ncbieaa "MNTTTISPVAVKIDAALKNRLKRLASLRQRKPHWLMREAIAQYVEREEQRED
FKKEALTAWKDYQTTGKHVTGDEVITWLETWGEQQTKPAPKCHK"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "Prevent host death protein, Phd antitoxin"
                }
              },
              location int {
                from 0,
                to 95,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2330"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2331"
        }
      },
      descr {
        title "Death on curing protein, Doc toxin [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2331"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 80,
        seq-data ncbieaa "MQEFLLTKTPVSAKRAGQAIIKNIRLLKSNPQIGRQVEGMLPEFRELIIQFG
DSGYVALYHYAGDVVTVLTIRHQKEAGH"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "Death on curing protein, Doc toxin"
                }
              },
              location int {
                from 0,
                to 79,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2331"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2332"
        }
      },
      descr {
        title "hypothetical protein PA0941 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2332"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 91,
        seq-data ncbieaa "MQFVITTTFVRGYMSKKAVFYHAGCPVCVDAEKNVANALDRSRYSVEIVHLG
EQKGRITEAEAAGVKSVPALVLEGQPFHINFGAGLDALK"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein PA0941"
                }
              },
              location int {
                from 0,
                to 90,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2332"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2333"
        }
      },
      descr {
        title "hypothetical protein DYY67_2333 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2333"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 223,
        seq-data ncbieaa "MLASNIAVVRHGGQGSLRAYLYFQKWFLAASVNKSALLSDGGSIPRTMKNPD
DDKCSLGDLVVNGIRMVKRHPQARAELVAGRANQWRVACHIYCLGNPVKVTGCSRFTRFGRNVSPDFRKVGFRCIGEV
KGQGLADNFLPLAMMRFLSNLRTDRRNIRQSFIDIRFQCRELMRLECPPLFPLAHSFSHDFTGRGIVPIVNRRLDNRC
HVSRHGGWSCVQYSP"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 222,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2333"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2334"
        }
      },
      descr {
        title "hypothetical protein DYY67_2334 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2334"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 118,
        seq-data ncbieaa "MQLHLRVGLILMVLVATAGCTKRNLQHDITDVTAALKMWELEQKKTGAPQSI
TCLKLASVIIEADATKELDAGVSANVQPSPTATSNANATRAGTSKITIQWNGINDPDKGCTSPPAP"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 117,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2334"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2335"
        }
      },
      descr {
        title "hypothetical protein DYY67_2335 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2335"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 181,
        seq-data ncbieaa "MSCGVTRNRRYRSLSQAPRPKQGLAALCFVSGDDTNTVSISLGQSASGVQVQ
AFLGSVKMPVNTSGINNIALPLDGQNHAFNAFTRFYAVPQSHWYSGQLQSDINQFISVQFKEASAIVNIVNKLVDPST
VIKYAGPSIQQPNVVTINPSDSQTISWNLQGMGRNWSGSMPTVYKIPKVRQ"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 180,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2335"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2336"
        }
      },
      descr {
        title "hypothetical protein DYY67_2336 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2336"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 284,
        seq-data ncbieaa "MRSPYWYPSAYQVSSFAFLTHSHPCTPVPRGGLDRRSRMEGVSKPQLRPQSR
HVAALVSLTECATRLVRGSSRASLTERGRRGLARQGRPLPRLSAANRDFDGLRLDAEGVRQLPLGLREGEDARRGVSG
PPRRRLLLQRHRLKRHLVEIDPEVGEGPVAHGIAPLIPGLGKLDPRVLAKGDEPADPGTLMVVRFLHGRNPPEQEAHA
VRFCGIRKLRVGVMAILGAEQPGALLRAGGVEHPRLRTALTDDAFRASRRQHHDGVGGGGRLAGSALVNEKCHHVT"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 283,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2336"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2337"
        }
      },
      descr {
        title "hypothetical protein DYY67_2337 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2337"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 59,
        seq-data ncbieaa "MRRSNRKDYSNRVYEQYTGIAIAISVLGMLISQFLPSPIAATSDISHTSQPS
GKDVTHA"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 58,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2337"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2338"
        }
      },
      descr {
        title "hypothetical protein DYY67_2338 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2338"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 126,
        seq-data ncbieaa "MCLLLLNLSGCSVLMVASRENRRGDLNVIQMGVQRSLVIAELGEPDNFTTLA
GGGYDDRYKLDPGAHHWSLKLLTAVGYLAGDFFTLFLTELIFTPIEIAVKDRLVIYHLTYGANGSLTAIEKIKP"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 125,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2338"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2339"
        }
      },
      descr {
        title "hypothetical protein DYY67_2339 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2339"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 131,
        seq-data ncbieaa "MVMSYVFCPLWLHERRMPPAIAGEASRLDEGAQPPHLSEVVPSVGSPAIGNL
SGLTRGHVRRSGRGSPLLRPNDDGWLINQYFIVNQYVVTLLRGSGRAFSYTGSLRERLAGATCRQLTAGRHRRRAYGPA"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 130,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2339"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2340"
        }
      },
      descr {
        title "hypothetical protein DYY67_2340 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2340"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 53,
        seq-data ncbieaa "MEKDFVSFPQLRLEPKERKKIAFKRVSEEGGGHRMLSNAIIKRLGRPQSNETE"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 52,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2340"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2341"
        }
      },
      descr {
        title "IncW-like replication protein [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2341"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 309,
        seq-data ncbieaa "MPLTPQQENFLDAAVAIRLDPDKAEAAFIARQLVQATLPHRNPKTDTWRRTN
GNFVLGMQAGYDALTDKKYGLPYGTIPRLLLFWITTEALRTANRRLELGNSLASFMRQLDLDPSRGGKRSDAKRIREQ
MERLFNAKISFQQSHNQKGKKGYAWMNMDVAPKGMLWWDEKQPHQSTLWKSWIQLGEEFFAAITSSPVPVDMRALKAL
KSSPLALDLYSWATYTAYRTQQNGQARSISWKILHNQLGTENHDIKDFSKKAKAAFKKIQQVYPDLGLQYIRGGVSVL
PCNPAITIKLKPQQLTHHLDTLK"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "IncW-like replication protein"
                }
              },
              location int {
                from 0,
                to 308,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2341"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2342"
        }
      },
      descr {
        title "hypothetical protein DYY67_2342 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2342"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 93,
        seq-data ncbieaa "MKKHSALKQSLSAAAGKPVPLEPNPTVLPKTKQQSKDVLVGAFYAPEVRKAL
RFIEAESGLTLKQLLGRAINQLAVEYGKPEPYTDTDHRSQN"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 92,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2342"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2343"
        }
      },
      descr {
        title "Chromosome [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2343"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 206,
        seq-data ncbieaa "MKSLAVISQKGGSGKSTTAQGLAVEAMRTGLKVALIDLDQQASTGKWSDRRE
ESDRLAVVCSPAARLPKVLNQAKTEGVDFVVIDTPPHAGQIAIEAAKLADRILIPIEPHISSLETLTTVSDILNLAGK
PPAEVLINDAPVQGRRHEDAREWLIEQGFKVAPVVLFHRAAHSDAGDLGKTAGELDPLGKAAVEMKQLYIYIYRLL"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "Chromosome"
                }
              },
              location int {
                from 0,
                to 205,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2343"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2344"
        }
      },
      descr {
        title "hypothetical protein DYY67_2344 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2344"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 108,
        seq-data ncbieaa "MNMPLTHDFKETIRTRAQKDKAFRDALLREGIEAFVSGDVEAGKAVMRDYIN
ATIGFGALSKATKMPSKSLMRQFSPSGNPQARNLFAVLGYLQKQAGLSFELRPAKH"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 107,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2344"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2345"
        }
      },
      descr {
        title "hypothetical protein DYY67_2345 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2345"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 108,
        seq-data ncbieaa "MIEMRGYIDRNGRAVFKEWFDELEATASAKVAIALTRMELGNFSNTNGVGSS
VLEYRIDWGAGYRIYFAKDGDALIILLAGGTKRRQNSDIETALSRWADYKLRKKGI"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 107,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2345"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2346"
        }
      },
      descr {
        title "hypothetical protein DYY67_2346 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2346"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 197,
        seq-data ncbieaa "MRTAFYIRVSSPRGQKTDSQRAELEAWRTRQRLKAVRWFEDKDSATNFQRPA
FQQLQSAIFKGEIETVVVWKLDRLARSLKDGINILADWCKRDVRVIAVTQQIDLSGTVGHLIASLLFGIAEMELQHTK
ERQAIGIALARQRGVYKGRLAGTTKATPKRAQELRRQGLTVPEIANALNVSPRTVFNYLHLSRPHSV"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 196,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2346"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2347"
        }
      },
      descr {
        title "Prevent host death protein, Phd antitoxin [Candidatus
 Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2347"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 96,
        seq-data ncbieaa "MNTTTISPVAVKIDAALKNRLKRLASLRQRKPHWLMREAIAQYVEREEQRED
FKKEALTAWKDYQTTGKHVTGDEVITWLETWGEQQTKPAPKCHK"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "Prevent host death protein, Phd antitoxin"
                }
              },
              location int {
                from 0,
                to 95,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2347"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2348"
        }
      },
      descr {
        title "Death on curing protein, Doc toxin [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2348"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 80,
        seq-data ncbieaa "MQEFLLTKTPVSAKRAGQAIIKNIRLLKSNPQIGRQVEGMLPEFRELIIQFG
DSGYVALYHYAGDVVTVLTIRHQKEAGH"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "Death on curing protein, Doc toxin"
                }
              },
              location int {
                from 0,
                to 79,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2348"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2349"
        }
      },
      descr {
        title "hypothetical protein PA0941 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2349"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 78,
        seq-data ncbieaa "MSKKAVFYHAGCPVCVDAEKNVANALDRSRYSVEIVHLGEQKGRITEAEAAG
VKSVPALVLEGQPFHINFGAGLDALK"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein PA0941"
                }
              },
              location int {
                from 0,
                to 77,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2349"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2350"
        }
      },
      descr {
        title "hypothetical protein DYY67_2350 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2350"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 102,
        seq-data ncbieaa "MTLHLTDAAETDLAEIWGYIATEAGEPTATRYLDRITKTIDVARHSPLIGTT
RDQLGTGLRVTFHHPYAIYYQVTKRTLIVVRVLHGARDAAAIAEQGGFIH"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 101,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2350"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2351"
        }
      },
      descr {
        title "hypothetical protein DYY67_2351 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2351"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 101,
        seq-data ncbieaa "MNYESYTEDAMASIERMTITMPTDMAAVIKTAVDDGDYASTSEVVREAVREW
KQRRAFQSHEFAALKADIDKGLADIAAGRVRKFDKKRIIAKGRKLSAKP"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 100,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2351"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2352"
        }
      },
      descr {
        title "hypothetical protein DYY67_2352 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2352"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 118,
        seq-data ncbieaa "MQLHLRVGLILMVLVATAGCTKRNLQHDITDVTAALKMWELEQKKTGAPQSI
TCLKLASVIIEADATKELDAGVSANVQPSPTATSNANATRAGTSKITIQWNGINDPDKGCTSPPAP"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 117,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2352"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2353"
        }
      },
      descr {
        title "hypothetical protein DYY67_2353 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2353"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 262,
        seq-data ncbieaa "MMINWNGGQLITLNPGDTATCAGGLNPGQVYAIFLYNSANNDANAPVNVVWS
NSQPPVPVTVPGTTAKQGLAALCFVSGDDTNTVSISLGQSASGVQVQAFLGSVKMPVNTSGINNIALPLDGQNHAFNA
FTRFYAVPQSHWYSGQLQSDINQFISVQFKEASAIVNIVNKLVDPSTVIKYAGPSIQQPNVVTINPSDSQTISWNLQG
NGTQLVWINADSVQNSQSATISVQSLAAVYDAYNRGSFEELEAKVMAKAKAARP"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 261,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2353"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2354"
        }
      },
      descr {
        title "hypothetical protein DYY67_2354 [Candidatus Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2354"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 284,
        seq-data ncbieaa "MRSPYWYPSAYQVSSFAFLTHSHPCTPVPRGGLDRRSRMEGVSKPQLRPQSR
HVAALVSLTECATRLVRGSSRASLTERGRRGLARQGRPLPRLSAANRDFDGLRLDAEGVRQLPLGLREGEDARRGVSG
PPRRRLLLQRHRLKRHLVEIDPEVGEGPVAHGIAPLIPGLGKLDPRVLAKGDEPADPGTLMVVRFLHGRNPPEQEAHA
VRFCGIRKLRVGVMAILGAEQPGALLRAGGVEHPRLRTALTDDAFRASRRQHHDGVGGGGRLAGSALVNEKCHHVT"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              location int {
                from 0,
                to 283,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2354"
                }
              }
            }
          }
        }
      }
    },
    seq {
      id {
        general {
          db "zhongguo",
          tag str "DYY67_2355"
        }
      },
      descr {
        title "hypothetical protein DYY67_2355, partial [Candidatus
 Nitrosotalea sp.]",
        molinfo {
          biomol peptide,
          tech concept-trans,
          completeness no-left
        },
        user {
          type str "OriginalID",
          data {
            {
              label str "General",
              data str "gnl|zhongguo|DYY67_2355"
            }
          }
        }
      },
      inst {
        repr raw,
        mol aa,
        length 180,
        seq-data ncbieaa "NPSLGLSYCVFRYVKATFVVYFVSTGVFFTTQVSFSFIGEVITALLDSSITF
DERDHRASGVSTHIKHPLNGQAVMVPLVVKQTDPVRETTEAVEYTSKLMTIERQLEQGAALIQRTLVSVLMTALAALC
GQRLYREGRSLSRPQFSECLLSPSNAVTSSEEVIQLLSHYLYLAGGKKNA"
      },
      annot {
        {
          data ftable {
            {
              data prot {
                name {
                  "hypothetical protein"
                }
              },
              partial TRUE,
              location int {
                from 0,
                to 179,
                id general {
                  db "zhongguo",
                  tag str "DYY67_2355"
                },
                fuzz-from lim lt
              }
            }
          }
        }
      }
    }
  },
  annot {
    {
      data ftable {
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2330"
          },
          location int {
            from 70,
            to 360,
            strand plus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2331"
          },
          location int {
            from 396,
            to 638,
            strand plus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2332"
          },
          location int {
            from 746,
            to 1021,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2333"
          },
          location int {
            from 1023,
            to 1694,
            strand plus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2334"
          },
          location int {
            from 1919,
            to 2275,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2335"
          },
          location int {
            from 3104,
            to 3649,
            strand plus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2336"
          },
          location int {
            from 4009,
            to 4863,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2337"
          },
          location int {
            from 6088,
            to 6267,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2338"
          },
          location int {
            from 6248,
            to 6628,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2339"
          },
          location int {
            from 7132,
            to 7527,
            strand plus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2340"
          },
          location int {
            from 7966,
            to 8127,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2341"
          },
          location int {
            from 8424,
            to 9353,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2342"
          },
          location int {
            from 9375,
            to 9656,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2343"
          },
          location int {
            from 9677,
            to 10297,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2344"
          },
          location int {
            from 10533,
            to 10859,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2345"
          },
          location int {
            from 10856,
            to 11182,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2346"
          },
          location int {
            from 11339,
            to 11932,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2347"
          },
          location int {
            from 12131,
            to 12421,
            strand plus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2348"
          },
          location int {
            from 12457,
            to 12699,
            strand plus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2349"
          },
          location int {
            from 12806,
            to 13042,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2350"
          },
          location int {
            from 13173,
            to 13481,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2351"
          },
          location int {
            from 13478,
            to 13783,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2352"
          },
          location int {
            from 13980,
            to 14336,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2353"
          },
          location int {
            from 15023,
            to 15811,
            strand plus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame one,
            code {
              id 11
            }
          },
          product whole general {
            db "zhongguo",
            tag str "DYY67_2354"
          },
          location int {
            from 16070,
            to 16924,
            strand minus,
            id local str "ctg7180000000092"
          }
        },
        {
          data cdregion {
            frame three,
            code {
              id 11
            }
          },
          partial TRUE,
          product whole general {
            db "zhongguo",
            tag str "DYY67_2355"
          },
          location int {
            from 18726,
            to 19270,
            strand minus,
            id local str "ctg7180000000092",
            fuzz-to lim gt
          }
        }
      }
    }
  }
}
