Seq-annot ::= {
  data ftable {
    {
      id local id 1,
      data biosrc {
        genome genomic,
        org {
          orgname {
            mod {
              {
                subtype strain,
                subname "NOD/ShiLtJ"
              }
            }
          }
        },
        subtype {
          {
            subtype chromosome,
            name "6"
          },
          {
            subtype map,
            name "6qF3"
          }
        }
      },
      location int {
        from 0,
        to 620322,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id0"
        },
        {
          qual "Name",
          val "6"
        },
        {
          qual "mol_type",
          val "genomic DNA"
        }
      },
      dbxref {
        {
          db "taxon",
          tag id 10090
        }
      }
    },
    {
      id local id 2,
      data imp {
        key "STS"
      },
      location int {
        from 1566,
        to 1917,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id2"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 130925
        }
      }
    },
    {
      id local id 3,
      data imp {
        key "STS"
      },
      location int {
        from 5921,
        to 6061,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id123"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 166300
        }
      }
    },
    {
      id local id 4,
      data gene {
        locus "Klra9",
        desc "killer cell lectin-like receptor subfamily A, member 9",
        syn {
          "Ly49I",
          "LY49I1"
        }
      },
      location int {
        from 8625,
        to 22895,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "gene0"
        },
        {
          qual "Name",
          val "Klra9"
        },
        {
          qual "gene_biotype",
          val "protein_coding"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16640
        },
        {
          db "MGI",
          tag str "MGI:1321153"
        }
      }
    },
    {
      id local id 5,
      data rna {
        type mRNA
      },
      except TRUE,
      comment "The RefSeq transcript has 27 substitutions, 1 non-frameshifting
 indel compared to this genomic sequence",
      location mix {
        int {
          from 22758,
          to 22895,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "Parent",
          val "gene0"
        },
        {
          qual "ID",
          val "rna0"
        },
        {
          qual "gene",
          val "Klra9"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor subfamily A, member 9"
        },
        {
          qual "transcript_id",
          val "NM_010651.3"
        }
      },
      xref {
        {
          id local id 6
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16640
        },
        {
          db "Genbank",
          tag str "NM_010651.3"
        },
        {
          db "MGI",
          tag str "MGI:1321153"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 6,
      data cdregion {
        frame one
      },
      except TRUE,
      comment "The RefSeq protein has 12 substitutions compared to this
 genomic sequence",
      location mix {
        int {
          from 20967,
          to 21078,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        },
        int {
          from 19496,
          to 19585,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "ID",
          val "cds0"
        },
        {
          qual "gene",
          val "Klra9"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor subfamily A, member 9"
        },
        {
          qual "protein_id",
          val "NP_034781.2"
        },
        {
          qual "Parent",
          val "rna0"
        }
      },
      xref {
        {
          id local id 5
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16640
        },
        {
          db "Genbank",
          tag str "NP_034781.2"
        },
        {
          db "MGI",
          tag str "MGI:1321153"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 7,
      data imp {
        key "STS"
      },
      location int {
        from 18472,
        to 18611,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id389"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 143711
        }
      }
    },
    {
      id local id 8,
      data imp {
        key "STS"
      },
      location int {
        from 24591,
        to 24614,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id644"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 271146
        }
      }
    },
    {
      id local id 9,
      data imp {
        key "STS"
      },
      location int {
        from 33150,
        to 33252,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id936"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 258434
        }
      }
    },
    {
      id local id 10,
      data imp {
        key "STS"
      },
      location int {
        from 62097,
        to 62356,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id1777"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 258348
        }
      }
    },
    {
      id local id 11,
      data gene {
        locus "Klra7",
        desc "killer cell lectin-like receptor, subfamily A, member 7",
        syn {
          "LGL-1",
          "Ly-49G.1",
          "Ly-49G.2",
          "Ly-49G.3",
          "Ly49g",
          "Ly49G.4",
          "Ly49g1",
          "Ly49g2"
        }
      },
      location int {
        from 64023,
        to 81112,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "gene1"
        },
        {
          qual "Name",
          val "Klra7"
        },
        {
          qual "gene_biotype",
          val "protein_coding"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16638
        },
        {
          db "MGI",
          tag str "MGI:101901"
        }
      }
    },
    {
      id local id 12,
      data rna {
        type mRNA
      },
      except TRUE,
      comment "The RefSeq transcript has 15 substitutions, 1 non-frameshifting
 indel compared to this genomic sequence",
      location mix {
        int {
          from 79292,
          to 79473,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "Parent",
          val "gene1"
        },
        {
          qual "ID",
          val "rna1"
        },
        {
          qual "gene",
          val "Klra7"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor, subfamily A, member 7,
 transcript variant 2"
        },
        {
          qual "transcript_id",
          val "NM_014194.5"
        }
      },
      xref {
        {
          id local id 16
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16638
        },
        {
          db "Genbank",
          tag str "NM_014194.5"
        },
        {
          db "MGI",
          tag str "MGI:101901"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 13,
      data rna {
        type mRNA
      },
      except TRUE,
      comment "The RefSeq transcript has 15 substitutions compared to this
 genomic sequence",
      location mix {
        int {
          from 81038,
          to 81112,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "Parent",
          val "gene1"
        },
        {
          qual "ID",
          val "rna2"
        },
        {
          qual "gene",
          val "Klra7"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor, subfamily A, member 7,
 transcript variant 1"
        },
        {
          qual "transcript_id",
          val "NM_001110323.1"
        }
      },
      xref {
        {
          id local id 17
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16638
        },
        {
          db "Genbank",
          tag str "NM_001110323.1"
        },
        {
          db "MGI",
          tag str "MGI:101901"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 14,
      data gene {
        locus "Klra13-ps",
        desc "killer cell lectin-like receptor subfamily A, member 13,
 pseudogene",
        syn {
          "Klra13",
          "Ly49M"
        }
      },
      location int {
        from 64312,
        to 230751,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "gene2"
        },
        {
          qual "Name",
          val "Klra13-ps"
        },
        {
          qual "gene_biotype",
          val "misc_RNA"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16631
        },
        {
          db "MGI",
          tag str "MGI:1321090"
        }
      },
      pseudo TRUE
    },
    {
      id local id 15,
      data imp {
        key "misc_RNA"
      },
      except TRUE,
      comment "The RefSeq transcript has 13 substitutions compared to this
 genomic sequence",
      location mix {
        int {
          from 230635,
          to 230751,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "Parent",
          val "gene2"
        },
        {
          qual "ID",
          val "rna3"
        },
        {
          qual "Name",
          val "NR_033451.1"
        },
        {
          qual "gene",
          val "Klra13-ps"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor subfamily A, member 13,
 pseudogene"
        },
        {
          qual "transcript_id",
          val "NR_033451.1"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16631
        },
        {
          db "Genbank",
          tag str "NR_033451.1"
        },
        {
          db "MGI",
          tag str "MGI:1321090"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 16,
      data cdregion {
        frame one,
        code-break {
          {
            loc int {
              from 76466,
              to 76468,
              strand minus,
              id other {
                accession "NW_006763130",
                version 1
              }
            },
            aa ncbieaa 85
          }
        }
      },
      except TRUE,
      comment "isoform 2 is encoded by transcript variant 2; The RefSeq
 protein has 9 substitutions compared to this genomic sequence",
      location mix {
        int {
          from 79292,
          to 79403,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        },
        int {
          from 77723,
          to 77812,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "ID",
          val "cds1"
        },
        {
          qual "gene",
          val "Klra7"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor 7 isoform 2"
        },
        {
          qual "protein_id",
          val "NP_055009.5"
        },
        {
          qual "Parent",
          val "rna1"
        }
      },
      xref {
        {
          id local id 12
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16638
        },
        {
          db "Genbank",
          tag str "NP_055009.5"
        },
        {
          db "MGI",
          tag str "MGI:101901"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 17,
      data cdregion {
        frame one,
        code-break {
          {
            loc int {
              from 76466,
              to 76468,
              strand minus,
              id other {
                accession "NW_006763130",
                version 1
              }
            },
            aa ncbieaa 85
          }
        }
      },
      except TRUE,
      comment "isoform 1 is encoded by transcript variant 1; The RefSeq
 protein has 9 substitutions compared to this genomic sequence",
      location mix {
        int {
          from 79292,
          to 79403,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        },
        int {
          from 77723,
          to 77812,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "ID",
          val "cds2"
        },
        {
          qual "gene",
          val "Klra7"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor 7 isoform 1"
        },
        {
          qual "protein_id",
          val "NP_001103793.1"
        },
        {
          qual "Parent",
          val "rna2"
        }
      },
      xref {
        {
          id local id 13
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16638
        },
        {
          db "Genbank",
          tag str "NP_001103793.1"
        },
        {
          db "MGI",
          tag str "MGI:101901"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 18,
      data imp {
        key "STS"
      },
      location int {
        from 64926,
        to 65262,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id1856"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 166310
        }
      }
    },
    {
      id local id 19,
      data imp {
        key "STS"
      },
      location int {
        from 74299,
        to 74537,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id2176"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 143717
        }
      }
    },
    {
      id local id 20,
      data imp {
        key "STS"
      },
      location int {
        from 74908,
        to 76378,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id2208"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 143715
        }
      }
    },
    {
      id local id 21,
      data gene {
        locus "LOC100862408"
      },
      location int {
        from 110253,
        to 133162,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "gene3"
        },
        {
          qual "Name",
          val "LOC100862408"
        },
        {
          qual "gene_biotype",
          val "pseudogene"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 100862408
        }
      },
      pseudo TRUE
    },
    {
      id local id 22,
      data imp {
        key "exon"
      },
      location int {
        from 110253,
        to 110388,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "Parent",
          val "gene3"
        },
        {
          qual "ID",
          val "id3726"
        },
        {
          qual "gene",
          val "LOC100862408"
        },
        {
          qual "model_evidence",
          val "Supporting evidence includes similarity to: 34 Proteins, and
 11% coverage of the annotated genomic feature by RNAseq alignments"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 100862408
        }
      }
    },
    {
      id local id 23,
      data imp {
        key "STS"
      },
      location int {
        from 110849,
        to 111186,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id3727"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 166310
        }
      }
    },
    {
      id local id 24,
      data imp {
        key "exon"
      },
      location int {
        from 119143,
        to 119246,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "Parent",
          val "gene3"
        },
        {
          qual "ID",
          val "id3728"
        },
        {
          qual "gene",
          val "LOC100862408"
        },
        {
          qual "model_evidence",
          val "Supporting evidence includes similarity to: 34 Proteins, and
 11% coverage of the annotated genomic feature by RNAseq alignments"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 100862408
        }
      }
    },
    {
      id local id 25,
      data imp {
        key "STS"
      },
      location int {
        from 127165,
        to 128682,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id3729"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 515498
        }
      }
    },
    {
      id local id 26,
      data imp {
        key "exon"
      },
      location int {
        from 127430,
        to 127572,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "Parent",
          val "gene3"
        },
        {
          qual "ID",
          val "id3730"
        },
        {
          qual "gene",
          val "LOC100862408"
        },
        {
          qual "model_evidence",
          val "Supporting evidence includes similarity to: 34 Proteins, and
 11% coverage of the annotated genomic feature by RNAseq alignments"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 100862408
        }
      }
    },
    {
      id local id 27,
      data imp {
        key "exon"
      },
      location int {
        from 129840,
        to 130046,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "Parent",
          val "gene3"
        },
        {
          qual "ID",
          val "id3731"
        },
        {
          qual "gene",
          val "LOC100862408"
        },
        {
          qual "model_evidence",
          val "Supporting evidence includes similarity to: 34 Proteins, and
 11% coverage of the annotated genomic feature by RNAseq alignments"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 100862408
        }
      }
    },
    {
      id local id 28,
      data imp {
        key "exon"
      },
      location int {
        from 130923,
        to 131012,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "Parent",
          val "gene3"
        },
        {
          qual "ID",
          val "id3732"
        },
        {
          qual "gene",
          val "LOC100862408"
        },
        {
          qual "model_evidence",
          val "Supporting evidence includes similarity to: 34 Proteins, and
 11% coverage of the annotated genomic feature by RNAseq alignments"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 100862408
        }
      }
    },
    {
      id local id 29,
      data imp {
        key "exon"
      },
      location int {
        from 133051,
        to 133162,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "Parent",
          val "gene3"
        },
        {
          qual "ID",
          val "id3733"
        },
        {
          qual "gene",
          val "LOC100862408"
        },
        {
          qual "model_evidence",
          val "Supporting evidence includes similarity to: 34 Proteins, and
 11% coverage of the annotated genomic feature by RNAseq alignments"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 100862408
        }
      }
    },
    {
      id local id 30,
      data imp {
        key "STS"
      },
      location int {
        from 149296,
        to 149619,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id3734"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 143706
        }
      }
    },
    {
      id local id 31,
      data gene {
        locus "Klra16",
        desc "killer cell lectin-like receptor, subfamily A, member 16",
        syn {
          "Klra24",
          "Ly-49P",
          "Ly49P",
          "Ly49x"
        }
      },
      location int {
        from 149511,
        to 173163,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "gene4"
        },
        {
          qual "Name",
          val "Klra16"
        },
        {
          qual "gene_biotype",
          val "protein_coding"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 27424
        },
        {
          db "MGI",
          tag str "MGI:1351669"
        }
      }
    },
    {
      id local id 32,
      data rna {
        type mRNA
      },
      except TRUE,
      comment "The RefSeq transcript has 6 substitutions, 2 non-frameshifting
 indels compared to this genomic sequence",
      location mix {
        int {
          from 173084,
          to 173163,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "Parent",
          val "gene4"
        },
        {
          qual "ID",
          val "rna4"
        },
        {
          qual "gene",
          val "Klra16"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor, subfamily A, member 16"
        },
        {
          qual "transcript_id",
          val "NM_013794.4"
        }
      },
      xref {
        {
          id local id 33
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 27424
        },
        {
          db "Genbank",
          tag str "NM_013794.4"
        },
        {
          db "MGI",
          tag str "MGI:1351669"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 33,
      data cdregion {
        frame one
      },
      except TRUE,
      comment "The RefSeq protein has 5 substitutions compared to this genomic
 sequence",
      location mix {
        int {
          from 171201,
          to 171312,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        },
        int {
          from 169825,
          to 169914,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "ID",
          val "cds3"
        },
        {
          qual "gene",
          val "Klra16"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor, subfamily A, member 16"
        },
        {
          qual "protein_id",
          val "NP_038822.3"
        },
        {
          qual "Parent",
          val "rna4"
        }
      },
      xref {
        {
          id local id 32
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 27424
        },
        {
          db "Genbank",
          tag str "NP_038822.3"
        },
        {
          db "MGI",
          tag str "MGI:1351669"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 34,
      data imp {
        key "STS"
      },
      location int {
        from 156289,
        to 156615,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id3742"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 166310
        }
      }
    },
    {
      id local id 35,
      data imp {
        key "STS"
      },
      location int {
        from 239423,
        to 239709,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id4612"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 130925
        }
      }
    },
    {
      id local id 36,
      data gene {
        locus "Klra3",
        desc "killer cell lectin-like receptor, subfamily A, member 3",
        syn {
          "5E6",
          "Ly49c",
          "Nk-2",
          "NK-2.1",
          "Nk2",
          "Nk2.1"
        }
      },
      location int {
        from 248233,
        to 292460,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "gene5"
        },
        {
          qual "Name",
          val "Klra3"
        },
        {
          qual "gene_biotype",
          val "protein_coding"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16634
        },
        {
          db "MGI",
          tag str "MGI:101905"
        }
      }
    },
    {
      id local id 37,
      data rna {
        type mRNA
      },
      except TRUE,
      comment "The RefSeq transcript has 49 substitutions, 1 non-frameshifting
 indel compared to this genomic sequence",
      location mix {
        int {
          from 292305,
          to 292460,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "Parent",
          val "gene5"
        },
        {
          qual "ID",
          val "rna5"
        },
        {
          qual "gene",
          val "Klra3"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor, subfamily A, member 3,
 transcript variant 1"
        },
        {
          qual "transcript_id",
          val "NM_010648.3"
        }
      },
      xref {
        {
          id local id 38
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16634
        },
        {
          db "Genbank",
          tag str "NM_010648.3"
        },
        {
          db "MGI",
          tag str "MGI:101905"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 38,
      data cdregion {
        frame one
      },
      except TRUE,
      comment "The RefSeq protein has 13 substitutions, 1 non-frameshifting
 indel compared to this genomic sequence",
      location mix {
        int {
          from 290526,
          to 290637,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        },
        int {
          from 289047,
          to 289136,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "ID",
          val "cds4"
        },
        {
          qual "gene",
          val "Klra3"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor 3"
        },
        {
          qual "protein_id",
          val "NP_034778.2"
        },
        {
          qual "Parent",
          val "rna5"
        }
      },
      xref {
        {
          id local id 37
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16634
        },
        {
          db "Genbank",
          tag str "NP_034778.2"
        },
        {
          db "MGI",
          tag str "MGI:101905"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 39,
      data imp {
        key "STS"
      },
      location int {
        from 268997,
        to 269301,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id5025"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 130925
        }
      }
    },
    {
      id local id 40,
      data imp {
        key "STS"
      },
      location int {
        from 288041,
        to 288180,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id5339"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 143711
        }
      }
    },
    {
      id local id 41,
      data imp {
        key "STS"
      },
      location int {
        from 294170,
        to 294199,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id5581"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 271146
        }
      }
    },
    {
      id local id 42,
      data imp {
        key "STS"
      },
      location int {
        from 294170,
        to 294187,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id5582"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 271146
        }
      }
    },
    {
      id local id 43,
      data imp {
        key "STS"
      },
      location int {
        from 315717,
        to 316047,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id6701"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 143706
        }
      }
    },
    {
      id local id 44,
      data gene {
        locus "Klra1",
        desc "killer cell lectin-like receptor, subfamily A, member 1",
        syn {
          "A1",
          "CH29-493D4.3",
          "Klra22",
          "Ly49a",
          "Ly49o<129>",
          "Ly49v"
        }
      },
      location int {
        from 315936,
        to 338920,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "gene6"
        },
        {
          qual "Name",
          val "Klra1"
        },
        {
          qual "gene_biotype",
          val "protein_coding"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16627
        },
        {
          db "MGI",
          tag str "MGI:101907"
        }
      }
    },
    {
      id local id 45,
      data rna {
        type mRNA
      },
      except TRUE,
      comment "The RefSeq transcript has 16 substitutions, 2 non-frameshifting
 indels compared to this genomic sequence",
      location mix {
        int {
          from 338873,
          to 338920,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "Parent",
          val "gene6"
        },
        {
          qual "ID",
          val "rna6"
        },
        {
          qual "gene",
          val "Klra1"
        },
        {
          qual "product",
          val "killer cell lectin-like receptor, subfamily A, member 1"
        },
        {
          qual "transcript_id",
          val "NM_016659.3"
        }
      },
      xref {
        {
          id local id 46
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16627
        },
        {
          db "Genbank",
          tag str "NM_016659.3"
        },
        {
          db "MGI",
          tag str "MGI:101907"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 46,
      data cdregion {
        frame one
      },
      except TRUE,
      comment "The RefSeq protein has 3 substitutions compared to this genomic
 sequence",
      location mix {
        int {
          from 332676,
          to 332787,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        },
        int {
          from 331124,
          to 331213,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "ID",
          val "cds5"
        },
        {
          qual "gene",
          val "Klra1"
        },
        {
          qual "product",
          val "T-cell surface glycoprotein YE1/48"
        },
        {
          qual "protein_id",
          val "NP_057868.2"
        },
        {
          qual "Parent",
          val "rna6"
        }
      },
      xref {
        {
          id local id 45
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 16627
        },
        {
          db "Genbank",
          tag str "NP_057868.2"
        },
        {
          db "MGI",
          tag str "MGI:101907"
        }
      },
      except-text "annotated by transcript or proteomic data"
    },
    {
      id local id 47,
      data imp {
        key "STS"
      },
      location int {
        from 316835,
        to 317145,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id6784"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 166310
        }
      }
    },
    {
      id local id 48,
      data imp {
        key "STS"
      },
      location int {
        from 329847,
        to 331192,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id7677"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 143704
        }
      }
    },
    {
      id local id 49,
      data imp {
        key "STS"
      },
      location int {
        from 334439,
        to 335458,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id8000"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 143705
        }
      }
    },
    {
      id local id 50,
      data imp {
        key "STS"
      },
      location int {
        from 336945,
        to 337042,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id8131"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 507756
        }
      }
    },
    {
      id local id 51,
      data imp {
        key "STS"
      },
      location int {
        from 341390,
        to 341494,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id8319"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 258434
        }
      }
    },
    {
      id local id 52,
      data imp {
        key "STS"
      },
      location int {
        from 360101,
        to 361068,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id9155"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 474272
        }
      }
    },
    {
      id local id 53,
      data imp {
        key "STS"
      },
      location int {
        from 432651,
        to 433027,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id12161"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 143708
        }
      }
    },
    {
      id local id 54,
      data imp {
        key "STS"
      },
      location int {
        from 432651,
        to 433026,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id12162"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 132208
        }
      }
    },
    {
      id local id 55,
      data imp {
        key "STS"
      },
      location int {
        from 432875,
        to 433025,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id12168"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 166312
        }
      }
    },
    {
      id local id 56,
      data gene {
        locus "Gm38706"
      },
      location int {
        from 434774,
        to 472644,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "gene7"
        },
        {
          qual "Name",
          val "Gm38706"
        },
        {
          qual "gene_biotype",
          val "pseudogene"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 105242439
        },
        {
          db "MGI",
          tag str "MGI:5621591"
        }
      },
      pseudo TRUE
    },
    {
      id local id 57,
      data imp {
        key "exon"
      },
      location int {
        from 434774,
        to 436103,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "Parent",
          val "gene7"
        },
        {
          qual "ID",
          val "id12241"
        },
        {
          qual "gene",
          val "Gm38706"
        },
        {
          qual "model_evidence",
          val "Supporting evidence includes similarity to: 1 Protein"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 105242439
        },
        {
          db "MGI",
          tag str "MGI:5621591"
        }
      }
    },
    {
      id local id 58,
      data imp {
        key "exon"
      },
      location int {
        from 471697,
        to 472029,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "Parent",
          val "gene7"
        },
        {
          qual "ID",
          val "id13688"
        },
        {
          qual "gene",
          val "Gm38706"
        },
        {
          qual "model_evidence",
          val "Supporting evidence includes similarity to: 1 Protein"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 105242439
        },
        {
          db "MGI",
          tag str "MGI:5621591"
        }
      }
    },
    {
      id local id 59,
      data imp {
        key "exon"
      },
      location int {
        from 472210,
        to 472252,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "Parent",
          val "gene7"
        },
        {
          qual "ID",
          val "id13714"
        },
        {
          qual "gene",
          val "Gm38706"
        },
        {
          qual "model_evidence",
          val "Supporting evidence includes similarity to: 1 Protein"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 105242439
        },
        {
          db "MGI",
          tag str "MGI:5621591"
        }
      }
    },
    {
      id local id 60,
      data imp {
        key "exon"
      },
      location int {
        from 472537,
        to 472644,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "Parent",
          val "gene7"
        },
        {
          qual "ID",
          val "id13734"
        },
        {
          qual "gene",
          val "Gm38706"
        },
        {
          qual "model_evidence",
          val "Supporting evidence includes similarity to: 1 Protein"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 105242439
        },
        {
          db "MGI",
          tag str "MGI:5621591"
        }
      }
    },
    {
      id local id 61,
      data imp {
        key "STS"
      },
      location int {
        from 475073,
        to 475269,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id13863"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 166311
        }
      }
    },
    {
      id local id 62,
      data imp {
        key "STS"
      },
      location int {
        from 491841,
        to 491993,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id14356"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 257281
        }
      }
    },
    {
      id local id 63,
      data imp {
        key "STS"
      },
      location int {
        from 508963,
        to 509076,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id14989"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 257631
        }
      }
    },
    {
      id local id 64,
      data imp {
        key "STS"
      },
      location int {
        from 521782,
        to 521914,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id15434"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 142655
        }
      }
    },
    {
      id local id 65,
      data gene {
        locus "Gm8816",
        desc "predicted gene 8816",
        syn {
          "EG667793"
        }
      },
      location int {
        from 526095,
        to 528226,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "gene8"
        },
        {
          qual "Name",
          val "Gm8816"
        },
        {
          qual "gene_biotype",
          val "pseudogene"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 667793
        },
        {
          db "MGI",
          tag str "MGI:3648634"
        }
      },
      pseudo TRUE
    },
    {
      id local id 66,
      data imp {
        key "exon"
      },
      location int {
        from 526095,
        to 528226,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "Parent",
          val "gene8"
        },
        {
          qual "ID",
          val "id15548"
        },
        {
          qual "gene",
          val "Gm8816"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 667793
        },
        {
          db "MGI",
          tag str "MGI:3648634"
        }
      }
    },
    {
      id local id 67,
      data imp {
        key "STS"
      },
      location int {
        from 534037,
        to 534229,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id15765"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 166305
        }
      }
    },
    {
      id local id 68,
      data gene {
        locus "Gm20997"
      },
      location int {
        from 536046,
        to 538621,
        strand minus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "gene9"
        },
        {
          qual "Name",
          val "Gm20997"
        },
        {
          qual "gene_biotype",
          val "protein_coding"
        },
        {
          qual "start_range",
          val "."
        },
        {
          qual "start_range",
          val "536047"
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 100504950
        },
        {
          db "MGI",
          tag str "MGI:5434352"
        }
      }
    },
    {
      id local id 69,
      data rna {
        type mRNA
      },
      except TRUE,
      comment "The sequence of the model RefSeq transcript was modified
 relative to this genomic sequence to represent the inferred CDS: inserted 1
 base in 1 codon",
      location mix {
        int {
          from 538387,
          to 538621,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "Parent",
          val "gene9"
        },
        {
          qual "ID",
          val "rna7"
        },
        {
          qual "gene",
          val "Gm20997"
        },
        {
          qual "model_evidence",
          val "Supporting evidence includes similarity to: 9 Proteins, and 4%
 coverage of the annotated genomic feature by RNAseq alignments"
        },
        {
          qual "product",
          val "predicted gene, 20997, transcript variant X1"
        },
        {
          qual "start_range",
          val "."
        },
        {
          qual "start_range",
          val "536047"
        },
        {
          qual "transcript_id",
          val "XM_017319046.1"
        }
      },
      xref {
        {
          id local id 70
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 100504950
        },
        {
          db "Genbank",
          tag str "XM_017319046.1"
        },
        {
          db "MGI",
          tag str "MGI:5434352"
        }
      },
      except-text "unclassified transcription discrepancy"
    },
    {
      id local id 70,
      data cdregion {
        frame one
      },
      except TRUE,
      comment "The sequence of the model RefSeq protein was modified relative
 to this genomic sequence to represent the inferred CDS: inserted 1 base in 1
 codon",
      location mix {
        int {
          from 538387,
          to 538621,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        },
        int {
          from 536046,
          to 538233,
          strand minus,
          id other {
            accession "NW_006763130",
            version 1
          }
        }
      },
      qual {
        {
          qual "ID",
          val "cds6"
        },
        {
          qual "gene",
          val "Gm20997"
        },
        {
          qual "product",
          val "LOW QUALITY PROTEIN: zinc finger protein 665-like isoform X1"
        },
        {
          qual "protein_id",
          val "XP_017174535.1"
        },
        {
          qual "Parent",
          val "rna7"
        }
      },
      xref {
        {
          id local id 69
        }
      },
      dbxref {
        {
          db "GeneID",
          tag id 100504950
        },
        {
          db "Genbank",
          tag str "XP_017174535.1"
        },
        {
          db "MGI",
          tag str "MGI:5434352"
        }
      },
      except-text "unclassified translation discrepancy"
    },
    {
      id local id 71,
      data imp {
        key "STS"
      },
      location int {
        from 566101,
        to 566449,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id16437"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 257691
        }
      }
    },
    {
      id local id 72,
      data imp {
        key "STS"
      },
      location int {
        from 566556,
        to 566655,
        strand plus,
        id other {
          accession "NW_006763130",
          version 1
        }
      },
      qual {
        {
          qual "ID",
          val "id16447"
        }
      },
      dbxref {
        {
          db "UniSTS",
          tag id 257868
        }
      }
    }
  }
}
