Seq-annot ::= {
  desc {
    user {
      type str "vcf-meta-info",
      data {
        {
          label str "meta-information",
          num 8,
          data strs {
            "fileformat=VCFv4.1",
            "INFO=<ID=DB,Number=0,Type=Flag,Description=""dbSNP Membership"">",
            "INFO=<ID=H2,Number=0,Type=Flag,Description=""Hapmap2 Membership"">",
            "INFO=<ID=H3,Number=0,Type=Flag,Description=""Hapmap3 Membership"">",
            "INFO=<ID=RL,Number=1,Type=String,Description=""Resource Link"">",
            "INFO=<ID=FBV,Number=1,Type=String,Description=""Frequency Based
 Validation"">",
            "INFO=<ID=GTP,Number=1,Type=String,Description=""Genotype"">",
            "INFO=<ID=QC,Number=1,Type=String,Description=""Quality Check"">"
          }
        }
      }
    }
  },
  data ftable {
    {
      data variation {
        id {
          db "dbSNP",
          tag str "rs000"
        },
        variant-prop {
          version 5,
          resource-link preserved,
          gene-location 0,
          effect no-change,
          mapping 0,
          frequency-based-validation 0,
          genotype 0,
          quality-check 0
        },
        data set {
          type package,
          variations {
            {
              data instance {
                type identity,
                delta {
                  {
                    seq literal {
                      length 1,
                      seq-data iupacna "A"
                    }
                  }
                },
                observation reference
              }
            },
            {
              data instance {
                type snv,
                delta {
                  {
                    seq literal {
                      length 1,
                      seq-data iupacna "G"
                    }
                  }
                }
              }
            },
            {
              data instance {
                type snv,
                delta {
                  {
                    seq literal {
                      length 1,
                      seq-data iupacna "C"
                    }
                  }
                }
              }
            }
          }
        }
      },
      location pnt {
        point 0,
        id other {
          accession "NC_000008",
          version 10
        }
      },
      ext {
        type str "VcfAttributes",
        data {
          {
            label str "filter",
            data str "PASS"
          },
          {
            label str "info",
            data str "DB"
          }
        }
      }
    }
  }
}
