ANTLR_DIR=../../../external/pccts

include $(ANTLR_DIR)/makefile.mk

# user defined names
GRM = parser
PGM = parser
CLASS = ASNParser
OBJ = asntype.o asnvalue.o asnmodule.o

include $(ANTLR_DIR)/makefile.mkg

